### ISSUE TITLE
Can't start faraday

### ISSUE THREAD

**Issue by blacksecdefault** [infobyte/faraday#104]
_____                           .___
_/ ____\_____  ____________     __| _/_____   ___.__.
\   __\ \__  \ \_  __ \__  \   / __ | \__  \ <   |  |
 |  |    / __ \_|  | \// __ \_/ /_/ |  / __ \_\___  |
 |__|   (____  /|__|  (____  /\____ | (____  // ____|
             \/            \/      \/      \/ \/
    
[*[       Open Source Penetration Test IDE       ]*]
            Where pwnage goes multiplayer

2016-07-19 17:15:19,605 - faraday.launcher - INFO - Starting Faraday IDE.
2016-07-19 17:15:19,605 - faraday.launcher - INFO - Dependencies met.
2016-07-19 17:15:19,606 - faraday.launcher - INFO - Checking configuration.
2016-07-19 17:15:19,606 - faraday.launcher - INFO - Setting up plugins.
2016-07-19 17:15:19,606 - faraday.launcher - INFO - Removing old plugins folder
2016-07-19 17:15:19,682 - faraday.launcher - INFO - Setting up ZSH integration.
2016-07-19 17:15:19,683 - faraday.launcher - INFO - Setting up  user configuration.
2016-07-19 17:15:19,683 - faraday.launcher - INFO - Using custom user configuration.
2016-07-19 17:15:19,683 - faraday.launcher - INFO - Setting up libraries.
2016-07-19 17:15:19,687 - faraday.launcher - INFO - x86_64 linux detected.
2016-07-19 17:15:19,693 - faraday.launcher - INFO - Setting configuration.
2016-07-19 17:15:20,033 - faraday.launcher - INFO - All done. Opening environment.
Traceback (most recent call last):
  File "./faraday.py", line 533, in <module>
    main()
  File "./faraday.py", line 529, in main
    startFaraday()
  File "./faraday.py", line 262, in startFaraday
    main_app = MainApplication(args)
  File "/usr/share/python-faraday/model/application.py", line 99, in __init__
    self.args.gui)
  File "/usr/share/python-faraday/gui/gui_app.py", line 25, in create
    return GuiApp(model_controller, plugin_manager, workspace_manager, plugin_controller)
  File "/usr/share/python-faraday/gui/gtk/application.py", line 100, in __init__
    16, False)
GLib.Error: g-file-error-quark: Failed to open file '/root/.faraday/images/icons/faraday_icon.png': No such file or directory (4)

**Comment by joaquinlpereyra** [comment]
Hey @blacksecdefault! We're sorry we encountered trouble. We know about this issue, and luckily it has a simple fix and it will be fixed in the next release. 

Just run: 
```cp -r $FARADAY_DIR/data/images/icons/ ~/.faraday/images/icons/```

Of course replace $FARADAY_DIR with your Faraday installation path. 

Let us know if this fixed it!

**Comment by blacksecdefault** [comment]
Tnx for the fast response! Worked like a charm.
