### ISSUE TITLE
Start up Error - [Errno 98] Address already in use

### ISSUE THREAD

**Issue by JonLittleIT** [infobyte/faraday#136]
2016-09-28 12:16:10,842 - faraday - INFO - There was an error creating the XMLRPC API Server:
[Errno 98] Address already in use
There was an error while starting Faraday
--------------------------------------------------
Traceback (most recent call last):
  File "/usr/share/python-faraday/model/application.py", line 170, in start
    CONF.getApiRestfulConInfoPort())
  File "/usr/share/python-faraday/apis/rest/api.py", line 53, in startAPIs
    _http_server.listen(port, address=hostname)
  File "/usr/lib/python2.7/dist-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 182, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
--------------------------------------------------
2016-09-28 12:16:12,849 - faraday - INFO - Please configure Couchdb for fancy HTML5 Dashboard (https://github.com/infobyte/faraday/wiki/Couchdb)

**Comment by Ezequieltbh** [comment]
Hi!
What version are you using?
This bug should be fixed in the lastest versions.
Cheers

**Comment by JonLittleIT** [comment]
__\ \__  \ \_  __ \__  \   / __ | \__  \ <   |  |
 |  |    / __ \_|  | \// __ \_/ /_/ |  / __ \_\___  |
 |__|   (____  /|__|  (____  /\____ | (____  // ____|
             \/            \/      \/      \/ \/
    
[*[       Open Source Penetration Test IDE       ]*]
            Where pwnage goes multiplayer

2016-09-28 13:46:42,721 - faraday.launcher - INFO - Starting Faraday IDE.
2016-09-28 13:46:42,721 - faraday.launcher - INFO - Dependencies met.
2016-09-28 13:46:42,721 - faraday.launcher - INFO - Checking configuration.
2016-09-28 13:46:42,721 - faraday.launcher - INFO - Setting up plugins.
2016-09-28 13:46:42,721 - faraday.launcher - INFO - Removing old plugins folder.
2016-09-28 13:46:42,791 - faraday.launcher - INFO - Setting up ZSH integration.
2016-09-28 13:46:42,792 - faraday.launcher - INFO - Setting up user configuration.
2016-09-28 13:46:42,793 - faraday.launcher - INFO - Copying default configuration from project.
2016-09-28 13:46:42,804 - faraday.launcher - INFO - Setting up icons for GTK interface.
2016-09-28 13:46:42,814 - faraday.launcher - INFO - Setting configuration.
2016-09-28 13:46:43,304 - faraday.launcher - INFO - All done. Opening environment.
2016-09-28 13:46:43,671 - faraday.launcher - INFO - Main application ExceptHook enabled.
2016-09-28 13:46:43,671 - faraday.launcher - INFO - Starting main application.
Please config Couchdb for fancy HTML5 Dashboard (https://github.com/infobyte/faraday/wiki/Couchdb)

2016-09-28 13:46:43,674 - faraday - INFO - XMLRPC API server configured on ('localhost', 9876)
2016-09-28 13:46:43,686 - faraday - INFO - REST API server configured on ('localhost', 9977)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/share/python-faraday/utils/error_report.py", line 83, in exception_handler
    model.guiapi.postCustomEvent(event)
  File "/usr/share/python-faraday/model/guiapi.py", line 38, in postCustomEvent
    receiver = getMainWindow()
  File "/usr/share/python-faraday/model/guiapi.py", line 34, in getMainWindow
    return __the_mainapp.getMainWindow()
AttributeError: 'NoneType' object has no attribute 'getMainWindow'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/python-faraday/gui/gtk/application.py", line 615, in do_startup
    CONF.getLastWorkspace())
  File "/usr/share/python-faraday/gui/gtk/mainwidgets.py", line 430, in __init__
    self.workspaces = self.serverIO.get_workspaces_names()
  File "/usr/share/python-faraday/gui/gtk/decorators.py", line 16, in wrapper
    res = func(*args, **kwargs)
  File "/usr/share/python-faraday/gui/gtk/server.py", line 67, in get_workspaces_names
    return models.get_workspaces_names()
  File "/usr/share/python-faraday/persistence/server/models.py", line 479, in get_workspaces_names
    return server.get_workspaces_names()['workspaces']
  File "/usr/share/python-faraday/persistence/server/server.py", line 380, in get_workspaces_names
    return _get("{0}/ws".format(_create_server_api_url()))
  File "/usr/share/python-faraday/persistence/server/server.py", line 124, in _get
    params=params))
  File "/usr/share/python-faraday/persistence/server/server.py", line 90, in _unsafe_io_with_server
    answer = server_io_function(server_url, **payload)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None/_api/ws': No schema supplied. Perhaps you meant http://None/_api/ws?
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/share/python-faraday/utils/error_report.py", line 83, in exception_handler
    model.guiapi.postCustomEvent(event)
  File "/usr/share/python-faraday/model/guiapi.py", line 38, in postCustomEvent
    receiver = getMainWindow()
  File "/usr/share/python-faraday/model/guiapi.py", line 34, in getMainWindow
    return __the_mainapp.getMainWindow()
AttributeError: 'NoneType' object has no attribute 'getMainWindow'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/python-faraday/gui/gtk/application.py", line 676, in do_activate
    self.window = AppWindow(self.sidebar,
AttributeError: 'GuiApp' object has no attribute 'sidebar'
2016-09-28 13:46:44,739 - faraday - INFO - Closing Faraday...

**Comment by Ezequieltbh** [comment]
You need write the couch_uri tag xml in ~/.faraday/config/user.xml
'http://localhost:5985/'
We are reviewing this bug and we can fix this in later versions.
Cheers!

**Comment by JonLittleIT** [comment]
what directory is this file?


root@SantaClause:/usr/share/python-faraday# ~/.faraday/config/user.xml
bash: /root/.faraday/config/user.xml: Permission denied

**Comment by Ezequieltbh** [comment]
Is a text file!
You need use a text editor, should be in $HOME/.faraday/config/user.xml

**Comment by JonLittleIT** [comment]
Ok I edited it 👍 
Make sure you got couchdb up and running.
If couchdb is up, point your browser to: 
[http://localhost:5985/_ui]

2016-09-29 13:09:23,565 - faraday - INFO - XMLRPC API server configured on ('localhost', 9876)
2016-09-29 13:09:23,588 - faraday - INFO - REST API server configured on ('localhost', 9977)
2016-09-29 13:09:24,180 - faraday.GTK - ERROR - Workspace keck wasn't found
2016-09-29 13:09:28,986 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:09:31,007 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:09:38,281 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db2 with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:01,932 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:02,390 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:02,814 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:03,315 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:03,658 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:04,179 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:04,542 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:04,891 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:05,261 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:05,678 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:06,065 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:20,065 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:28,659 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:29,305 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:29,661 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:29,929 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:30,265 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:30,576 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:30,896 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:31,228 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:31,588 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.
2016-09-29 13:10:31,936 - faraday.GTK - ERROR - Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/ws/test_suite_db with parameters {'params': {}} and function <function get at 0x7f228d275aa0>.

**Comment by JonLittleIT** [comment]
the web GUI is working for me but I get the error above when trying to load console...also can you upload Qualys scan data through web GUI?

**Comment by JonLittleIT** [comment]
I just added the missing workspace in the web GUI and now it loads with no errors! I guess it lost the created workspace so once I added it with same name it works fine.

**Comment by Ezequieltbh** [comment]
Ok, we know the problem here.

You run the verify installation in couchdb, /_utils maybe?
It create two databases 'test_suite_db' and 'test_suite_db2', this trigger errors in GTK.
You can run this commands for delete this databases, restart Faraday Server and create a new workspace in WebUi for start working!

curl -X DELETE 'http://faraday:faraday@localhost:5985/test_suite_db'
curl -X DELETE 'http://faraday:faraday@localhost:5985/test_suite_db2'

Sorry for the troubles!
Cheers!

**Comment by JonLittleIT** [comment]
I just re-created the workspace that was missing on boot-up and now it works.

**Comment by Ezequieltbh** [comment]
Excelent!
Issue close then...
Cheers!
