### ISSUE TITLE
red hat install

### ISSUE THREAD

**Issue by mgaulton** [infobyte/faraday#179]
Hey Guys, 

trying to install on a Red Hat 7 instance (not my first choice but that's what they user here) and running into the below. I tweaked the install to replace apt-get with yum and everything seemed to go smoothly.

Any suggestions?

Traceback (most recent call last):
  File "./faraday-server.py", line 14, in <module>
    from utils.dependencies import DependencyChecker
  File "/home/mgaulton/faraday-dev/utils/dependencies.py", line 9, in <module>
    import pkg_resources
  File "/root/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/root/.local/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

**Comment by Ezequieltbh** [comment]
Hi @mgaulton!

This seems be a problem with your python modules, can you try this commands?
```
python -m pip install --upgrade --force pip 
pip install setuptools==33.1.1
```
These commands, try upgrade your pip and setuptools modules.
Let me know if works.
Cheers!

**Comment by Ezequieltbh** [comment]
Hi @mgaulton !
Any news about this?
