### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by hktalent** [infobyte/faraday#180]
# 1、mac os 10.12.3
```
$ uname -a
Darwin QQ1160.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```
# 2、info
```
$ git pull
Already up-to-date.
QQ1160:faraday-dev xiatian$ pwd
/Users/xiatian/pp/faraday-dev
QQ1160:faraday-dev xiatian$ gitv
origin	https://github.com/infobyte/faraday.git (fetch)
origin	https://github.com/infobyte/faraday.git (push)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```
# 3、install
```
$ ./install.sh
You must be root.
QQ1160:faraday-dev xiatian$ sudo ./install.sh
[+] Install Darwin 16.4.0 x86_64
./install.sh: line 56: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-get: command not found
The directory '/Users/xiatian/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/xiatian/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: couchdbkit in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: mockito in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: whoosh in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: argparse in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: IPy in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: restkit in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: requests in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: tornado in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: flask in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: colorama in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: psycopg2 in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied: funcsigs in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from mockito->-r requirements.txt (line 2))
Requirement already satisfied: http-parser>=0.8.3 in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from restkit->-r requirements.txt (line 6))
Requirement already satisfied: socketpool>=0.5.3 in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from restkit->-r requirements.txt (line 6))
Requirement already satisfied: singledispatch in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from tornado->-r requirements.txt (line 8))
Requirement already satisfied: certifi in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from tornado->-r requirements.txt (line 8))
Requirement already satisfied: backports_abc>=0.4 in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from tornado->-r requirements.txt (line 8))
Requirement already satisfied: Jinja2>=2.4 in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from flask->-r requirements.txt (line 9))
Requirement already satisfied: Werkzeug>=0.7 in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from flask->-r requirements.txt (line 9))
Requirement already satisfied: click>=2.0 in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from flask->-r requirements.txt (line 9))
Requirement already satisfied: itsdangerous>=0.21 in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from flask->-r requirements.txt (line 9))
Requirement already satisfied: six in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from singledispatch->tornado->-r requirements.txt (line 8))
Requirement already satisfied: MarkupSafe>=0.23 in /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (from Jinja2>=2.4->flask->-r requirements.txt (line 9))
You can now run Faraday, enjoy!

```

$ sudo ./faraday.py --update
```

  _____                           .___
_/ ____\_____  ____________     __| _/_____   ___.__.
\   __\ \__  \ \_  __ \__  \   / __ | \__  \ <   |  |
 |  |    / __ \_|  | \// __ \_/ /_/ |  / __ \_\___  |
 |__|   (____  /|__|  (____  /\____ | (____  // ____|
             \/            \/      \/      \/ \/
    
[*[       Open Source Penetration Test IDE       ]*]
            Where pwnage goes multiplayer

2017-02-27 14:45:40,155 - faraday.launcher - INFO - Starting Faraday IDE.
2017-02-27 14:45:40,155 - faraday.launcher - INFO - Dependencies met.
2017-02-27 14:45:40,155 - faraday.launcher - INFO - Checking configuration.
2017-02-27 14:45:40,156 - faraday.launcher - INFO - Setting up plugins.
2017-02-27 14:45:40,156 - faraday.launcher - INFO - Removing old plugins folder.
2017-02-27 14:45:40,241 - faraday.launcher - INFO - Setting up ZSH integration.
2017-02-27 14:45:40,242 - faraday.launcher - INFO - Setting up user configuration.
2017-02-27 14:45:40,242 - faraday.launcher - INFO - Using custom user configuration.
2017-02-27 14:45:40,242 - faraday.launcher - INFO - Setting up icons for GTK interface.
2017-02-27 14:45:40,258 - faraday.launcher - INFO - Setting configuration.
2017-02-27 14:45:41,403 - faraday.Updater - INFO - Removing old pyc files
2017-02-27 14:45:41,429 - faraday.Updater - INFO - Pulling latest Github Master copy
Proceed? [Y/n] y
Already up-to-date.
2017-02-27 14:45:59,209 - faraday.Updater - ERROR - Checking missing dependencies in pip
2017-02-27 14:45:59,209 - faraday.Updater - INFO - Upgrading DBs to latest version
2017-02-27 14:45:59,209 - faraday.Updater - INFO - No DB configuration found.
                    To upgrade your DB please configure a valid CouchDB URI in:
                    ~/.faraday/config/user.xml configuration file.
2017-02-27 14:45:59,209 - faraday.launcher - INFO - Update process finished with no errors
2017-02-27 14:45:59,209 - faraday.launcher - INFO - Faraday will start now.
2017-02-27 14:46:03,735 - faraday.launcher - ERROR - HTTPSConnectionPool(host='www.faradaysec.com', port=443): Max retries exceeded with url: /scripts/updates.php?version=2.3.1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10266a750>, 'Connection to www.faradaysec.com timed out. (connect timeout=1)'))
2017-02-27 14:46:03,735 - faraday.launcher - INFO - No updates available, enjoy Faraday.
2017-02-27 14:46:03,939 - faraday.launcher - INFO - All done. Opening environment.
You are missing Gobject Instrospection. Please install version 3.14 or above (recommended) or 3.12
```
$ pip list |grep gi
```
gi (1.2)
packaging (16.8)
```

$ sudo ./faraday.py
```

  _____                           .___
_/ ____\_____  ____________     __| _/_____   ___.__.
\   __\ \__  \ \_  __ \__  \   / __ | \__  \ <   |  |
 |  |    / __ \_|  | \// __ \_/ /_/ |  / __ \_\___  |
 |__|   (____  /|__|  (____  /\____ | (____  // ____|
             \/            \/      \/      \/ \/
    
[*[       Open Source Penetration Test IDE       ]*]
            Where pwnage goes multiplayer

2017-02-27 14:47:49,102 - faraday.launcher - INFO - Starting Faraday IDE.
2017-02-27 14:47:49,102 - faraday.launcher - INFO - Dependencies met.
2017-02-27 14:47:49,102 - faraday.launcher - INFO - Checking configuration.
2017-02-27 14:47:49,102 - faraday.launcher - INFO - Setting up plugins.
2017-02-27 14:47:49,103 - faraday.launcher - INFO - Removing old plugins folder.
2017-02-27 14:47:49,159 - faraday.launcher - INFO - Setting up ZSH integration.
2017-02-27 14:47:49,160 - faraday.launcher - INFO - Setting up user configuration.
2017-02-27 14:47:49,160 - faraday.launcher - INFO - Using custom user configuration.
2017-02-27 14:47:49,161 - faraday.launcher - INFO - Setting up icons for GTK interface.
2017-02-27 14:47:49,179 - faraday.launcher - INFO - Setting configuration.
2017-02-27 14:47:53,415 - faraday.launcher - ERROR - HTTPSConnectionPool(host='www.faradaysec.com', port=443): Max retries exceeded with url: /scripts/updates.php?version=2.3.1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109506550>, 'Connection to www.faradaysec.com timed out. (connect timeout=1)'))
2017-02-27 14:47:53,415 - faraday.launcher - INFO - No updates available, enjoy Faraday.
2017-02-27 14:47:53,571 - faraday.launcher - INFO - All done. Opening environment.
You are missing Gobject Instrospection. Please install version 3.14 or above (recommended) or 3.12
```
$ sudo chown -R xiatian:staff /Users/xiatian/.faraday
$ ./faraday.py
```

  _____                           .___
_/ ____\_____  ____________     __| _/_____   ___.__.
\   __\ \__  \ \_  __ \__  \   / __ | \__  \ <   |  |
 |  |    / __ \_|  | \// __ \_/ /_/ |  / __ \_\___  |
 |__|   (____  /|__|  (____  /\____ | (____  // ____|
             \/            \/      \/      \/ \/
    
[*[       Open Source Penetration Test IDE       ]*]
            Where pwnage goes multiplayer

2017-02-27 14:49:28,403 - faraday.launcher - INFO - Starting Faraday IDE.
2017-02-27 14:49:28,404 - faraday.launcher - INFO - Dependencies met.
2017-02-27 14:49:28,404 - faraday.launcher - INFO - Checking configuration.
2017-02-27 14:49:28,404 - faraday.launcher - INFO - Setting up plugins.
2017-02-27 14:49:28,404 - faraday.launcher - INFO - Removing old plugins folder.
2017-02-27 14:49:28,474 - faraday.launcher - INFO - Setting up ZSH integration.
2017-02-27 14:49:28,475 - faraday.launcher - INFO - Setting up user configuration.
2017-02-27 14:49:28,476 - faraday.launcher - INFO - Using custom user configuration.
2017-02-27 14:49:28,476 - faraday.launcher - INFO - Setting up icons for GTK interface.
2017-02-27 14:49:28,495 - faraday.launcher - INFO - Setting configuration.
2017-02-27 14:49:32,885 - faraday.launcher - ERROR - HTTPSConnectionPool(host='www.faradaysec.com', port=443): Max retries exceeded with url: /scripts/updates.php?version=2.3.1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10f248950>, 'Connection to www.faradaysec.com timed out. (connect timeout=1)'))
2017-02-27 14:49:32,886 - faraday.launcher - INFO - No updates available, enjoy Faraday.
2017-02-27 14:49:33,041 - faraday.launcher - INFO - All done. Opening environment.
You are missing Gobject Instrospection. Please install version 3.14 or above (recommended) or 3.12
```

**Comment by hktalent** [comment]
in browser 
https://www.faradaysec.com/scripts/updates.php?version=2.0.0
return
UPDATE

**Comment by hktalent** [comment]
$ ./faraday.py -d --update 
```

  _____                           .___
_/ ____\_____  ____________     __| _/_____   ___.__.
\   __\ \__  \ \_  __ \__  \   / __ | \__  \ <   |  |
 |  |    / __ \_|  | \// __ \_/ /_/ |  / __ \_\___  |
 |__|   (____  /|__|  (____  /\____ | (____  // ____|
             \/            \/      \/      \/ \/
    
[*[       Open Source Penetration Test IDE       ]*]
            Where pwnage goes multiplayer

2017-02-27 14:57:06,871 - faraday.launcher - INFO - Starting Faraday IDE.
2017-02-27 14:57:06,872 - faraday.launcher - INFO - Dependencies met.
2017-02-27 14:57:06,872 - faraday.launcher - INFO - Checking configuration.
2017-02-27 14:57:06,872 - faraday.launcher - INFO - Setting up plugins.
2017-02-27 14:57:06,872 - faraday.launcher - INFO - Removing old plugins folder.
2017-02-27 14:57:06,961 - faraday.launcher - INFO - Setting up ZSH integration.
2017-02-27 14:57:06,962 - faraday.launcher - INFO - Setting up user configuration.
2017-02-27 14:57:06,962 - faraday.launcher - INFO - Using custom user configuration.
2017-02-27 14:57:06,962 - faraday.launcher - INFO - Setting up icons for GTK interface.
2017-02-27 14:57:06,977 - faraday.launcher - INFO - Setting configuration.
2017-02-27 14:57:07,783 - faraday.Updater - INFO - Removing old pyc files
2017-02-27 14:57:08,051 - faraday.Updater - INFO - Pulling latest Github Master copy
Proceed? [Y/n] y
Already up-to-date.
2017-02-27 14:57:15,308 - faraday.Updater - ERROR - Checking missing dependencies in pip
2017-02-27 14:57:15,308 - faraday.Updater - INFO - Upgrading DBs to latest version
2017-02-27 14:57:15,308 - faraday.Updater - INFO - No DB configuration found.
                    To upgrade your DB please configure a valid CouchDB URI in:
                    ~/.faraday/config/user.xml configuration file.
2017-02-27 14:57:15,308 - faraday.launcher - INFO - Update process finished with no errors
2017-02-27 14:57:15,308 - faraday.launcher - INFO - Faraday will start now.
2017-02-27 14:57:19,357 - faraday.launcher - ERROR - HTTPSConnectionPool(host='www.faradaysec.com', port=443): Read timed out. (read timeout=1)
2017-02-27 14:57:19,357 - faraday.launcher - INFO - No updates available, enjoy Faraday.
2017-02-27 14:57:19,561 - faraday.launcher - INFO - All done. Opening environment.
You are missing Gobject Instrospection. Please install version 3.14 or above (recommended) or 3.12
```

**Comment by hktalent** [comment]
$ cat ~/.faraday/config/config.xml 
```
<?xml version="1.0"?>
<faraday>

    <appname>Faraday - Penetration Test IDE</appname>
    <version>2.0.0</version>
    <debug_status>0</debug_status>
    <font>-Misc-Fixed-medium-r-normal-*-12-100-100-100-c-70-iso8859-1</font>
    <home_path>~/</home_path>
    <image_path>~/.faraday/images/</image_path>>
    <icons_path>~/.faraday/images/icons/</icons_path>
    <data_path>~/.faraday/data</data_path>
    <config_path>~/.faraday/</config_path>
    <default_temp_path>~/.faraday/temp/</default_temp_path>
    <persistence_path>~/.faraday/persistence/</persistence_path>
    <report_path>~/.faraday/report/</report_path>
    <hstactions_path>~/.faraday/hstactions.dat</hstactions_path>

    <default_category>General</default_category>
    <auto_share_workspace>1</auto_share_workspace>
    <network_location>LAN</network_location>
    <perspective_view>Hosts</perspective_view>
    <log_console_toggle></log_console_toggle>
    <shell_maximized>0</shell_maximized>
    <host_tree_toggle></host_tree_toggle>

    <api_con_info>None</api_con_info>
    <api_con_info_host>None</api_con_info_host>
    <api_con_info_port>None</api_con_info_port>
    <auth encrypted="no" algorithm="OTR">0</auth>
    <repo_url type="svn"></repo_url>
    <repo_user>u</repo_user>
    <repo_password></repo_password>
    <couch_uri/>
    <couch_is_replicated/>
    <couch_replics/>

    <updates_uri>https://www.faradaysec.com/scripts/updates.php</updates_uri>
    <tickets_uri>https://www.faradaysec.com/scripts/listener.php</tickets_uri>
    <tickets_template>{}</tickets_template>
    <tickets_api>{}</tickets_api>


</faraday>
```

**Comment by hktalent** [comment]
i try
```
sudo chmod 040777 /usr/local/ant/bin
sudo pip install --ignore-installed --trusted-host pypi.douban.com  -i http://pypi.douban.com/simple -r requirements.txt
sudo pip install --ignore-installed --trusted-host pypi.douban.com  -i http://pypi.douban.com/simple sqlalchemy pyopenssl
sudo pip install --ignore-installed --trusted-host pypi.douban.com  -i http://pypi.douban.com/simple pyopenssl
pip install gi
pip install urllib3
sudo port selfupdate
sudo port install gobject-introspection
gem install gobject-introspection

```
brew install CouchDB
brew services restart couchdb;brew services list
$ /usr/local/opt/couchdb/bin/couchdb &
```
=INFO REPORT==== 27-Feb-2017::15:15:08 ===
    alarm_handler: {set,{{disk_almost_full,"/Volumes/dbdata"},[]}}
Apache CouchDB 1.6.1 (LogLevel=info) is starting.
Apache CouchDB has started. Time to relax.
[info] [<0.56.0>] Apache CouchDB has started on http://127.0.0.1:5984/

```
$ brew info CouchDB
```
CouchDB: stable 1.6.1 (bottled), HEAD
Document database server
https://couchdb.apache.org/
/usr/local/Cellar/CouchDB/1.6.1_9 (639 files, 15.0M)
  Poured from bottle on 2017-01-10 at 17:41:39
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/couchdb.rb
==> Dependencies
Required: spidermonkey ✔, icu4c ✔, erlang ✔
==> Options
--with-geocouch
	Build with GeoCouch spatial index extension
--HEAD
	Install HEAD version
==> Caveats
To test CouchDB run:
    curl http://127.0.0.1:5984/
The reply should look like:
    {"couchdb":"Welcome","uuid":"....","version":"1.6.1","vendor":{"version":"1.6.1-1","name":"Homebrew"}}

To have launchd start CouchDB now and restart at login:
  brew services start CouchDB
Or, if you don't want/need a background service you can just run:
  couchdb
```

**Comment by hktalent** [comment]
$ cat /usr/local/etc/couchdb/default.ini | grep port
```
port = 5984
port = 6984

```

**Comment by hktalent** [comment]
see 
```
https://github.com/infobyte/faraday/wiki/Couchdb
https://github.com/infobyte/faraday/wiki/installation-client#osx
https://github.com/infobyte/faraday/wiki/First-steps#setup

```
do it
```
brew install zsh curl
brew install --force curl
brew install vte3 pygobject3

sudo chmod 040777 /usr/local/ant/bin
sudo chown -R xiatian:staff ~/.pyenv
easy_install --upgrade pip
$ which pip
/Users/xiatian/.pyenv/shims/pip
$ pip -V
pip 9.0.1 from /Users/xiatian/.pyenv/versions/2.7.13/lib/python2.7/site-packages (python 2.7)
ls -lA /usr/local/bin | grep pip
easy_install -U pip
sudo pip install --ignore-installed --trusted-host pypi.douban.com  -i http://pypi.douban.com/simple -r requirements.txt
sudo pip install --ignore-installed --trusted-host pypi.douban.com  -i http://pypi.douban.com/simple sqlalchemy pyopenssl
sudo pip install --ignore-installed --trusted-host pypi.douban.com  -i http://pypi.douban.com/simple pyopenssl
pip install gi
pip install urllib3
sudo port selfupdate
sudo port install gobject-introspection
gem install gobject-introspection
pip install flask twisted sqlalchemy pyopenssl python-docx docxtpl six matplotlib
pip install utils

```
$ python -c"import sys;print '当前的python是:'+sys.prefix;print '\n'.join(sys.path)"
```
当前的python是:/opt/local/Library/Frameworks/Python.framework/Versions/2.7

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/readline
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/Users/xiatian/Library/Python/2.7/lib/python/site-packages
/usr/local/lib/python2.7/site-packages
/usr/local/Cellar/protobuf/3.2.0/libexec/lib/python2.7/site-packages
/usr/local/Cellar/scapy/2.3.3/libexec/vendor/lib/python2.7/site-packages
/usr/local/lib/python2.7/site-packages/gtk-2.0
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/distribute-0.7.3-py2.7.egg
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gyp-0.1-py2.7.egg
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/shodan-1.5.6-py2.7.egg
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmdline_shellsploit-0.1-py2.7.egg
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-28.3.0-py2.7.egg
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0

```
# error
$ ./faraday-server.py
```
Traceback (most recent call last):
  File "./faraday-server.py", line 14, in <module>
    from utils.dependencies import DependencyChecker
  File "/Volumes/BOOK/安全/project/faraday-dev/utils/dependencies.py", line 8, in <module>
    import pip
ImportError: No module named pip
```

**Comment by hktalent** [comment]
cannot found the file
`./setup_server.sh`
```
$ pwd
/Users/xiatian/pp/faraday-dev
$ find . -name setup_server.sh
QQ1160:faraday-dev xiatian$ 
```

**Comment by Ezequieltbh** [comment]
Hi @hktalent !

install.sh dont support install in MacOs.
If you want install faraday in MacOs, you need follow this guide.
[](https://github.com/infobyte/faraday/wiki/installation-client#osx)

setup_server.sh is a bash script, only for commercials edition, do you have one?
Cheers!

**Comment by Ezequieltbh** [comment]
Hi @hktalent !
Any notice about this issue?

**Comment by hktalent** [comment]
@Ezequieltbh
sorry
i can't find 
setup_server.sh
