### ISSUE TITLE
Issues in installing faraday

### ISSUE THREAD

**Issue by unmesh92** [infobyte/faraday#186]
Traceback (most recent call last):
  File "./faraday-server.py", line 11, in <module>
    import server.couchdb
  File "/root/Downloads/faraday-master/server/couchdb.py", line 7, in <module>
    import requests
  File "/root/.local/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/root/.local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/root/.local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/.local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 112, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: 'FFILibrary' object has no attribute 'Cryptography_HAS_SSL_ST'

**Comment by WinnaZ** [comment]
Hello unmesh92,
I would need to know more context to understand the problem,
What version of Faraday are you using?
What is your Operating System?
What was the exact command you used to run Faraday when you got this message?
It would be very helpful if you sent us the whole Error.

You can also try:
pip install -U cffi 
pip install -U cryptography

Hope we hear from you soon,
Cheers.

**Comment by WinnaZ** [comment]
Hello unmesh92,
I would need to know more context to understand the problem,
What version of Faraday are you using?
What is your Operating System?
Are you still having this issue?
Hope we hear from you soon,
Cheers.
