### ISSUE TITLE
Password protecting the community edition docker

### ISSUE THREAD

**Issue by Robiinn** [infobyte/faraday#187]
Hi,

I have installed the docker version of Faraday community edition. I can access the web gui and link the client from a remote machine to the server by entering the url as you would in a normal installation. This happens without authentication which would be the preferred situation. 

I tried building a new docker image by changing the dockerfile to set the couchdb password in the config and setting it in both /root/faraday/server/default.ini and /root/.faraday/config/server.ini. This results in an error in the faraday.Updater when launching the container.

2017-04-06 09:51:50,056 - faraday.Updater - INFO - Preparing updates on Couchdbs
Traceback (most recent call last):
  File "./faraday.py", line 571, in <module>
    main()
  File "./faraday.py", line 563, in main
    update()
  File "./faraday.py", line 469, in update
    Updater().doUpdates()
  File "/root/faraday/updates/updater.py", line 46, in doUpdates
    CouchViews().run()
  File "/root/faraday/updates/updater.py", line 76, in run
    views_uploader.addViews(db_source, force = True)
  File "/root/faraday/managers/all.py", line 43, in addViews
    installed_views = self.getViews(workspaceDB)
  File "/root/faraday/managers/all.py", line 36, in getViews
    if result:
  File "/usr/local/lib/python2.7/dist-packages/couchdbkit/client.py", line 1068, in __nonzero__
    return bool(len(self))
  File "/usr/local/lib/python2.7/dist-packages/couchdbkit/client.py", line 1065, in __len__
    return self.count()
  File "/usr/local/lib/python2.7/dist-packages/couchdbkit/client.py", line 988, in count
    self._fetch_if_needed()
  File "/usr/local/lib/python2.7/dist-packages/couchdbkit/client.py", line 1022, in _fetch_if_needed
    self.fetch()
  File "/usr/local/lib/python2.7/dist-packages/couchdbkit/client.py", line 1001, in fetch
    self._result_cache = self.fetch_raw().json_body
  File "/usr/local/lib/python2.7/dist-packages/couchdbkit/client.py", line 1018, in fetch_raw
    return self._fetch(self._arg, self.params)
  File "/usr/local/lib/python2.7/dist-packages/couchdbkit/client.py", line 697, in raw_view
    return self.res.get(view_path, **params)
  File "/usr/local/lib/python2.7/dist-packages/restkit/resource.py", line 114, in get
    params_dict=params_dict, **params)
  File "/usr/local/lib/python2.7/dist-packages/couchdbkit/resource.py", line 111, in request
    payload=payload, headers=headers, **params)
  File "/usr/local/lib/python2.7/dist-packages/restkit/resource.py", line 204, in request
    response=resp)
restkit.errors.Unauthorized: {"error":"unauthorized","reason":"You are not authorized to access this db."}

Am I missing something in the configuration files or can I set the password in a different way for the docker image?

**Comment by Ezequieltbh** [comment]
Hi @Robiinn !
Faraday client needs username and password how basic auth in <couch_uri> tag from ~/.faraday/config/user.xml.
Faraday server need user and password in ~/.faraday/config/server.ini file, [couchdb] tag (user and password values)

**Comment by Robiinn** [comment]
Hi @Ezequieltbh 
It seems I forgot to update the client config with the new credentials. Changed user.xml now and it's working great.

**Comment by Ezequieltbh** [comment]
Great!
I close the issue, open a new if you have any comment!
