### ISSUE TITLE
Error Creating Workspace.

### ISSUE THREAD

**Issue by horusint** [infobyte/faraday#194]
We have this error creating a workspace
"Oops!
{"data":"\n<title>500 Internal Server Error</title>\n

Internal Server Error

\n
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

\n","status":500,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"url":"http://ipfaraday:5985/_api/ws/ge","data":{"_id":"ge","customer":"","sdate":1495487909831,"name":"ge","type":"Workspace","children":[],"duration":{"start":"","end":""},"scope":"","description":""},"headers":{"Accept":"application/json, text/plain, /","Content-Type":"application/json;charset=utf-8"}},"statusText":"INTERNAL SERVER ERROR"}"
On Console see:
"~$ /usr/local/lib/python2.7/dist-packages/twisted/web/wsgi.py:128: UnicodeWarning: write() argument should be str, not u'[2017-05-22 18:18:27,808] ERROR in app: Exception on /ws/ge [PUT]\nTraceback (most recent call last):\n File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app\n response = self.full_dispatch_request()\n File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request\n rv = self.handle_user_exception(e)\n File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception\n reraise(exc_type, exc_value, tb)\n File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request\n rv = self.dispatch_request()\n File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request\n return self.view_functionsrule.endpoint\n File "/home/user/faraday-dev/server/utils/web.py", line 70, in view_func\n return f(*args, **kwargs)\n File "/home/user/faraday-dev/server/api/modules/workspaces.py", line 67, in workspace_create_or_update\n validate_admin_perm()\n File "/home/user/faraday-dev/server/utils/web.py", line 109, in validate_admin_perm\n res = __check_response(requests.get(__get_server_sessions_uri(), cookies=request.cookies)) or \\n File "/home/user/faraday-dev/server/utils/web.py", line 103, in __check_response\n response = response.json()\n File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 885, in json\n return complexjson.loads(self.text, **kwargs)\n File "/usr/lib/python2.7/json/init.py", line 339, in loads\n return _default_decoder.decode(s)\n File "/usr/lib/python2.7/json/decoder.py", line 364, in decode\n obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode\n raise ValueError("No JSON object could be decoded")\nValueError: No JSON object could be decoded\n' (unicode)
data, type(data).name), category=UnicodeWarning)
[2017-05-22 18:18:27,808] ERROR in app: Exception on /ws/ge [PUT]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functionsrule.endpoint
File "/home/user/faraday-dev/server/utils/web.py", line 70, in view_func
return f(*args, **kwargs)
File "/home/user/faraday-dev/server/api/modules/workspaces.py", line 67, in workspace_create_or_update
validate_admin_perm()
File "/home/user/faraday-dev/server/utils/web.py", line 109, in validate_admin_perm
res = __check_response(requests.get(__get_server_sessions_uri(), cookies=request.cookies)) or 
File "/home/user/faraday-dev/server/utils/web.py", line 103, in __check_response
response = response.json()
File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 885, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib/python2.7/json/init.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2017-05-22 18:18:27,808 - server.app - ERROR - Exception on /ws/ge [PUT]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functionsrule.endpoint
File "/home/user/faraday-dev/server/utils/web.py", line 70, in view_func
return f(*args, **kwargs)
File "/home/user/faraday-dev/server/api/modules/workspaces.py", line 67, in workspace_create_or_update
validate_admin_perm()
File "/home/user/faraday-dev/server/utils/web.py", line 109, in validate_admin_perm
res = __check_response(requests.get(__get_server_sessions_uri(), cookies=request.cookies)) or 
File "/home/user/faraday-dev/server/utils/web.py", line 103, in __check_response
response = response.json()
File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 885, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib/python2.7/json/init.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded"

Any issue with twisted?

Ubuntu 17.04

Linux Server 4.11.0-041100-generic #201705041534 SMP Thu May 4 19:36:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by horusint** [comment]
We have this error creating a workspace 
"Oops!
{"data":"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n","status":500,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"url":"http://ipfaraday:5985/_api/ws/ge","data":{"_id":"ge","customer":"","sdate":1495487909831,"name":"ge","type":"Workspace","children":[],"duration":{"start":"","end":""},"scope":"","description":""},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"INTERNAL SERVER ERROR"}"

On Console see:
"~$ /usr/local/lib/python2.7/dist-packages/twisted/web/wsgi.py:128: UnicodeWarning: write() argument should be str, not u'[2017-05-22 18:18:27,808] ERROR in app: Exception on /ws/ge [PUT]\nTraceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/home/user/faraday-dev/server/utils/web.py", line 70, in view_func\n    return f(*args, **kwargs)\n  File "/home/user/faraday-dev/server/api/modules/workspaces.py", line 67, in workspace_create_or_update\n    validate_admin_perm()\n  File "/home/user/faraday-dev/server/utils/web.py", line 109, in validate_admin_perm\n    res = __check_response(requests.get(__get_server_sessions_uri(), cookies=request.cookies)) or \\\n  File "/home/user/faraday-dev/server/utils/web.py", line 103, in __check_response\n    response = response.json()\n  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 885, in json\n    return complexjson.loads(self.text, **kwargs)\n  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads\n    return _default_decoder.decode(s)\n  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode\n    raise ValueError("No JSON object could be decoded")\nValueError: No JSON object could be decoded\n' (unicode)
  data, type(data).__name__), category=UnicodeWarning)
[2017-05-22 18:18:27,808] ERROR in app: Exception on /ws/ge [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/faraday-dev/server/utils/web.py", line 70, in view_func
    return f(*args, **kwargs)
  File "/home/user/faraday-dev/server/api/modules/workspaces.py", line 67, in workspace_create_or_update
    validate_admin_perm()
  File "/home/user/faraday-dev/server/utils/web.py", line 109, in validate_admin_perm
    res = __check_response(requests.get(__get_server_sessions_uri(), cookies=request.cookies)) or \
  File "/home/user/faraday-dev/server/utils/web.py", line 103, in __check_response
    response = response.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 885, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2017-05-22 18:18:27,808 - server.app - ERROR - Exception on /ws/ge [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/faraday-dev/server/utils/web.py", line 70, in view_func
    return f(*args, **kwargs)
  File "/home/user/faraday-dev/server/api/modules/workspaces.py", line 67, in workspace_create_or_update
    validate_admin_perm()
  File "/home/user/faraday-dev/server/utils/web.py", line 109, in validate_admin_perm
    res = __check_response(requests.get(__get_server_sessions_uri(), cookies=request.cookies)) or \
  File "/home/user/faraday-dev/server/utils/web.py", line 103, in __check_response
    response = response.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 885, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded"

Any issue with twisted?

Ubuntu 17.04

Linux Server 4.11.0-041100-generic #201705041534 SMP Thu May 4 19:36:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by WinnaZ** [comment]
hi horusint,
could you give us more information about how were you trying to create this workspace?
What version of Faraday are you working on?

**Comment by horusint** [comment]
version in RELEASE.md

New features in the latest update
=====================================

March 17, 2017:

____
Create Worskpace from http://ip:5985/_ui/#/workspaces , New . Put only name, "ge" or "asd"

**Comment by horusint** [comment]
After:
apt-get purge couchdb
apt-get remove couchdb
apt-get install couchdb

rm -rf ~.faraday

Rerun.

now its working as expected.


Regards.

**Comment by alvahdati** [comment]
@horusint 
hi. i have the same issue, did the solution you gave but problem still remains. exactly the same error message displayed on web ui.

**Comment by llazzaro** [comment]
hi @horusint,

can you send us the output of pip freeze?

Thanks

**Comment by alvahdati** [comment]
> hi @horusint,
> 
> can you send us the output of pip freeze?
> 
> Thanks

As i think you meant to mention me not @horusint, here is the output of `pip freeze` command:
[https://drive.google.com/file/d/1S3PUYIS66_wNE3nDpWobCN9EiPik5gJR/view?usp=sharing](url)
Regards.

**Comment by alvahdati** [comment]
following > https://github.com/infobyte/faraday/issues/339
just solved my problem.
