### ISSUE TITLE
Faraday not working on Kali Linux

### ISSUE THREAD

**Issue by DenverDaveH** [infobyte/faraday#198]
After checking the forum here quickly, I seem to be having an issue:
I start with sudo ./faraday.py and get this:
2017-06-07 16:56:32,071 - faraday.launcher - INFO - Starting Faraday IDE.
2017-06-07 16:56:32,071 - faraday.launcher - INFO - Checking configuration.
2017-06-07 16:56:32,071 - faraday.launcher - INFO - Setting up plugins.
2017-06-07 16:56:32,071 - faraday.launcher - INFO - Removing old plugins folder.
2017-06-07 16:56:32,085 - faraday.launcher - INFO - Setting up ZSH integration.
2017-06-07 16:56:32,086 - faraday.launcher - INFO - Setting up user configuration.
2017-06-07 16:56:32,086 - faraday.launcher - INFO - Using custom user configuration.
2017-06-07 16:56:32,087 - faraday.launcher - INFO - Setting up icons for GTK interface.
2017-06-07 16:56:32,091 - faraday.launcher - INFO - Setting configuration.
2017-06-07 16:56:32,679 - faraday.launcher - INFO - No updates available, enjoy Faraday.
2017-06-07 16:56:32,811 - faraday.launcher - INFO - All done. Opening environment.
2017-06-07 16:56:33,109 - faraday.launcher - INFO - Main application ExceptHook enabled.
2017-06-07 16:56:33,109 - faraday.launcher - INFO - Starting main application.

*              faraday ui is ready              
Make sure you got couchdb up and running.
If couchdb is up, point your browser to: 
[http://127.0.0.1:5985/_ui]
2017-06-07 16:56:33,109 - faraday - INFO - XMLRPC API server configured on ('localhost', 9876)
2017-06-07 16:56:33,115 - faraday - INFO - REST API server configured on ('localhost', 9977)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/dave/faraday/utils/error_report.py", line 83, in exception_handler
    model.guiapi.postCustomEvent(event)
  File "/home/dave/faraday/model/guiapi.py", line 38, in postCustomEvent
    receiver = getMainWindow()
  File "/home/dave/faraday/model/guiapi.py", line 34, in getMainWindow
    return __the_mainapp.getMainWindow()
AttributeError: 'NoneType' object has no attribute 'getMainWindow'

Original exception was:
Traceback (most recent call last):
  File "/home/dave/faraday/gui/gtk/application.py", line 635, in do_startup
    CONF.getLastWorkspace())
  File "/home/dave/faraday/gui/gtk/mainwidgets.py", line 515, in __init__
    self.workspaces = self.serverIO.get_workspaces_names()
  File "/home/dave/faraday/gui/gtk/decorators.py", line 17, in wrapper
    res = func(*args, **kwargs)
  File "/home/dave/faraday/gui/gtk/server.py", line 67, in get_workspaces_names
    return models.get_workspaces_names()
  File "/home/dave/faraday/persistence/server/models.py", line 647, in get_workspaces_names
    return server.get_workspaces_names()['workspaces']
  File "/home/dave/faraday/persistence/server/server.py", line 470, in get_workspaces_names
    return _get("{0}/ws".format(_create_server_api_url()))
  File "/home/dave/faraday/persistence/server/server.py", line 152, in _get
    params=params))
  File "/home/dave/faraday/persistence/server/server.py", line 118, in _unsafe_io_with_server
    answer = server_io_function(server_url, **payload)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/api.py", line 70, in get
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/api.py", line 56, in request
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 487, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5985): Max retries exceeded with url: /_api/ws (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7b3f63dfd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/dave/faraday/utils/error_report.py", line 83, in exception_handler
    model.guiapi.postCustomEvent(event)
  File "/home/dave/faraday/model/guiapi.py", line 38, in postCustomEvent
    receiver = getMainWindow()
  File "/home/dave/faraday/model/guiapi.py", line 34, in getMainWindow
    return __the_mainapp.getMainWindow()
AttributeError: 'NoneType' object has no attribute 'getMainWindow'

Original exception was:
Traceback (most recent call last):
  File "/home/dave/faraday/gui/gtk/application.py", line 718, in do_activate
    self.window = AppWindow(self.sidebar,
AttributeError: 'GuiApp' object has no attribute 'sidebar'
2017-06-07 16:56:33,469 - faraday - INFO - Closing Faraday...

I could not connect to the couchdb url. I tried port 5984 as that was the test from the couchdb install instructions to test if the couchdb server is running: curl localhost:5984.

Here is my Kali version info:
lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling

Where did I go wrong?

**Comment by f-amato** [comment]
Hi @DenverDaveH 
Thanks for trying Faraday :)! 
Keep in mind that you have to run first Faraday Server ./faraday-server.py and then the client ./faraday.py

Couch is running on 5984, and Faraday server will use the port 5985.

Take a look to:
https://github.com/infobyte/faraday/wiki/First-steps
https://github.com/infobyte/faraday/wiki/configuration-server

Let us know if you need more help.
Best

**Comment by DenverDaveH** [comment]
Hello,
Thanks for the help. Sorry I did not RTFM ;) I was able to get the client updated as well as fire up the server. Then access it via browser. 
Now to read more on how to use it for bug bounties not listed here :)

Thanks again!
Dave

**Comment by f-amato** [comment]
Excellent @DenverDaveH !! Happy hunting!
