### ISSUE TITLE
OS Error

### ISSUE THREAD

**Issue by Hankhh** [infobyte/faraday#209]
Hi Guys,

I faced with this error, while I was trying to update Faraday to the v2.6. As far as I remember It was working fine. I checked the troubleshooting page https://github.com/infobyte/faraday/wiki/Troubleshooting
and found the similar OSError but, in my case, Faraday has been installed in a correct directory.

2017-07-28 12:36:38,099 - faraday.launcher - INFO - Starting Faraday IDE.
2017-07-28 12:36:38,099 - faraday.launcher - INFO - Checking configuration.
2017-07-28 12:36:38,099 - faraday.launcher - INFO - Setting up plugins.
2017-07-28 12:36:38,100 - faraday.launcher - INFO - Removing old plugins folder.
Traceback (most recent call last):
  File "./faraday.py", line 553, in <module>
    main()
  File "./faraday.py", line 540, in main
    checkConfiguration(args.gui)
  File "./faraday.py", line 387, in checkConfiguration
    setupPlugins(args.dev_mode)
  File "./faraday.py", line 328, in setupPlugins
    shutil.rmtree(FARADAY_PLUGINS_PATH)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 2] No such file or directory: '/root/.faraday/plugins/__init__.py'

* faraday-server and Couchdb are working fine and without any errors.
Any idea? Is that related to PATH or existence of a specific folder?

**Comment by WinnaZ** [comment]
Hi Hankhh,
mmm this behaviour is estrange,
Go to the ~.faraday/ directory and change the name of the plugins folder for something else.
And then stop the server and start it again.
Are you using the community version?
Hope to hear back from you!

**Comment by WinnaZ** [comment]
Hi there Hankhh,
Are you still having this issue?
Cheers!

**Comment by Hankhh** [comment]
@WinnaZ 
Hi There,

Thank you for following up and sorry for my late reply. I had the issue and I could not resolve it with changing the plugin folder name ( also, I have the Faraday installed on docker and I had many permission issues and etc.) So I ended up with reinstalling and configuring a new instance.

Thanks!

**Comment by WinnaZ** [comment]
Great! Shall we set the issue to fixed then?

**Comment by Hankhh** [comment]
@WinnaZ 
I haven't had this issue since version 2.6.2, so I assume we can set it to fixed (somehow).
Thanks!
