### ISSUE TITLE
Problems with the API

### ISSUE THREAD

**Issue by S-Schettler** [infobyte/faraday#210]
Hi,
I have some problems with the REST API running Faraday-Server and -Client on the same VM.
Couchdb is running on Admin Party and its possible to connect the server (standardport) and the client (rest api changed to port 9999).

When I'm trying to 
`curl -X GET http://127.0.0.1:5985/_api/ws`
It's work just fine with the Output:
`{"workspaces":["faraday","testdatabase","xxxx"]}`

But the PUT /ws/workspace_name like: 
`$ curl -X PUT http://127.0.0.1:5985/_api/ws/test `
Produce the following error:
`{"error":"invalid json"}`

and the Client RESTfulAPI doesn't work  too. I tried some different things like:

`$ curl http://127.0.0.1:9999/model/host -XPUT -d '{"name":"123", "os":"windows"}'`
or
`$ curl http://127.0.0.1:9999/model/webvulns -XGET`
so the output is:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

And if I try:
`$ curl -X PUT -H "Content-Type: application/json" -d '{"name":"123"}' "http://127.0.0.1:9999/model/host"
`I get something like:
```
{
  "code": 200, 
  "id": "40bd001563085fc35165329ea1ff5c5ecbdbbeef"
}
```
but nothing happens either.

I'm fairly new at RESTful APIs, so I don't know if i missed something, or it just doesn't work. 
I checked the config files, user.xml, server.ini etc. more than once and reinstalled the whole system from scratch, so I'm stuck atm.
Can someone please give me some tipps, or a working sample of a PUT request for the API? :)

Thank you.
Sebastian

**Comment by llazzaro** [comment]
When the api return error code 500, could you check if the faraday-server or faraday gtk client returns any error?

When you do this request:
`curl -X PUT -H "Content-Type: application/json" -d '{"name":"123"}' 

Check which workspace is selected on the gtk ui, the host will be created on the selected workspace.
`

**Comment by S-Schettler** [comment]
When i test:
`$ curl -X PUT -H "Content-Type: application/json" -d '{"name":"123"}' "http://127.0.0.1:9999/model/host"`

the Console from the Client shows the following output: (I posted the full console Log, just for completeness)

```
2017-08-06 14:39:28,689 - faraday.launcher - INFO - Checking dependencies...
2017-08-06 14:39:28,703 - faraday.launcher - INFO - Dependencies met

  _____                           .___
_/ ____\_____  ____________     __| _/_____   ___.__.
\   __\ \__  \ \_  __ \__  \   / __ | \__  \ <   |  |
 |  |    / __ \_|  | \// __ \_/ /_/ |  / __ \_\___  |
 |__|   (____  /|__|  (____  /\____ | (____  // ____|
             \/            \/      \/      \/ \/
    
[*[       Open Source Penetration Test IDE       ]*]
            Where pwnage goes multiplayer

2017-08-06 14:39:28,703 - faraday.launcher - INFO - Starting Faraday IDE.
2017-08-06 14:39:28,703 - faraday.launcher - INFO - Checking configuration.
2017-08-06 14:39:28,703 - faraday.launcher - INFO - Setting up plugins.
2017-08-06 14:39:28,703 - faraday.launcher - INFO - Removing old plugins folder.
2017-08-06 14:39:29,581 - faraday.launcher - INFO - Setting up ZSH integration.
2017-08-06 14:39:29,587 - faraday.launcher - INFO - Setting up user configuration.
2017-08-06 14:39:29,591 - faraday.launcher - INFO - Using custom user configuration.
2017-08-06 14:39:29,598 - faraday.launcher - INFO - Setting up icons for GTK interface.
2017-08-06 14:39:29,923 - faraday.launcher - INFO - Setting configuration.
2017-08-06 14:39:32,155 - faraday.launcher - INFO - No updates available, enjoy Faraday.
2017-08-06 14:39:34,654 - faraday.launcher - INFO - All done. Opening environment.
2017-08-06 14:39:34,776 - faraday.PluginManager - WARNING - Please install psycopg2 to use plugin: MetasploitOn
2017-08-06 14:39:35,051 - faraday.PluginManager - WARNING - No module named lxml
2017-08-06 14:39:35,249 - faraday.PluginManager - WARNING - No module named bs4
2017-08-06 14:39:35,403 - faraday.PluginManager - WARNING - No module named lxml
2017-08-06 14:39:37,697 - faraday.launcher - INFO - Main application ExceptHook enabled.
2017-08-06 14:39:37,699 - faraday.launcher - INFO - Starting main application.

*              faraday ui is ready              
Make sure you got couchdb up and running.
If couchdb is up, point your browser to: 
[http://127.0.0.1:5985/_ui]

2017-08-06 14:39:37,703 - faraday - INFO - XMLRPC API server configured on ('127.0.0.1', 9876)
2017-08-06 14:39:37,881 - faraday - INFO - REST API server configured on ('127.0.0.1', 9999)
[2017-08-06 14:42:50,626] ERROR in app: Exception on /model/host [PUT]
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/.local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/faraday-dev/apis/rest/api.py", line 246, in createHost
    ['name', 'os'])
  File "/home/user/faraday-dev/apis/rest/api.py", line 230, in _create
    if not 'name' in data:
TypeError: argument of type 'NoneType' is not iterable
2017-08-06 14:42:50,674 - tornado.access - ERROR - 500 PUT /model/host (127.0.0.1) 58.64ms


```

**Comment by WinnaZ** [comment]
hi there S-Schettler,
Are you still having this issue?

**Comment by WinnaZ** [comment]
i'm closing this ticket for now,
If you are still having problems you can re-open it or create a new one.
Cheers!
