### ISSUE TITLE
error on initial startup - address already in use

### ISSUE THREAD

**Issue by steorra1** [infobyte/faraday#211]
2017-08-09 18:27:22,387 - faraday.Updater - INFO - Upgrading DBs to latest version
2017-08-09 18:27:22,388 - faraday.Updater - INFO - We are about to upload CouchdbViews in Server [http://127.0.0.1:5984]
2017-08-09 18:27:22,400 - faraday.Updater - INFO - Dbs to upgrade: example, workspace
2017-08-09 18:27:22,400 - faraday.Updater - INFO - Preparing updates on Couchdbs
2017-08-09 18:27:22,678 - faraday.launcher - INFO - Update process finished with no errors
2017-08-09 18:27:22,679 - faraday.launcher - INFO - Faraday will start now.
2017-08-09 18:27:23,018 - faraday.launcher - INFO - No updates available, enjoy Faraday.
2017-08-09 18:27:23,233 - faraday.launcher - INFO - All done. Opening environment.
2017-08-09 18:27:23,251 - faraday.PluginManager - WARNING - No module named bs4
2017-08-09 18:27:23,273 - faraday.PluginManager - WARNING - No module named lxml
2017-08-09 18:27:23,354 - faraday.PluginManager - WARNING - No module named lxml
2017-08-09 18:27:23,388 - faraday.launcher - INFO - Main application ExceptHook enabled.
2017-08-09 18:27:23,388 - faraday.launcher - INFO - Starting main application.

*              faraday ui is ready              
Make sure you got couchdb up and running.
If couchdb is up, point your browser to: 
[http://127.0.0.1:5984/_ui]

2017-08-09 18:27:23,389 - faraday - INFO - XMLRPC API server configured on ('localhost', 9876)
There was an error while starting Faraday
--------------------------------------------------
Traceback (most recent call last):
  File "/root/faraday/model/application.py", line 145, in start
    CONF.getApiRestfulConInfoPort()
  File "/root/faraday/apis/rest/api.py", line 68, in startAPIs
    raise exception
error: [Errno 99] Cannot assign requested address
--------------------------------------------------
2017-08-09 18:27:23,405 - faraday - INFO - Closing Faraday...

**Comment by WinnaZ** [comment]
Hi there steorra1,
Run this command:
```netstat -tulp```
and then run the client again.
If it doesn't work try turning off and on again.

**Comment by WinnaZ** [comment]
Hi there steorra1,
Are you still having this issue?
What was the command that caused this Error message?
On what OS are you running Faraday?
Cheers!

**Comment by HTlocal** [comment]
Hello, I know it's closed but I had this problem as well and here's the solution:
run the client like this
./faraday.pyc -n 127.0.0.1

The address error is caused by trying to bind to 'localhost' which is failing and a common problem since 2 years.
