### ISSUE TITLE
installation problem in mac os hight sierra

### ISSUE THREAD

**Issue by alim92** [infobyte/faraday#246]
I am unbale to run ./faraday.py :
./faraday.py --version
Traceback (most recent call last):
  File "./faraday.py", line 26, in <module>
    from persistence.server import server
  File "/Users/almost/faraday-dev/persistence/server/server.py", line 27, in <module>
    import requests
ImportError: No module named requests

Mac OS - High Sierra 10.13.3

tried these:
pip install requests
easy_install requests

anyone has an idea on how to overcome this?

Thanks

**Comment by llazzaro** [comment]
faraday.py uses python2.7. Make sure that you are using pip2 or better pip2.7 command to install requirements.

Check [here OSX install notes](https://github.com/infobyte/faraday/wiki/Installation-OSX), there is a note about brew versus shipped python interpreter.

**Comment by alim92** [comment]
I just uninstalled all version I had for python and I overcame this step.
now I am having another problem:

  _____                           .___
_/ ____\_____  ____________     __| _/_____   ___.__.
\   __\ \__  \ \_  __ \__  \   / __ | \__  \ <   |  |
 |  |    / __ \_|  | \// __ \_/ /_/ |  / __ \_\___  |
 |__|   (____  /|__|  (____  /\____ | (____  // ____|
             \/            \/      \/      \/ \/
    
[*[       Open Source Penetration Test IDE       ]*]
            Where pwnage goes multiplayer

2018-02-19 11:04:57,942 - faraday.launcher - INFO - Starting Faraday IDE.
2018-02-19 11:04:57,942 - faraday.launcher - INFO - Checking configuration.
2018-02-19 11:04:57,942 - faraday.launcher - INFO - Setting up plugins.
2018-02-19 11:04:57,943 - faraday.launcher - INFO - Removing old plugins folder.
2018-02-19 11:04:58,020 - faraday.launcher - INFO - Setting up ZSH integration.
2018-02-19 11:04:58,021 - faraday.launcher - INFO - Setting up user configuration.
2018-02-19 11:04:58,021 - faraday.launcher - INFO - Using custom user configuration.
2018-02-19 11:04:58,021 - faraday.launcher - INFO - Setting up icons for GTK interface.
2018-02-19 11:04:58,041 - faraday.launcher - INFO - Setting configuration.
2018-02-19 11:04:58,726 - faraday.launcher - INFO - No updates available, enjoy Faraday.
2018-02-19 11:04:58,839 - faraday.launcher - INFO - All done. Opening environment.
2018-02-19 11:04:58,847 - faraday.PluginManager - WARNING - No module named lxml
2018-02-19 11:04:58,866 - faraday.PluginManager - WARNING - No module named lxml
2018-02-19 11:04:58,917 - faraday.PluginManager - WARNING - No module named bs4
2018-02-19 11:04:58,961 - faraday.launcher - INFO - Main application ExceptHook enabled.
2018-02-19 11:04:58,961 - faraday.launcher - INFO - Starting main application.

*              faraday ui is ready              
Make sure you got couchdb up and running.
If couchdb is up, point your browser to: 
[http://127.0.0.1:5985/_ui]

2018-02-19 11:04:58,962 - faraday - INFO - XMLRPC API server configured on ('localhost', 9876)
2018-02-19 11:04:58,981 - faraday - INFO - REST API server configured on ('localhost', 9977)
2018-02-19 11:04:58,986 - faraday.GuiApp - ERROR - Your last workspace untitled is not accessible, check configuration.
2018-02-19 11:04:58,986 - faraday.GuiApp - ERROR - You may try and go to ~/.faraday/config/user.xml to set a valid couch_uri and last_workspace
2018-02-19 11:04:58,986 - faraday.GuiApp - ERROR - Couldn't get a valid response from the server when requesting to URL http://127.0.0.1:5985/_api/ws and function <function get at 0x10bb0d0c8>.
2018-02-19 11:04:58,986 - faraday - INFO - Closing Faraday...

**Comment by WinnaZ** [comment]
Hi there,
Do you have the server up and running?
For the client (faraday.py) to work, you first need to be running the server (faraday-server.py).

**Comment by alim92** [comment]
didn't succeed by running it on mac so I ran it on linux instead
