### ISSUE TITLE
JIRA integration fails with SSL error (Ubuntu)

### ISSUE THREAD

**Issue by HTlocal** [infobyte/faraday#262]
## Issue Type
 - Bug Report

## Faraday version
Faraday vc-2.7.2

## Component Name

JIRA integration

## Steps to reproduce

- select desired vulnerability
- enter credentials and project
- jira host: 
  jira.companyname.com
- jira port:
  443

## Expected results

The vulnerabilities are forwarded to JIRA

### Debugging tracebacks (current results)
`2018-07-17 15:43:31,801 - flask.app - ERROR - Exception on /jira/rest/api/2/issue [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./server/modules/jira.py", line 26, in jira_new_ticket
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='jira.xxxxxxxxxxxxxx.com', port=443): Max retries exceeded with url: /rest/api/2/issue (Caused by SSLError
(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))`

Please attach the result of:

pip freeze > requirements_freeze.txt
[requirements_freeze.txt](https://github.com/infobyte/faraday/files/2201990/requirements_freeze.txt)

## Environment information
`# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
`
`# uname -a 
Linux t42-itsec-06 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

`# uname -a 
Linux t42-itsec-06 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

`# dpkg -l | grep -i tls
ii  libcurl3-gnutls:amd64               7.47.0-1ubuntu2.8                          amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libgnutls-openssl27:amd64           3.4.10-4ubuntu1.4                          amd64        GNU TLS library - OpenSSL wrapper
ii  libgnutls30:amd64                   3.4.10-4ubuntu1.4                          amd64        GNU TLS library - main runtime library`

### Configuration files

not needed for JIRA

### OS
see Environment

**Comment by WinnaZ** [comment]
Hi there!
We will be trying to reproduce your issue!
If you have a professional or corporate license you should open a ticket on our zoho desk! You will have a better support experience there. 
I will let you know when i have a solution for you.

**Comment by HTlocal** [comment]
Yea, you're right. I guess this feature only affects professional / corporate.

**Comment by WinnaZ** [comment]
Issue Migrated to Zoho. #180.
