### ISSUE TITLE
TypeError: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by benharold** [infobyte/faraday#274]
## Issue Type
 - Bug Report

## Faraday version

3.0.1

## Component Name

    faraday-server.py main()

## Steps to reproduce

Using `Linux web-1 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux` and `Python 2.7.12`:

Follow all instructions at https://github.com/infobyte/faraday/wiki/Installation-Community up to:

    python2 faraday-server.py --start

## Expected results

Faraday server should spawn in a background thread.

### Debugging tracebacks (current results)

```
2018-09-11 14:59:23,724 - faraday-server.__main__ - INFO {MainThread} [faraday-server.py:42 - setup_environment() ]  Checking dependencies...
2018-09-11 14:59:23,726 - faraday-server.__main__ - INFO {MainThread} [faraday-server.py:59 - setup_environment() ]  Dependencies met
2018-09-11 14:59:23,726 - faraday-server.__main__ - INFO {MainThread} [faraday-server.py:182 - main() ]  Faraday Server is running as a daemon
Traceback (most recent call last):
  File "faraday-server.py", line 189, in <module>
    main()
  File "faraday-server.py", line 183, in main
    subprocess.Popen(params, stdout=devnull, stderr=devnull)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
```

### OS

Provide information on your operating system. Example:

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"

**Comment by elmoke** [comment]
Experiencing same problem:
`# python2 faraday-server.py` works fine
`# python2 faraday-server.py --start` fails
`# python2 faraday-server.py --start --port 5985` works fine


### Config
```bash
# cat ~/.faraday/config/sever.ini
[faraday_server]
port = 5985
...
```
### OS
```bash
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

**Comment by WinnaZ** [comment]
Hi there,
We've been looking at this bug and we believe we fixed it.
The change will come out on the next version of faraday.
We'll keep you posted.

**Comment by WinnaZ** [comment]
Hi, 
this fix is already out on the last version,
Cheers!
