### ISSUE TITLE
Credentials can not be checked

### ISSUE THREAD

**Issue by logdot** [infobyte/faraday#278]
## Issue Type
 - Bug Report

## Faraday version
Faraday v3.0.1

## Info
I setup faraday to run as a server and everything works fine, except the login screen where one tries to put in the generated credentials and it doesn't accept it even after generating them again and changing them via manage.py and the sql shell.
When running the status check all returns good except faraday GTK and "Credentials can not be checked. Either the Faraday Server not running or database not working". This persists even after dropping the database and generating it again. To get the status check running I needed to change a couple lines of code to get it working, but these shouldn't be related

### Status check output
```
Checking if postgreSQL is running...
[+] PostgreSQL is running
[+] PostgreSQL lock not detected.

Checking if Faraday is running...
[+] Faraday Server is running. PID:0         
[-] Faraday GTK is not running

Checking Faraday dependencies...
[+] Server dependencies met
[+] Client dependencies met

Checking Faraday config...
[-] Credentials can not be checked. Either Faraday Server not running or database not working
[+] /.faraday/storage -> Permission accepted
[+] Port 5985 in 0.0.0.0 is open
```
### Code I changed

``` 
diff --git a/server/commands/status_check.py b/server/commands/status_check.py
index 17f69119..6115ec91 100644
--- a/server/commands/status_check.py
+++ b/server/commands/status_check.py
@@ -28,8 +28,8 @@ init()


 def check_server_running():
-    pid = is_server_running()
-    return pid
+    #pid = is_server_running()
+    return 0 
```

### Logs
Faraday server log
```
2018-09-16 19:39:52,964 - faraday-server.__main__ - WARNING {MainThread} [faraday-server.py:94 - check_postgresql() ]  No workspaces found. Remember to execute CouchDB importer
2018-09-16 19:39:53,699 - faraday-server.__main__ - INFO {MainThread} [faraday-server.py:42 - setup_environment() ]  Checking dependencies...
2018-09-16 19:39:53,702 - faraday-server.__main__ - INFO {MainThread} [faraday-server.py:59 - setup_environment() ]  Dependencies met
2018-09-16 19:39:53,705 - faraday-server.server.web - INFO {MainThread} [web.py:82 - __init__() ]  Starting web server at http://0.0.0.0:5985/
2018-09-16 19:39:53,758 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin arachni
2018-09-16 19:39:53,762 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin peepingtom
2018-09-16 19:39:53,768 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin netsparker
2018-09-16 19:39:53,773 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dnsenum
2018-09-16 19:39:53,777 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin sublist3r
2018-09-16 19:39:53,781 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin fruitywifi
2018-09-16 19:39:53,784 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin arp-scan
2018-09-16 19:39:53,800 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin burp
2018-09-16 19:39:53,804 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin webfuzzer
2018-09-16 19:39:53,810 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin impact
2018-09-16 19:39:53,813 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dnsmap
2018-09-16 19:39:53,817 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin netdiscover
2018-09-16 19:39:53,820 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin whois
2018-09-16 19:39:53,825 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin wpscan
2018-09-16 19:39:53,830 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin webinspect
2018-09-16 19:39:53,836 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin metasploit
2018-09-16 19:39:53,841 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin acunetix
2018-09-16 19:39:53,845 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dig
2018-09-16 19:39:53,849 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin metagoofil
2018-09-16 19:39:53,852 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin sshdefaultscan
2018-09-16 19:39:53,863 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin sqlmap
2018-09-16 19:39:53,867 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin pasteanalyzer
2018-09-16 19:39:53,870 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin masscan
2018-09-16 19:39:53,874 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dnswalk
2018-09-16 19:39:53,878 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin goohost
2018-09-16 19:39:53,881 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin reconng
2018-09-16 19:39:53,886 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin wapiti
2018-09-16 19:39:53,890 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin sentinel
2018-09-16 19:39:53,895 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin metasploiton
2018-09-16 19:39:53,899 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin listurl
2018-09-16 19:39:53,903 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin sslcheck
2018-09-16 19:39:53,906 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin hping3
2018-09-16 19:39:53,910 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin ndiff
2018-09-16 19:39:53,913 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin netcat
2018-09-16 19:39:53,916 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin reverseraider
2018-09-16 19:39:53,920 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin fierce
2018-09-16 19:39:53,923 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin beef
2018-09-16 19:39:53,927 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin nexpose
2018-09-16 19:39:53,931 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin theharvester
2018-09-16 19:39:53,933 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin telnet
2018-09-16 19:39:53,936 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin xsssniper
2018-09-16 19:39:53,941 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin nikto
2018-09-16 19:39:53,945 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin w3af
2018-09-16 19:39:53,947 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin propecia
2018-09-16 19:39:53,952 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin openvas
2018-09-16 19:39:53,955 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin amap
2018-09-16 19:39:53,959 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:124 - _loadPlugins() ]  An error ocurred while loading plugin /root/.faraday/plugins/junit/plugin.py.
Traceback (most recent call last):
  File "/root/faraday-dev/plugins/manager.py", line 115, in _loadPlugins
    module_filename)
  File "/root/.faraday/plugins/junit/plugin.py", line 17, in <module>
    from lxml import etree
ImportError: No module named lxml

2018-09-16 19:39:53,967 - faraday-server.PluginManager - WARNING {MainThread} [manager.py:125 - _loadPlugins() ]  No module named lxml
2018-09-16 19:39:53,969 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dirb
2018-09-16 19:39:53,974 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin netsparkercloud
2018-09-16 19:39:53,976 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin wfuzz
2018-09-16 19:39:53,981 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin nexpose-full
2018-09-16 19:39:53,983 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin ping
2018-09-16 19:39:53,996 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin nessus
2018-09-16 19:39:53,999 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin skipfish
2018-09-16 19:39:54,003 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dnsrecon
2018-09-16 19:39:54,007 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin wcscan
2018-09-16 19:39:54,010 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dirsearch
2018-09-16 19:39:54,013 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin hydra
2018-09-16 19:39:54,017 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin sslyze
2018-09-16 19:39:54,020 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin ftp
2018-09-16 19:39:54,024 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin retina
2018-09-16 19:39:54,028 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin x1
2018-09-16 19:39:54,030 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin traceroute
2018-09-16 19:39:54,034 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin maltego
2018-09-16 19:39:54,039 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin zap
2018-09-16 19:39:54,043 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:124 - _loadPlugins() ]  An error ocurred while loading plugin /root/.faraday/plugins/appscan/plugin.py.
Traceback (most recent call last):
  File "/root/faraday-dev/plugins/manager.py", line 115, in _loadPlugins
    module_filename)
  File "/root/.faraday/plugins/appscan/plugin.py", line 12, in <module>
    from lxml import objectify
ImportError: No module named lxml

2018-09-16 19:39:54,053 - faraday-server.PluginManager - WARNING {MainThread} [manager.py:125 - _loadPlugins() ]  No module named lxml
2018-09-16 19:39:54,056 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin medusa
2018-09-16 19:39:54,060 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin ip360
2018-09-16 19:39:54,062 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin brutexss
2018-09-16 19:39:54,068 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin qualysguard
2018-09-16 19:39:54,070 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin nmap
2018-09-16 19:39:54,075 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin lynis
2018-09-16 19:39:54,123 - faraday-server.server.web - INFO {MainThread} [web.py:128 - __build_websockets_resource() ]  Starting websocket server at port 9000 with bind address 0.0.0.0. SSL False
2018-09-16 19:39:54,130 - faraday-server.server.web - INFO {MainThread} [web.py:171 - run() ]  Faraday Server is ready
```

### OS
I'm running Arch on the server and Kali Linux on the client.

Arch specs:
- Kernel: x86_64 Linux 4.18.3-arch1-1-ARCH
- output from uname -a
```
Linux uranium 4.18.3-arch1-1-ARCH #1 SMP PREEMPT Sat Aug 18 09:22:54 UTC 2018 x86_64 GNU/Linux
```

Kali specs
- output from lsb-release
```
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
```
- uname -a
```
Linux kali 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux
```

**Comment by WinnaZ** [comment]
could you send us the output of 
aux ps | grep faraday
given your modifications to the status check we can't really know from the scrip if the server is running.
About the credentials issue, on the version of faraday we are releasing this week we included a new functionality to the manage.py called change_password. Maybe that will finally solve your issue.
Keep us updated.

**Comment by logdot** [comment]
Heres the output 

```
root      1110 24.5  2.7 408836 109868 tty2    Sl+  00:58   0:02 python2.7 ./faraday-server.py
postgres  1116  0.0  0.3 227120 11896 ?        Ss   00:58   0:00 postgres: faraday_postgresql faraday ::1(52302) idle
```
