### ISSUE TITLE
Nessus plugin is moving report to process folder but not processing

### ISSUE THREAD

**Issue by nickkilla** [infobyte/faraday#28]
me@kali     ./nessus report 	05/09/2015 at 10:57PM 	0.26s 

The .nessus export is copied into the ~/.faraday/report/workspace/ directory and I see in the command log (output above) that the plugin is processing the report, yet no data populate.

Nessus Version 6.3.2 

Error messages
me@kali:~/Desktop/scripts/faraday/faraday-dev# ./faraday.py

  _____                           .___
_/ ____\_____  ____________     __| _/_____   ___.__.
\   __\ \__  \ \_  __ \__  \   / __ | \__  \ <   |  |
 |  |    / __ \_|  | \// __ \_/ /_/ |  / __ \_\___  |
 |__|   (____  /|__|  (____  /\____ | (____  // ____|
             \/            \/      \/      \/ \/
    
[*[       Open Source Penetration Test IDE       ]*]
            Where pwnage goes multiplayer

2015-05-09 23:01:00,287 - faraday.launcher - INFO - Starting Faraday IDE.
2015-05-09 23:01:00,287 - faraday.launcher - INFO - Dependencies met.
2015-05-09 23:01:00,287 - faraday.launcher - INFO - Checking configuration.
2015-05-09 23:01:00,287 - faraday.launcher - INFO - Setting up plugins.
2015-05-09 23:01:00,287 - faraday.launcher - INFO - Removing old plugins folder
2015-05-09 23:01:00,343 - faraday.launcher - INFO - Setting up folders.
2015-05-09 23:01:00,344 - faraday.launcher - INFO - Setting up Qt configuration.
2015-05-09 23:01:00,380 - faraday.launcher - INFO - Setting up ZSH integration.
2015-05-09 23:01:00,383 - faraday.launcher - INFO - Setting up  user configuration.
2015-05-09 23:01:00,384 - faraday.launcher - INFO - Using custom user configuration.
2015-05-09 23:01:00,384 - faraday.launcher - INFO - Setting up libraries.
2015-05-09 23:01:00,394 - faraday.launcher - INFO - i386/686 linux detected.
2015-05-09 23:01:00,400 - faraday.launcher - INFO - Setting up icons for QT interface.
2015-05-09 23:01:00,410 - faraday.launcher - INFO - Setting configuration.
2015-05-09 23:01:02,288 - faraday.launcher - ERROR - [Errno bad handshake] 
2015-05-09 23:01:02,289 - faraday.launcher - INFO - No updates available, enjoy Faraday
2015-05-09 23:01:02,494 - faraday.launcher - INFO - All done. Opening environment.
2015-05-09 23:01:03,280 - faraday.launcher - WARNING - Main application ExceptHook enabled.
2015-05-09 23:01:03,280 - faraday.launcher - INFO - Starting main application.

*              faraday ui is ready              
Make sure you got couchdb up and running.
If couchdb is up, point your browser to: 
[http://127.0.0.1:5984/reports/_design/reports/index.html]

console.error: fx_pnh: 
Object
    - message = Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]
    - fileName = undefined
    - lineNumber = 15
    - stack = @undefined:15:NaN|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://jid1-cz1beofm9mmlzg-at-jetpack/fx_pnh/lib/config.js:28:7|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://jid1-cz1beofm9mmlzg-at-jetpack/fx_pnh/lib/main.js:10:1|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|run@resource://gre/modules/commonjs/sdk/addon/runner.js:149:9|startup/<@resource://gre/modules/commonjs/sdk/addon/runner.js:113:7|Handler.prototype.process@resource://gre/modules/Promise-backend.js:863:11|this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:742:7|
    - toString = function () /* use strict */ toString
console.error: fx_pnh: 
Object
    - message = Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]
    - fileName = undefined
    - lineNumber = 15
    - stack = @undefined:15:NaN|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://jid1-cz1beofm9mmlzg-at-jetpack/fx_pnh/lib/config.js:28:7|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|@resource://jid1-cz1beofm9mmlzg-at-jetpack/fx_pnh/lib/main.js:10:1|CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:9|run@resource://gre/modules/commonjs/sdk/addon/runner.js:149:9|startup/<@resource://gre/modules/commonjs/sdk/addon/runner.js:113:7|Handler.prototype.process@resource://gre/modules/Promise-backend.js:863:11|this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:742:7|
    - toString = function () /* use strict */ toString

**Comment by f-amato** [comment]
Hi @nickkilla thanks for tried faraday!
Could you please try on debug mode using ./faraday.py -d 
Is it possible to share us the report? Maybe there is something new that it's breaking the parser.
Best

**Comment by nickkilla** [comment]
2015-05-10 20:13:05,584 - faraday.CouchDbConnector - DEBUG - Watching for changes
2015-05-10 20:13:05,598 - faraday.MainApplication - DEBUG - Starting Reports Manager Thread
2015-05-10 20:13:05,599 - faraday.model.api - DEBUG - Faraday ready...
2015-05-10 20:13:05,599 - faraday.model.api - DEBUG - clearTree called
2015-05-10 20:13:06,118 - faraday.model.api - DEBUG - createShellEnvironment called             - About to create new shell env with name Shell-1
2015-05-10 20:13:06,603 - faraday.model.api - DEBUG - processOutputHandler (IGNORED by flags): 
'export PS1="[\\u@\\h:\\w]>\\$ "\r\n[root@kali:~/Desktop/scripts/faraday/faraday-dev]>$ clear\r\n'
2015-05-10 20:13:06,610 - faraday.model.api - DEBUG - processOutputHandler (IGNORED by flags): 
'\x1b[H\x1b[2J[root@kali:~/Desktop/scripts/faraday/faraday-dev]>$ '
2015-05-10 20:14:36,240 - faraday.model.api - DEBUG - Report file is /root/.faraday/report/labs2/7xa6po.nessus
2015-05-10 20:14:36,256 - faraday.model.api - DEBUG - nessus
2015-05-10 20:14:36,258 - faraday.model.api - DEBUG - The file is /root/.faraday/report/labs2/7xa6po.nessus, nessus
2015-05-10 20:14:36,260 - faraday.model.api - DEBUG - Executing ./nessus report
2015-05-10 20:14:36,276 - faraday.CouchDbConnector - DEBUG - Saving document in couch db <Database labs2>
2015-05-10 20:14:36,393 - faraday.CouchDbConnector - DEBUG - Saving document in couch db <Database labs2>
2015-05-10 20:14:36,412 - faraday.model.api - DEBUG - PluginController (191560524) - Created plugin_process (194885420) for plugin instance (191524140)
2015-05-10 20:14:36,430 - faraday.model.api - DEBUG - ----------------------------------------
2015-05-10 20:14:36,431 - faraday.model.api - DEBUG - proc_name = PluginProcess-1
2015-05-10 20:14:36,431 - faraday.model.api - DEBUG - Starting run method on PluginProcess
2015-05-10 20:14:36,432 - faraday.model.api - DEBUG - parent process: 30008
2015-05-10 20:14:36,432 - faraday.model.api - DEBUG - process id: 30532
2015-05-10 20:14:36,432 - faraday.model.api - DEBUG - ----------------------------------------
2015-05-10 20:14:36,439 - faraday.model.api - DEBUG - PluginProcess-1: New Output
2015-05-10 20:14:37,131 - faraday.model.api - DEBUG - Plugin raised an exception:
2015-05-10 20:14:37,132 - faraday.model.api - DEBUG - Traceback (most recent call last):
  File "/root/Desktop/scripts/faraday/faraday-dev/plugins/core.py", line 799, in run
    self.plugin.parseOutputString(output)
  File "/root/.faraday/plugins/nessus/plugin.py", line 163, in parseOutputString
    resolution=resolution,ref=ref)
  File "/root/Desktop/scripts/faraday/faraday-dev/plugins/core.py", line 686, in createAndAddVulnWebToService
    category=category, parent_id=service_id)
  File "/root/Desktop/scripts/faraday/faraday-dev/model/common.py", line 546, in generateID
    return '.'.join([parent_id, tmpObj.getID()])
  File "/root/Desktop/scripts/faraday/faraday-dev/model/common.py", line 248, in getID
    self.updateID()
  File "/root/Desktop/scripts/faraday/faraday-dev/model/common.py", line 1012, in updateID
    self._id = get_hash([self.name, self.website, self.path, self.desc ])
  File "/root/Desktop/scripts/faraday/faraday-dev/utils/common.py", line 17, in get_hash
    return hashlib.sha1("._.".join(parts)).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 515: ordinal not in range(128)

2015-05-10 20:14:37,134 - faraday.model.api - DEBUG - PluginProcess-1: Exiting


Where should iI send the nessus file?

**Comment by f-amato** [comment]
please send to devel [at] infobytesec [dot] com
Thanks!

**Comment by nickkilla** [comment]
Nessus file emailed.

**Comment by rgerman** [comment]
Hi @nickkilla!
We had problems with unicode characters inside the nessus report. 
Could you try this patch? Move to the faraday root, save the diff in a file like "nessus.patch" and then run: patch -p1 < nessus.patch

``` patch
diff --git a/plugins/repo/nessus/plugin.py b/plugins/repo/nessus/plugin.py
index 722f937..81d1e63 100644
--- a/plugins/repo/nessus/plugin.py
+++ b/plugins/repo/nessus/plugin.py
@@ -129,10 +129,10 @@ class NessusPlugin(core.PluginBase):
             for v in t.vulns:
                                                                                                    
                 desc=""
-                desc+=v.get('description') if v.get('description') else ""
+                desc+=v.get('description').encode("ascii", errors="backslashreplace") if v.get('description') else ""
                 resolution = ""
-                resolution = v.get('solution') if v.get('solution') else ""
-                desc+="\nOutput: "+v.get('plugin_output') if v.get('plugin_output') else ""
+                resolution = v.get('solution').encode("ascii", errors="backslashreplace") if v.get('solution') else ""
+                desc+="\nOutput: "+v.get('plugin_output').encode("ascii", errors="backslashreplace") if v.get('plugin_output') else ""
                 ref=[]
                 if v.get('cve'):
                     ref.append(", ".join(v.get('cve')))


```
Thanks!

**Comment by nickkilla** [comment]
Patch worked. Nessus file was imported.
