### ISSUE TITLE
Faraday client start error

### ISSUE THREAD

**Issue by alexoslabs2** [infobyte/faraday#286]
## Issue Type
 - Bug Re port

## Faraday version

Faraday v3.1.1

## Steps to reproduce

Execute ./faraday.py

### Debugging tracebacks (current results)

2018-10-09 17:29:08,066 - faraday.launcher - INFO [faraday.py:429 -         checkUpdates() ]  No updates available, enjoy Faraday.
Traceback (most recent call last):
  File "./faraday.py", line 561, in <module>
    main()
  File "./faraday.py", line 557, in main
    startFaraday()
  File "./faraday.py", line 246, in startFaraday
    from model.application import MainApplication
  File "/home/alexos/Research/faraday/model/application.py", line 27, in <module>
    import apis.rest.api as restapi
  File "/home/alexos/Research/faraday/apis/rest/api.py", line 15, in <module>
    from tornado.wsgi import WSGIContainer
  File "/usr/local/lib/python2.7/dist-packages/tornado/wsgi.py", line 37, in <module>
    from tornado.concurrent import Future
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 47, in <module>
    import asyncio
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
Please attach the result of:

pip freeze > requirements_freeze.txt
[requirements_freeze.txt](https://github.com/infobyte/faraday/files/2462100/requirements_freeze.txt)

### Screenshots

![image](https://user-images.githubusercontent.com/39374140/46696995-fa2ef500-cbe9-11e8-95bb-96db20e0d8e5.png)

## Environment information

$ cat /etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by llazzaro** [comment]
You are using asyncio with python 2.7 and that is not compatible (https://github.com/python/asyncio/issues/386).

You can try to uninstall asyncio with "pip uninstall asyncio" or use a virtualenv to isolate faraday environment.

**Comment by WinnaZ** [comment]
did you try pip install asyncio ?

**Comment by alexoslabs2** [comment]
Solved! I unistalled the asyncio. 

Thanks @llazzaro

**Comment by alexoslabs2** [comment]
Solved! I unistalled the asyncio.

Thanks @llazzaro
