### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by leebaird** [infobyte/faraday#29]
root@kali:~/Desktop/stuff/faraday# git pull
Already up-to-date.
root@kali:~/Desktop/stuff/faraday# ./faraday.py 

  _____                           .___
_/ ____\_____  ____________     __| _/_____   ___.__.
\   __\ \__  \ \_  __ \__  \   / __ | \__  \ <   |  |
 |  |    / __ \_|  | \// __ \_/ /_/ |  / __ \_\___  |
 |__|   (____  /|__|  (____  /\____ | (____  // ____|
             \/            \/      \/      \/ \/
    
[*[       Open Source Penetration Test IDE       ]*]
            Where pwnage goes multiplayer

2015-05-10 01:26:23,227 - faraday.launcher - INFO - Starting Faraday IDE.
2015-05-10 01:26:23,227 - faraday.launcher - INFO - Dependencies met.
2015-05-10 01:26:23,227 - faraday.launcher - INFO - Checking configuration.
2015-05-10 01:26:23,227 - faraday.launcher - INFO - Setting up plugins.
2015-05-10 01:26:23,227 - faraday.launcher - INFO - Removing old plugins folder
2015-05-10 01:26:23,359 - faraday.launcher - INFO - Setting up folders.
2015-05-10 01:26:23,359 - faraday.launcher - INFO - Setting up Qt configuration.
2015-05-10 01:26:23,433 - faraday.launcher - INFO - Setting up ZSH integration.
2015-05-10 01:26:23,436 - faraday.launcher - INFO - Setting up  user configuration.
2015-05-10 01:26:23,437 - faraday.launcher - INFO - Using custom user configuration.
2015-05-10 01:26:23,437 - faraday.launcher - INFO - Setting up libraries.
2015-05-10 01:26:23,441 - faraday.launcher - INFO - x86_64 linux detected.
ln: failed to create symbolic link `/root/Desktop/stuff/faraday/shell/core/_helpers.so': File exists
2015-05-10 01:26:23,449 - faraday.launcher - INFO - Setting up icons for QT interface.
2015-05-10 01:26:23,497 - faraday.launcher - INFO - Setting configuration.
2015-05-10 01:26:23,675 - faraday.launcher - ERROR - [Errno bad handshake] 
2015-05-10 01:26:23,676 - faraday.launcher - INFO - No updates available, enjoy Faraday
2015-05-10 01:26:23,916 - faraday.launcher - INFO - All done. Opening environment.
Traceback (most recent call last):
  File "./faraday.py", line 582, in <module>
    main()
  File "./faraday.py", line 576, in main
    startFaraday()
  File "./faraday.py", line 282, in startFaraday
    main_app = MainApplication(args)
  File "/root/Desktop/stuff/faraday/model/application.py", line 73, in __init__
    args.gui)
  File "/root/Desktop/stuff/faraday/gui/gui_app.py", line 16, in create
    from gui.qt3.application import GuiApp
  File "/root/Desktop/stuff/faraday/gui/qt3/application.py", line 21, in <module>
    from shell.controller.env import ShellEnvironment
  File "/root/Desktop/stuff/faraday/shell/controller/env.py", line 21, in <module>
    from shell.controller.qt3.session import Session
  File "/root/Desktop/stuff/faraday/shell/controller/qt3/session.py", line 32, in <module>
    import emulation
  File "/root/Desktop/stuff/faraday/shell/controller/qt3/emulation.py", line 69, in <module>
    from shell.core.screen import Screen
  File "/root/Desktop/stuff/faraday/shell/core/screen.py", line 44, in <module>
    from helpers import wcWidth
  File "/root/Desktop/stuff/faraday/shell/core/helpers.py", line 13, in <module>
    from _helpers import *
ImportError: No module named _helpers

**Comment by f-amato** [comment]
Hi @leebaird ! thanks for tried Faraday!
Please delete the file /root/Desktop/stuff/faraday/shell/core/helpers.so and run ./faraday.py again
Let me know if this fix the bug.
Best

**Comment by leebaird** [comment]
Same problem exists. I even deleted the old folder and pulled down a new one.

**Comment by f-amato** [comment]
Hi @leebaird Could you please send run ./faraday.py -d and give use a output?
Best
