### ISSUE TITLE
Deleted ~/.faraday and now Faraday does not start

### ISSUE THREAD

**Issue by daniejstriata** [infobyte/faraday#295]
I deleted the Kali install's .faraday folder after uninstall it using --purge. I did a clean install for Faraday but when running the server I get the following:

```
2018-10-15 15:24:40,376 - faraday-server.__main__ - ERROR {MainThread} [faraday-server.py:102 - check_postgresql() ]  

Could not connect to PostgreSQL.
Please check: 
  * if database is running 
  * configuration settings are correct. 

For first time installations execute: 

  python manage.py initdb
```

What is the preferred method to reinstall Faraday from scratch? I don't have access to the Postgre database anymore and Ideally I don't want to purge the install of Postegre as other utilities on Kali use that database too.

## Faraday version
3.1.1

## Expected results
I expected all configs to be returned to defaults after purging Faraday from Kali and running a new install of python-faraday 

## Environment information
Kali 2018.2 updated

### Configuration files
The config file is recreated when I run the server for the first time.

### OS

Provide information on your operating system. Example:

$ cat /etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by llazzaro** [comment]
Hi,
The command   python manage.py initdb should create the .faraday directory. Did the command returned an error? Can you paste it here?

**Comment by daniejstriata** [comment]
python manage.py initdb does not recreate if the data is not available:

```
# python2 manage.py initdb
Error while opening file.
[Errno 2] No such file or directory: '/root/.faraday/config/config.xml'. /root/.faraday/config/config.xml
2018-10-17 09:41:20,720 - faraday-server.server.config - INFO {MainThread} [config.py:64 - copy_default_config_to_local() ]  Local faraday-server configuration created at /root/.faraday/config/server.ini
This script will  create a new postgres user  and  save faraday-server settings (server.ini). 
WARNING: Role faraday_postgresql already exists, skipping creation 
Traceback (most recent call last):
  File "manage.py", line 216, in <module>
    cli()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 759, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 714, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1132, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 951, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 552, in invoke
    return callback(*args, **kwargs)
  File "manage.py", line 81, in initdb
    InitDB().run(choose_password=choose_password)
  File "/usr/share/python-faraday/server/commands/initdb.py", line 86, in run
    username, password, process_status = self._configure_new_postgres_user(current_psql_output)
  File "/usr/share/python-faraday/server/commands/initdb.py", line 208, in _configure_new_postgres_user
    password = server.config.database.connection_string.split(':')[2].split('@')[0]
AttributeError: 'NoneType' object has no attribute 'split'
```
Then I look and the .faraday folder is back under ~/.faraday

When I now run the server I get: 
```

# python2 ./faraday-server.py
Error while opening file.
[Errno 2] No such file or directory: '/root/.faraday/config/config.xml'. /root/.faraday/config/config.xml
2018-10-17 09:44:04,397 - faraday-server.__main__ - ERROR {MainThread} [faraday-server.py:102 - check_postgresql() ]  

Could not connect to PostgreSQL.
Please check: 
  * if database is running 
  * configuration settings are correct. 

For first time installations execute: 

  python manage.py initdb


```
When I try to change the password:
```
# python2 manage.py change-password
Error while opening file.
[Errno 2] No such file or directory: '/root/.faraday/config/config.xml'. /root/.faraday/config/config.xml
Enter the Name of the User: faraday
Enter the new password: P4ssw0rd!
Traceback (most recent call last):
  File "manage.py", line 216, in <module>
    cli()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 759, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 714, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1132, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 951, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 552, in invoke
    return callback(*args, **kwargs)
  File "manage.py", line 150, in change_password
    change_pass.changes_password(username, password)
  File "/usr/share/python-faraday/server/commands/change_password.py", line 6, in changes_password
    user = User.query.filter_by(username=username).first()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2835, in first
    ret = list(self[0:1])
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2627, in __getitem__
    return list(res)
  File "/usr/lib/python2.7/dist-packages/nplusone/ext/sqlalchemy.py", line 99, in query_iter
    ret, clone = itertools.tee(original_query_iter(self))
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2935, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2958, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (pysqlite2.dbapi2.OperationalError) no such table: faraday_user [SQL: u'SELECT faraday_user.id AS faraday_user_id, faraday_user.username AS faraday_user_username, faraday_user.password AS faraday_user_password, faraday_user.email AS faraday_user_email, faraday_user.name AS faraday_user_name, faraday_user.is_ldap AS faraday_user_is_ldap, faraday_user.last_login_at AS faraday_user_last_login_at, faraday_user.current_login_at AS faraday_user_current_login_at, faraday_user.last_login_ip AS faraday_user_last_login_ip, faraday_user.current_login_ip AS faraday_user_current_login_ip, faraday_user.login_count AS faraday_user_login_count, faraday_user.active AS faraday_user_active, faraday_user.confirmed_at AS faraday_user_confirmed_at, faraday_user.role AS faraday_user_role \nFROM faraday_user \nWHERE faraday_user.username = ?\n LIMIT ? OFFSET ?'] [parameters: ('faraday', 1, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by llazzaro** [comment]
Hi,

It seems that your server.ini is missing database connection string and that you have created the role faraday_postgresql.

There is a warning message:

`WARNING: Role faraday_postgresql already exists, skipping creation 
`

Make sure there is no improtant faraday data at the database before execute the following commands:

You can drop the role of postgresql with:

```
sudo su postgres
psql -c "DROP ROLE faraday_postgresql" 
```

Then after you deleted the role, re execute:

`python manage.py initdb
`

**Comment by WinnaZ** [comment]
hi @daniejstriata how did it go?

**Comment by CorpOfHack** [comment]
ERROR: role "faraday_postgresql" cannot be dropped because some objects depend on it

**Comment by llazzaro** [comment]
@CorpOfHack the error is related to postgresql.
faraday_postgresql is linked to some objects.
please check:
https://dba.stackexchange.com/questions/155332/find-objects-linked-to-a-postgresql-role

**Comment by isabellah750** [comment]
When i do these steps it shows me this again..
