### ISSUE TITLE
Unable to create workspace on new installation

### ISSUE THREAD

**Issue by skiamakhe** [infobyte/faraday#303]
### UPDATE: Problem is solved. marshmallow module was 3.0.0b14 and needed to be 2.15.3. After updating marshmallow and restarting faraday server, client can create new workspace.

-------------------------------------------------------------------------------------------------------------

> I just pulled the latest code earlier today, and I ran through all the installation instructions here:
> https://github.com/infobyte/faraday/wiki/Installation-Community

status-check:
root@kali:/opt/faraday-dev# python manage.py status-check

Checking if postgreSQL is running...
[+] PostgreSQL is running
[+] PostgreSQL lock not detected. 

Checking if Faraday is running...
[+] Faraday Server is running. PID:2421         
[+] Faraday GTK is running

Checking Faraday dependencies...
[+] Server dependencies met
[+] Client dependencies met

Checking Faraday config...
[+] Credentials matched
[+] /.faraday/storage -> Permission accepted
[+] Port 5985 in localhost is open

> When I start up the faraday client (python faraday.py), it tells me there are no workspaces and asks me to create a workspace. I typed the name "pentestitv11" and hit OK and got this error message:

Exception: 
    Traceback: Traceback (most recent call last):
  File "/opt/faraday-dev/gui/gtk/dialogs.py", line 328, in on_click_ok
    creation_ok = self.create_ws_callback(ws_name, ws_desc)
  File "/opt/faraday-dev/gui/gtk/application.py", line 148, in createWorkspace
    if name in self.workspace_manager.getWorkspacesNames():
  File "/opt/faraday-dev/managers/workspace_manager.py", line 37, in getWorkspacesNames
    return get_workspaces_names()
  File "/opt/faraday-dev/persistence/server/models.py", line 674, in get_workspaces_names
    return map(lambda ws: ws['name'], server.get_workspaces_names())
  File "/opt/faraday-dev/persistence/server/server.py", line 568, in get_workspaces_names
    return _get("{0}/ws".format(_create_server_api_url()))
  File "/opt/faraday-dev/persistence/server/server.py", line 245, in _get
    params=params))
  File "/opt/faraday-dev/persistence/server/server.py", line 188, in wrapper
    response = func(*args, **kwargs)
  File "/opt/faraday-dev/persistence/server/server.py", line 222, in _unsafe_io_with_server
    raise CantCommunicateWithServerError(server_io_function, server_url, payload, answer)
CantCommunicateWithServerError: Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/v2/ws and function <function get at 0x7fa6dd28ecf8>. Response was <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

    
    Identifier: f7e7470347b0608ec52cb9bcb86d7ed0f773564247b1962e5b24453dcec5c935
    Versions: OS: Kali kali-rolling kali-rolling,
              Faraday Version: 3.2
              Python Versions: Python 2.7.15+ 
 Modules: [ zope.interface=4.6.0,webargs=4.1.0,urllib3=1.24,txaio=18.8.1,twisted=18.9.0,tqdm=4.28.1,terminaltables=3.1.0,tabulate=0.8.2,sqlparse=0.2.4,sqlalchemy=1.2.12,setproctitle=1.1.10,service-identity=17.0.0,requests=2.20.0,python-slugify=1.2.6,python-dateutil=2.7.3,pyhamcrest=1.9.0,pyasn1=0.4.4,pyasn1-modules=0.2.2,prompt-toolkit=2.0.6,pgspecial=1.11.2,pgcli=2.0.0,mockito=1.1.1,incremental=17.5.0,idna=2.7,hyperlink=18.0.0,humanize=0.5.1,flask-sqlalchemy=2.3.2,filteralchemy=0.1.0,colorama=0.4.0,click=7.0,cli-helpers=1.1.0,certifi=2018.10.15,backports.csv=1.0.6,automat=0.7.0,autobahn=18.10.1,alembic=1.0.1 ]

> Logs generated from the connection attempt:
> ~/.faraday/logs/faraday-server.log:

2018-10-24 17:38:24,516 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin qualysguard
2018-10-24 17:38:24,518 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin sentinel
2018-10-24 17:38:24,519 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin sshdefaultscan
2018-10-24 17:38:24,522 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin maltego
2018-10-24 17:38:24,523 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin traceroute
2018-10-24 17:38:24,524 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin brutexss
2018-10-24 17:38:24,527 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin acunetix
2018-10-24 17:38:24,528 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin hping3
2018-10-24 17:38:24,530 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin fruitywifi
2018-10-24 17:38:24,549 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin wfuzz
2018-10-24 17:38:24,569 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin junit
2018-10-24 17:38:24,573 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin nikto
2018-10-24 17:38:24,575 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dirb
2018-10-24 17:38:24,578 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin wapiti
2018-10-24 17:38:24,579 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin netdiscover
2018-10-24 17:38:24,581 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin webinspect
2018-10-24 17:38:24,584 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin skipfish
2018-10-24 17:38:24,585 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin ping
2018-10-24 17:38:24,586 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin xsssniper
2018-10-24 17:38:24,587 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin goohost
2018-10-24 17:38:24,588 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin propecia
2018-10-24 17:38:24,591 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin netsparker
2018-10-24 17:38:24,593 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin sslyze
2018-10-24 17:38:24,595 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin listurl
2018-10-24 17:38:24,598 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin impact
2018-10-24 17:38:24,601 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin zap
2018-10-24 17:38:24,602 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin theharvester
2018-10-24 17:38:24,604 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dig
2018-10-24 17:38:24,605 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dirsearch
2018-10-24 17:38:24,607 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin reverseraider
2018-10-24 17:38:24,612 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin openvas
2018-10-24 17:38:24,613 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin ip360
2018-10-24 17:38:24,614 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin peepingtom
2018-10-24 17:38:24,617 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin amap
2018-10-24 17:38:24,621 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin metasploit
2018-10-24 17:38:24,622 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin ftp
2018-10-24 17:38:24,624 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin beef
2018-10-24 17:38:24,627 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin netsparkercloud
2018-10-24 17:38:24,629 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dnsenum
2018-10-24 17:38:24,631 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin wcscan
2018-10-24 17:38:24,633 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin medusa
2018-10-24 17:38:24,634 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dnswalk
2018-10-24 17:38:24,636 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin netcat
2018-10-24 17:38:24,638 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin lynis
2018-10-24 17:38:24,652 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin hydra
2018-10-24 17:38:24,654 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dnsrecon
2018-10-24 17:38:24,658 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin w3af
2018-10-24 17:38:24,669 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin nessus
2018-10-24 17:38:24,671 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin telnet
2018-10-24 17:38:24,673 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin wpscan
2018-10-24 17:38:24,675 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin webfuzzer
2018-10-24 17:38:24,676 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin reconng
2018-10-24 17:38:24,677 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin nmap
2018-10-24 17:38:24,685 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin sqlmap
2018-10-24 17:38:24,686 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin arp-scan
2018-10-24 17:38:24,687 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin ndiff
2018-10-24 17:38:24,688 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin sublist3r
2018-10-24 17:38:24,692 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin nexpose-full
2018-10-24 17:38:24,694 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin sslcheck
2018-10-24 17:38:24,713 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin metasploiton
2018-10-24 17:38:24,715 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin masscan
2018-10-24 17:38:24,716 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin metagoofil
2018-10-24 17:38:24,758 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin burp
2018-10-24 17:38:24,759 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin whois
2018-10-24 17:38:24,762 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin nexpose
2018-10-24 17:38:24,764 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin x1
2018-10-24 17:38:24,766 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin fierce
2018-10-24 17:38:24,768 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin dnsmap
2018-10-24 17:38:24,772 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin arachni
2018-10-24 17:38:24,774 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin retina
2018-10-24 17:38:24,779 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin appscan
2018-10-24 17:38:24,780 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin pasteanalyzer
2018-10-24 17:38:27,224 - flask.app - ERROR {PoolThread-twisted.internet.reactor-0} [app.py:1761 - log_exception() ]  Exception on /v2/ws/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/opt/faraday-dev/server/api/base.py", line 421, in index
    return self._envelope_list(self._dump(objects, kwargs, many=True),
  File "/opt/faraday-dev/server/api/modules/workspaces.py", line 108, in _dump
    return super(WorkspaceView, self)._dump(obj, route_kwargs, **kwargs)
  File "/opt/faraday-dev/server/api/base.py", line 285, in _dump
    return self._get_schema_instance(route_kwargs, **kwargs).dump(obj).data
  File "/opt/faraday-dev/server/api/base.py", line 173, in _get_schema_instance
    return self._get_schema_class()(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'strict'
2018-10-24 17:38:27,633 - flask.app - ERROR {PoolThread-twisted.internet.reactor-0} [app.py:1761 - log_exception() ]  Exception on /v2/ws/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/opt/faraday-dev/server/api/base.py", line 421, in index
    return self._envelope_list(self._dump(objects, kwargs, many=True),
  File "/opt/faraday-dev/server/api/modules/workspaces.py", line 108, in _dump
    return super(WorkspaceView, self)._dump(obj, route_kwargs, **kwargs)
  File "/opt/faraday-dev/server/api/base.py", line 285, in _dump
    return self._get_schema_instance(route_kwargs, **kwargs).dump(obj).data
  File "/opt/faraday-dev/server/api/base.py", line 173, in _get_schema_instance
    return self._get_schema_class()(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'strict'
2018-10-24 17:38:27,692 - flask.app - ERROR {PoolThread-twisted.internet.reactor-1} [app.py:1761 - log_exception() ]  Exception on /v2/ws/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/opt/faraday-dev/server/api/base.py", line 421, in index
    return self._envelope_list(self._dump(objects, kwargs, many=True),
  File "/opt/faraday-dev/server/api/modules/workspaces.py", line 108, in _dump
    return super(WorkspaceView, self)._dump(obj, route_kwargs, **kwargs)
  File "/opt/faraday-dev/server/api/base.py", line 285, in _dump
    return self._get_schema_instance(route_kwargs, **kwargs).dump(obj).data
  File "/opt/faraday-dev/server/api/base.py", line 173, in _get_schema_instance
    return self._get_schema_class()(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'strict'
2018-10-24 17:38:27,728 - flask.app - ERROR {PoolThread-twisted.internet.reactor-1} [app.py:1761 - log_exception() ]  Exception on /v2/ws/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/opt/faraday-dev/server/api/base.py", line 421, in index
    return self._envelope_list(self._dump(objects, kwargs, many=True),
  File "/opt/faraday-dev/server/api/modules/workspaces.py", line 108, in _dump
    return super(WorkspaceView, self)._dump(obj, route_kwargs, **kwargs)
  File "/opt/faraday-dev/server/api/base.py", line 285, in _dump
    return self._get_schema_instance(route_kwargs, **kwargs).dump(obj).data
  File "/opt/faraday-dev/server/api/base.py", line 173, in _get_schema_instance
    return self._get_schema_class()(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'strict'

> ~/.faraday/logs/faraday.log:

2018-10-24 17:38:21,971 - faraday.launcher - INFO [faraday.py:191 - check_dependencies_or_exit() ]  Checking dependencies...
2018-10-24 17:38:21,971 - faraday.launcher - INFO [faraday.py:209 - check_dependencies_or_exit() ]  Dependencies met
2018-10-24 17:38:21,971 - faraday.launcher - INFO [faraday.py:404 -          printBanner() ]  Starting Faraday IDE.
2018-10-24 17:38:21,972 - faraday.launcher - INFO [faraday.py:355 -   checkConfiguration() ]  Checking configuration.
2018-10-24 17:38:21,972 - faraday.launcher - INFO [faraday.py:356 -   checkConfiguration() ]  Setting up plugins.
2018-10-24 17:38:21,972 - faraday.launcher - INFO [faraday.py:294 -         setupPlugins() ]  Removing old plugins folder.
2018-10-24 17:38:22,011 - faraday.launcher - INFO [faraday.py:358 -   checkConfiguration() ]  Setting up ZSH integration.
2018-10-24 17:38:22,011 - faraday.launcher - INFO [faraday.py:360 -   checkConfiguration() ]  Setting up user configuration.
2018-10-24 17:38:22,012 - faraday.launcher - INFO [faraday.py:335 -       setupXMLConfig() ]  Using custom user configuration.
2018-10-24 17:38:22,038 - faraday.launcher - INFO [faraday.py:362 -   checkConfiguration() ]  Setting up icons for GTK interface.
2018-10-24 17:38:22,046 - faraday.launcher - INFO [faraday.py:218 -              setConf() ]  Setting configuration.
2018-10-24 17:38:23,917 - faraday.launcher - INFO [faraday.py:529 -                login() ]  Login successful: faraday
2018-10-24 17:38:24,318 - faraday.launcher - INFO [faraday.py:429 -         checkUpdates() ]  No updates available, enjoy Faraday.
2018-10-24 17:38:24,508 - faraday.launcher - INFO [faraday.py:248 -         startFaraday() ]  All done. Opening environment.
2018-10-24 17:38:27,023 - faraday.launcher - INFO [faraday.py:254 -         startFaraday() ]  Main application ExceptHook enabled.
2018-10-24 17:38:27,024 - faraday.launcher - INFO [faraday.py:257 -         startFaraday() ]  Starting main application.
2018-10-24 17:38:27,028 - faraday - INFO [api.py:118 -      _setUpAPIServer() ]  XMLRPC API server configured on ('localhost', 9876)
2018-10-24 17:38:27,048 - faraday - INFO [api.py:68 -            startAPIs() ]  REST API server configured on ('localhost', 9977)
2018-10-24 17:38:27,227 - faraday.Server-GTK IO - WARNING [decorators.py:23 -              wrapper() ]  Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/v2/ws and function <function get at 0x7f4aa9a5dcf8>. Response was <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

2018-10-24 17:38:27,636 - faraday.GTK - ERROR [application.py:478 -   background_process() ]  Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/v2/ws and function <function get at 0x7f4aa9a5dcf8>. Response was <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

2018-10-24 17:38:27,705 - faraday.Server-GTK IO - WARNING [decorators.py:23 -              wrapper() ]  Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/v2/ws and function <function get at 0x7f4aa9a5dcf8>. Response was <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

2018-10-24 17:38:27,731 - faraday.Server-GTK IO - WARNING [decorators.py:23 -              wrapper() ]  Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/v2/ws and function <function get at 0x7f4aa9a5dcf8>. Response was <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by llazzaro** [comment]
Can you try this commands:

``` bash
pip uninstall marshmallow
pip install marshmallow==2.15.3
```

**Comment by skiamakhe** [comment]
I couldn't actually uninstall the previous marshmallow verison, but in the end, it reported the new version accurately and in the subsequent error message below:

root@kali:~/.faraday/logs# pip freeze |grep marshmallow
Warning: cannot find svn location for chirp===daily-20180815
marshmallow==3.0.0b14
marshmallow-sqlalchemy==0.14.1
root@kali:~/.faraday/logs# pip uninstall marshmallow
Not uninstalling marshmallow at /usr/lib/python2.7/dist-packages, outside environment /usr
root@kali:~/.faraday/logs# pip freeze |grep marshmallow
Warning: cannot find svn location for chirp===daily-20180815
marshmallow==3.0.0b14
marshmallow-sqlalchemy==0.14.1
root@kali:~/.faraday/logs# pip install marshmallow==2.15.3
Collecting marshmallow==2.15.3
  Downloading https://files.pythonhosted.org/packages/bd/c0/b176d4bcb59e973e23029573785ca3dd3a908dac26915f67004dd4ffc356/marshmallow-2.15.3-py2.py3-none-any.whl (44kB)
    100% |████████████████████████████████| 51kB 1.6MB/s
Installing collected packages: marshmallow
  Found existing installation: marshmallow 3.0.0b14
    Not uninstalling marshmallow at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed marshmallow-2.15.3
root@kali:~/.faraday/logs# pip freeze |grep marshmallow
Warning: cannot find svn location for chirp===daily-20180815
marshmallow==2.15.3
marshmallow-sqlalchemy==0.14.1

Trying to set a workspace gives the same result:

Exception: 
    Traceback: Traceback (most recent call last):
  File "/opt/faraday-dev/gui/gtk/dialogs.py", line 328, in on_click_ok
    creation_ok = self.create_ws_callback(ws_name, ws_desc)
  File "/opt/faraday-dev/gui/gtk/application.py", line 148, in createWorkspace
    if name in self.workspace_manager.getWorkspacesNames():
  File "/opt/faraday-dev/managers/workspace_manager.py", line 37, in getWorkspacesNames
    return get_workspaces_names()
  File "/opt/faraday-dev/persistence/server/models.py", line 674, in get_workspaces_names
    return map(lambda ws: ws['name'], server.get_workspaces_names())
  File "/opt/faraday-dev/persistence/server/server.py", line 568, in get_workspaces_names
    return _get("{0}/ws".format(_create_server_api_url()))
  File "/opt/faraday-dev/persistence/server/server.py", line 245, in _get
    params=params))
  File "/opt/faraday-dev/persistence/server/server.py", line 188, in wrapper
    response = func(*args, **kwargs)
  File "/opt/faraday-dev/persistence/server/server.py", line 222, in _unsafe_io_with_server
    raise CantCommunicateWithServerError(server_io_function, server_url, payload, answer)
CantCommunicateWithServerError: Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/v2/ws and function <function get at 0x7ffa4421ecf8>. Response was <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>


    
    Identifier: 669c211c91a28d2569181ed11765653db880d2886e044f55ccb1e90723773cc7
    Versions: OS: Kali kali-rolling kali-rolling,
              Faraday Version: 3.2
              Python Versions: Python 2.7.15+ 
 Modules: [ zope.interface=4.6.0,webargs=4.1.0,urllib3=1.24,txaio=18.8.1,twisted=18.9.0,tqdm=4.28.1,terminaltables=3.1.0,tabulate=0.8.2,sqlparse=0.2.4,sqlalchemy=1.2.12,setproctitle=1.1.10,service-identity=17.0.0,requests=2.20.0,python-slugify=1.2.6,python-dateutil=2.7.3,pyhamcrest=1.9.0,pyasn1=0.4.4,pyasn1-modules=0.2.2,prompt-toolkit=2.0.6,pgspecial=1.11.2,pgcli=2.0.0,mockito=1.1.1,marshmallow=2.15.3,incremental=17.5.0,idna=2.7,hyperlink=18.0.0,humanize=0.5.1,flask-sqlalchemy=2.3.2,filteralchemy=0.1.0,colorama=0.4.0,click=7.0,cli-helpers=1.1.0,certifi=2018.10.15,backports.csv=1.0.6,automat=0.7.0,autobahn=18.10.1,alembic=1.0.1 ]
   

Is there a way to manually create a workspace, maybe via database commands?

**Comment by llazzaro** [comment]
Can you send us the latest error message from the faraday-server.log? 
Did you restarted the server?

You can also start the server and client with --debug parameter for more verbose messages.

**Comment by skiamakhe** [comment]
I had forgotten to restart the server. Now everything is working. Thanks.
