### ISSUE TITLE
Unbale to access the Server API

### ISSUE THREAD

**Issue by Thilaknath** [infobyte/faraday#314]
## Issue Type
 - Question

## Faraday version
C-3.2

## Component Name

If you know where the problem lays indicate it:
Faraday Server API

## Steps to reproduce
1) I am trying to access to Faraday Server API trough postman
2) In order to get and save a cookie ( I tried accessing /_api/login) with the following payload
`{"email": "faraday", "password": "changeme"}`

## Observed results

I get the following error in the Server
`AttributeError: 'LdapReadyLoginForm' object has no attribute 'user'
/usr/local/lib/python2.7/dist-packages/twisted/web/wsgi.py:128: UnicodeWarning: write() argument should be str, not u'[2018-11-13 09:31:52,253] ERROR in app: Exception on /login [GET]\nTraceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/usr/local/lib/python2.7/dist-packages/flask_security/decorators.py", line 230, in wrapper\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/flask_security/views.py", line 85, in login\n    return _render_json(form, include_auth_token=True)\n  File "/usr/local/lib/python2.7/dist-packages/flask_security/views.py", line 48, in _render_json\n    response[\'user\'] = form.user.get_security_payload()\nAttributeError: \'LdapReadyLoginForm\' object has no attribute \'user\'\n' (unicode)
  data, type(data).__name__), category=UnicodeWarning)
2018-11-13 09:31:52,253 - flask.app - ERROR {PoolThread-twisted.internet.reactor-0} [app.py:1761 - log_exception() ]  Exception on /login [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_security/decorators.py", line 230, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_security/views.py", line 85, in login
    return _render_json(form, include_auth_token=True)
  File "/usr/local/lib/python2.7/dist-packages/flask_security/views.py", line 48, in _render_json
    response['user'] = form.user.get_security_payload()
AttributeError: 'LdapReadyLoginForm' object has no attribute 'user'`
### OS

Windows 10 (Host OS)

Provide information on your operating system. Example:

$ cat /etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by Thilaknath** [comment]
Postman was parsing the arguments wrong causing the server to throw out errors. Based on analyzing the actual browser requests sent from faraday and copying that request with in Postman worked. Now i am able to access the apis
