### ISSUE TITLE
[Error 500] With nginx

### ISSUE THREAD

**Issue by vwhissell** [infobyte/faraday#320]
Hello,
Got faraday-server to run fine, and got nginx to make it available from the outside.
However, when I add a Vulnerability, click Ok got this:
```
Oops!
Error from backend: 500
```

On the faraday-server.py console:
```
/usr/local/lib/python2.7/dist-packages/twisted/web/wsgi.py:128: UnicodeWarning: write() argument should be str, not u'[2018-11-22 08:53:12,403] ERROR in app: Exception on /v2/ws/t/vulns/ [POST]\nTraceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy\n    response = view(**request.view_args)\n  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner\n    return fn(*args, **kwargs)\n  File "/root/faraday-dev/server/api/base.py", line 602, in post\n    created = self._perform_create(data, **kwargs)\n  File "/root/faraday-dev/server/api/modules/vulns.py", line 435, in _perform_create\n    obj.references = references\n  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 181, in __set__\n    return self._as_instance(class_).set(obj, values)\n  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 479, in set\n    proxy = self.get(obj)\n  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 461, in get\n    _lazy_collection(obj, self.target_collection))\n  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 502, in _new\n    lazy_collection, creator, self.value_attr, self)\n  File "/root/faraday-dev/server/models.py", line 544, in __init__\n    if parent.getset_factory:\nAttributeError: \'ColumnAssociationProxyInstance\' object has no attribute \'getset_factory\'\n' (unicode)
  data, type(data).__name__), category=UnicodeWarning)
2018-11-22 08:53:12,403 - flask.app - ERROR {PoolThread-twisted.internet.reactor-2} [app.py:1761 - log_exception() ]  Exception on /v2/ws/t/vulns/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/root/faraday-dev/server/api/base.py", line 602, in post
    created = self._perform_create(data, **kwargs)
  File "/root/faraday-dev/server/api/modules/vulns.py", line 435, in _perform_create
    obj.references = references
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 181, in __set__
    return self._as_instance(class_).set(obj, values)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 479, in set
    proxy = self.get(obj)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 461, in get
    _lazy_collection(obj, self.target_collection))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 502, in _new
    lazy_collection, creator, self.value_attr, self)
  File "/root/faraday-dev/server/models.py", line 544, in __init__
    if parent.getset_factory:
AttributeError: 'ColumnAssociationProxyInstance' object has no attribute 'getset_factory'
```

nginx config under /etc/nginx/sites-enabled/default, location

```
proxy_pass http://localhost:5985/;
proxy_redirect http:// $scheme://;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Ssl on;
```

Locally, I don't get that Error 500 (running firefox locally)
But I get this when passing through the nginx server.
Is there anything missing on the nginx server?

**Comment by llazzaro** [comment]
Hi,

There is a problem with SQLAlchemy 1.3.0b1 (which is a pre-release).

Please install SQLAlchemy stable version with:

`pip install SQLAlchemy==1.2.14`

**Comment by vwhissell** [comment]
> 
> 
> Hi,
> 
> There is a problem with SQLAlchemy 1.3.0b1 (which is a pre-release).
> 
> Please install SQLAlchemy stable version with:
> 
> `pip install SQLAlchemy==1.2.14`

Worked like a charm!
No error 500, no error in the server console. Runs perfectly.

Many many thanks again! :+1:
