### ISSUE TITLE
Unable to save Vuln Model (Vuln Templates Import)

### ISSUE THREAD

**Issue by Athrekas** [infobyte/faraday#328]
## Issue Type
 - Bug Report

## Faraday version

Faraday vc-3.3

## Component Name

Vulnerability Templates

## Steps to reproduce

Import CSV from data/ folder.

## Expected results

Successfully import CWE CSV.

### Debugging tracebacks (current results)

2018-12-04 15:38:24,020 - flask.app - ERROR {PoolThread-twisted.internet.reactor-1} [app.py:1761 - log_exception() ]  Exception on /v2/vulnerability_template/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "./server/api/modules/vulnerability_template.py", line 100, in post
  File "./server/api/base.py", line 626, in post
  File "./server/api/base.py", line 637, in _perform_create
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 437, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 434, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/base.py", line 767, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 181, in __set__
    return self._as_instance(class_).set(obj, values)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 479, in set
    proxy = self.get(obj)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 461, in get
    _lazy_collection(obj, self.target_collection))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 502, in _new
    lazy_collection, creator, self.value_attr, self)
  File "./server/models.py", line 387, in __init__
AttributeError: 'ColumnAssociationProxyInstance' object has no attribute 'getset_factory'

adns-python==1.2.1
alembic==1.0.0.dev0
anyjson==0.3.3
argcomplete==1.8.1
asn1crypto==0.24.0
atomicwrites==1.1.5
attrs==18.2.0
autobahn==18.11.2
Automat==0.6.0
Babel==2.6.0
backdoor-factory==0.0.0
backports-abc==0.5
backports.csv==1.0.6
backports.functools-lru-cache==1.5
backports.ssl-match-hostname==3.5.0.1
BBQSQL==1.0
bcrypt==3.1.4
bdfproxy==0.0.0
beautifulsoup4==4.6.3
BlindElephant==1.0
blinker==1.4
capstone==3.0.5
cbor==1.0.0
certifi==2018.11.29
chardet==3.0.4
CherryTree==0.38.5
#### FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20180815
cli-helpers==1.1.0
Click==7.0
colorama==0.4.1
ConfigArgParse==0.13.0
configobj==5.0.6
configparser==3.5.0b2
constantly==15.1.0
construct==2.8.16
couchdbkit==0.6.5
cryptography==2.3
cycler==0.10.0
Cython==0.28.4
deprecation==2.0.6
dhcpig==0.0.0
dicttoxml==1.7.4
distorm3==3.3.8
dnslib==0.9.7
dnspython==1.15.0
docutils==0.14
easygui==0.96
EditorConfig==0.12.1
Elixir==0.7.1
entrypoints==0.2.3.post3
enum34==1.1.6
et-xmlfile==1.0.1
feedparser==5.2.1
filedepot==0.5.2
filteralchemy==0.1.0
Flask==1.0.2
Flask-BabelEx==0.9.3
Flask-Classful==0.14.1
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-Security==3.0.0
Flask-Session==0.3.1
Flask-SQLAlchemy==2.1
Flask-WTF==0.14.2
funcsigs==1.0.2
fuse-python==0.3.1
future==0.15.2
futures==3.2.0
GDAL==2.3.2
GeoIP==1.3.2
gevent==1.3.7
greenlet==0.4.15
h2==3.0.1
hpack==3.0.0
html2text==2018.1.9
html5lib==1.0.1
http-parser==0.8.3
httplib2==0.11.3
humanize==0.5.1
hyperframe==5.1.0
hyperlink==17.3.1
idna==2.7
impacket==0.9.17
incremental==16.10.1
ipaddress==1.0.17
IPy==0.83
itsdangerous==0.24
jdcal==1.0
Jinja2==2.10
jsbeautifier==1.6.4
jsonpickle==0.9.5
jsonrpclib==0.1.7
keyring==16.1.1
keyrings.alt==3.1
killerbee==1.0
kiwisolver==1.0.1
ldap3==2.4.1
lxml==4.2.5
lz4==1.1.0
M2Crypto==0.31.0
Mako==1.0.7
MarkupSafe==1.0
marshmallow==3.0.0b3
marshmallow-sqlalchemy==0.14.1
matplotlib==2.2.2
mechanize==0.2.5
mercurial==4.7.2
metaconfig==0.1.4a1
mockito==1.1.1
more-itertools==4.2.0
msgpack==0.5.6
mysqlclient==1.3.10
nassl==0.12
netaddr==0.7.19
NfSpy==1.0
nplusone==1.0.0
numpy==1.14.5
olefile==0.46
openpyxl==2.4.9
OWSLib==0.17.0
packaging==18.0
PAM==0.4.2
paramiko==2.4.0
passlib==1.7.1
pcapy==0.10.8
peepdf==0.4.2
pefile==2018.8.8
pexpect==4.6.0
pgcli==2.0.1
pgspecial==1.11.4
Pillow==5.3.0
pluggy==0.8.0
prettytable==0.7.2
prompt-toolkit==2.0.7
psycopg2==2.7.6.1
py==1.7.0
py-ubjson==0.12.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycrypto==2.6.1
pycurl==7.43.0.1
pydns==2.3.6
pydot==1.2.4
pyenchant==2.0.0
Pygments==2.3.0
PyGObject==3.30.2
pygtkspellcheck==4.0.5
pyinotify==0.9.6
PyJWT==1.6.4
pylibemu==0.3.3
pymongo==3.7.1
pymssql==2.1.3
PyNaCl==1.3.0
pyOpenSSL==18.0.0
pyparsing==2.2.0
PyPDF2==1.26.0
pyperclip==1.6.4
pyproj==1.9.5.1
pyrit==0.5.1
pyscard==1.9.7
pyserial==3.4
PySocks==1.6.8
pyspatialite==3.0.1
pysqlite==2.7.0
pytest==3.6.4
python-dateutil==2.7.5
python-editor==1.0.3
python-Levenshtein==0.12.0
python-magic==0.4.16
python-slugify==1.2.5
python-snappy==0.5.3
pythonaes==1.0
PyTrie==0.2
pytz==2018.7
pyusb==1.0.2
PyV8==1.0.dev0
PyX==0.12.1
pyxdg==0.25
PyYAML==3.13
qrcode==6.0
requests==2.20.1
restkit==4.2.2
rfidiot==1.0
roman==2.0.0
scapy==2.4.0
SecretStorage==2.3.1
selenium==3.14.1
service-identity==16.0.0
setproctitle==1.1.10
Shapely==1.6.4
simplejson==3.15.0
singledispatch==3.4.0.3
sipvicious==0.2.8
six==1.11.0
slowaes==0.1a1
socketpool==0.5.3
speaklater==1.3
SQLAlchemy==1.2.8
sqlalchemy-schemadisplay==1.3
sqlparse==0.2.4
subprocess32==3.5.3
tabulate==0.8.2
tcpwatch==1.3.1
terminaltables==3.1.0
tornado==5.1.1
tqdm==4.28.1
trollius==2.0.1
Twisted==18.7.0
txaio==18.8.1
typing==3.6.6
u-msgpack-python==2.1
unicodecsv==0.14.1
Unidecode==1.0.22
urllib3==1.24.1
urwid==2.0.1
uTidylib==0.5
vinetto==0.7b0
volatility==2.6
wcwidth==0.1.7
webargs==4.0.0
webencodings==0.5
websocket-client==0.54.0
webunit==1.3.10
Werkzeug==0.14.1
wfuzz==2.3.1
Whoosh==2.7.4
wifite==2.2.5
wsaccel==0.6.2
WTForms==2.2.1
wxPython==3.0.2.0
wxPython-common==3.0.2.0
XlsxWriter==0.9.6
xmlbuilder==1.0
yara-python==3.8.0
zenmap==7.70
zim==0.68
zope.interface==4.3.2

### OS

PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by llazzaro** [comment]
Hi,
We are going to release an update to support the laster version of sqlalchemy soon.
please downgrade sqlalchemy with:
pip install SQLAlchemy==1.2.4

**Comment by Athrekas** [comment]
Downgrading SQLAlchemy worked, closing the issue. Thanks!
