### ISSUE TITLE
[DISPATCHING ERROR] Could not import any report to remote faraday server from client host.

### ISSUE THREAD

**Issue by CorpOfHack** [infobyte/faraday#330]
after trying to copy any report file to report directory in client PTE , for example arachn.xml:

**cp arachni_report.xml /root/.faraday/report/**

I have this error output from my Client Faraday PTE.

[ ERROR ]- 2018-12-12 15:55:59,662 - faraday - An exception occurred while dispatching an action (<bound method ModelController.__add of <ModelController(Thread-1, started 139814271710976)>>((<persistence.server.models.Host object at 0x7f29081b8750>, 1))
Traceback (most recent call last):
  File "./model/controller.py", line 177, in _dispatchActionWithLock
  File "./model/controller.py", line 368, in __add
  File "./model/controller.py", line 347, in _save_new_object
  File "./managers/mapper_manager.py", line 28, in save
  File "./persistence/server/models.py", line 514, in create_object
  File "./persistence/server/models.py", line 72, in func_wrapper
  File "./persistence/server/models.py", line 355, in create_host
  File "./persistence/server/server.py", line 977, in create_host
  File "./persistence/server/server.py", line 340, in _save_to_server
  File "./persistence/server/server.py", line 269, in _post
  File "./persistence/server/server.py", line 187, in wrapper
  File "./persistence/server/server.py", line 221, in _unsafe_io_with_server
CantCommunicateWithServerError: Couldn't get a valid response from the server when requesting to URL https://faraday.server/_api/v2/ws/hack/hosts/?command_id=1 and function <function post at 0x7f291a8b5b18>. Response was <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

The same output in client logfile:

**tail -n 20 /root/.faraday/logs/faraday.log**       
   
2018-12-12 15:55:59,662 - faraday - ERROR [api.py:485 -                  log() ]  An exception occurred while dispatching an action (<bound method ModelController.__add of <ModelController(Thread-1, started 139814271710976)>>((<persistence.server.models.Host object at 0x7f29081b8750>, 1))
Traceback (most recent call last):
  File "./model/controller.py", line 177, in _dispatchActionWithLock
  File "./model/controller.py", line 368, in __add
  File "./model/controller.py", line 347, in _save_new_object
  File "./managers/mapper_manager.py", line 28, in save
  File "./persistence/server/models.py", line 514, in create_object
  File "./persistence/server/models.py", line 72, in func_wrapper
  File "./persistence/server/models.py", line 355, in create_host
  File "./persistence/server/server.py", line 977, in create_host
  File "./persistence/server/server.py", line 340, in _save_to_server
  File "./persistence/server/server.py", line 269, in _post
  File "./persistence/server/server.py", line 187, in wrapper
  File "./persistence/server/server.py", line 221, in _unsafe_io_with_server
CantCommunicateWithServerError: Couldn't get a valid response from the server when requesting to URL https://faraday.server/_api/v2/ws/hack/hosts/?command_id=1 and function <function post at 0x7f291a8b5b18>. Response was <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

Here is error from server logfile:

**tail -n 35 /root/.faraday/logs/faraday-server.log**

2018-12-12 15:54:30,110 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin openvas
2018-12-12 15:54:30,112 - faraday-server.PluginManager - DEBUG {MainThread} [manager.py:120 - _loadPlugins() ]  Loading plugin impact
2018-12-12 15:54:30,144 - faraday-server.server.web - INFO {MainThread} [web.py:178 - run() ]  Starting webserver with 2 threads.
2018-12-12 15:54:30,144 - faraday-server.server.web - INFO {MainThread} [web.py:135 - __build_websockets_resource() ]  Starting websocket server at port 9000 with bind address localhost. SSL False
2018-12-12 15:54:30,147 - faraday-server.server.web - INFO {MainThread} [web.py:185 - run() ]  Faraday Server is ready
2018-12-12 15:56:00,169 - flask.app - ERROR {PoolThread-twisted.internet.reactor-1} [app.py:1761 - log_exception() ]  Exception on /v2/ws/hack/hosts/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "./server/api/base.py", line 626, in post
  File "./server/api/modules/hosts.py", line 153, in _perform_create
  File "./server/api/base.py", line 721, in _perform_create
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 181, in __set__
    return self._as_instance(class_).set(obj, values)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 479, in set
    proxy = self.get(obj)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 461, in get
    _lazy_collection(obj, self.target_collection))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/associationproxy.py", line 502, in _new
    lazy_collection, creator, self.value_attr, self)
  File "./server/models.py", line 387, in __init__
AttributeError: 'ColumnAssociationProxyInstance' object has no attribute 'getset_factory'
2018-12-12 15:56:00,425 - faraday-server.server.websocket_factories - DEBUG {MainThread} [websocket_factories.py:149 - broadcast() ]  broadcasting prepared message '{"action": "CREATE", "type": "Host", "id": 1, "workspace": "hack", "name": "_HERE_IS_CLIENT_IP_ADDRESS_"}'

**Comment by CorpOfHack** [comment]
Found solution here. Thanks!
https://github.com/infobyte/faraday/issues/328#issuecomment-444165537

**Comment by llazzaro** [comment]
Or you can upgrade to v3.4!
