### ISSUE TITLE
Internal Server 500 Error - Remote Faraday server

### ISSUE THREAD

**Issue by njdonarski** [infobyte/faraday#331]
500 Internal Server Error Results when connecting to remote faraday community server.

`/usr/local/lib/python2.7/dist-packages/twisted/web/wsgi.py:128: UnicodeWarning: write() argument should be str, not u'[2019-01-08 00:09:21,547] ERROR in app: Exception on /v2/ws/knowles/vulns/count/ [GET]\nTraceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy\n    response = view(**request.view_args)\n  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner\n    return fn(*args, **kwargs)\n  File "/home/ubuntu/faraday-dev/server/api/modules/vulns.py", line 551, in count\n    res = super(VulnerabilityView, self).count(**kwargs)\n  File "/home/ubuntu/faraday-dev/server/api/base.py", line 856, in count\n    *self.count_extra_filters))\n  File "/home/ubuntu/faraday-dev/server/api/modules/vulns.py", line 506, in _filter_query\n    query = super(VulnerabilityView, self)._filter_query(query)\n  File "/home/ubuntu/faraday-dev/server/api/base.py", line 547, in _filter_query\n    return self.filterset_class(query).filter()\n  File "/home/ubuntu/faraday-dev/server/api/modules/vulns.py", line 391, in filter\n    query = super(VulnerabilityFilterSet, self).filter()\n  File "/usr/local/lib/python2.7/dist-packages/filteralchemy/filterset.py", line 158, in filter\n    args = self.opts.parser.parse(argmap)\n  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 344, in parse\n    parsed = self._parse_request(schema=schema, req=req, locations=locations)\n  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 259, in _parse_request\n    parsed_value = self.parse_arg(argname, field_obj, req, locations)\n  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 231, in parse_arg\n    value = self._get_value(name, field, req=req, location=location)\n  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 204, in _get_value\n    value = function(req, name, argobj)\n  File "/usr/local/lib/python2.7/dist-packages/webargs/flaskparser.py", line 66, in parse_json\n    except json.JSONDecodeError as e:\nAttributeError: \'module\' object has no attribute \'JSONDecodeError\'\n' (unicode)
  data, type(data).__name__), category=UnicodeWarning)
2019-01-08 00:09:21,547 - flask.app - ERROR {PoolThread-twisted.internet.reactor-2} [app.py:1761 - log_exception() ]  Exception on /v2/ws/knowles/vulns/count/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/ubuntu/faraday-dev/server/api/modules/vulns.py", line 551, in count
    res = super(VulnerabilityView, self).count(**kwargs)
  File "/home/ubuntu/faraday-dev/server/api/base.py", line 856, in count
    *self.count_extra_filters))
  File "/home/ubuntu/faraday-dev/server/api/modules/vulns.py", line 506, in _filter_query
    query = super(VulnerabilityView, self)._filter_query(query)
  File "/home/ubuntu/faraday-dev/server/api/base.py", line 547, in _filter_query
    return self.filterset_class(query).filter()
  File "/home/ubuntu/faraday-dev/server/api/modules/vulns.py", line 391, in filter
    query = super(VulnerabilityFilterSet, self).filter()
  File "/usr/local/lib/python2.7/dist-packages/filteralchemy/filterset.py", line 158, in filter
    args = self.opts.parser.parse(argmap)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 344, in parse
    parsed = self._parse_request(schema=schema, req=req, locations=locations)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 259, in _parse_request
    parsed_value = self.parse_arg(argname, field_obj, req, locations)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 231, in parse_arg
    value = self._get_value(name, field, req=req, location=location)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 204, in _get_value
    value = function(req, name, argobj)
  File "/usr/local/lib/python2.7/dist-packages/webargs/flaskparser.py", line 66, in parse_json
    except json.JSONDecodeError as e:
AttributeError: 'module' object has no attribute 'JSONDecodeError'
/usr/local/lib/python2.7/dist-packages/twisted/web/wsgi.py:128: UnicodeWarning: write() argument should be str, not u'[2019-01-08 00:09:21,550] ERROR in app: Exception on /v2/ws/knowles/hosts/ [GET]\nTraceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy\n    response = view(**request.view_args)\n  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner\n    return fn(*args, **kwargs)\n  File "/home/ubuntu/faraday-dev/server/api/base.py", line 418, in index\n    query = self._filter_query(self._get_eagerloaded_query(**kwargs))\n  File "/home/ubuntu/faraday-dev/server/api/modules/hosts.py", line 164, in _filter_query\n    query = super(HostsView, self)._filter_query(query)\n  File "/home/ubuntu/faraday-dev/server/api/base.py", line 547, in _filter_query\n    return self.filterset_class(query).filter()\n  File "/usr/local/lib/python2.7/dist-packages/filteralchemy/filterset.py", line 158, in filter\n    args = self.opts.parser.parse(argmap)\n  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 344, in parse\n    parsed = self._parse_request(schema=schema, req=req, locations=locations)\n  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 259, in _parse_request\n    parsed_value = self.parse_arg(argname, field_obj, req, locations)\n  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 231, in parse_arg\n    value = self._get_value(name, field, req=req, location=location)\n  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 204, in _get_value\n    value = function(req, name, argobj)\n  File "/usr/local/lib/python2.7/dist-packages/webargs/flaskparser.py", line 66, in parse_json\n    except json.JSONDecodeError as e:\nAttributeError: \'module\' object has no attribute \'JSONDecodeError\'\n' (unicode)
  data, type(data).__name__), category=UnicodeWarning)
2019-01-08 00:09:21,550 - flask.app - ERROR {PoolThread-twisted.internet.reactor-3} [app.py:1761 - log_exception() ]  Exception on /v2/ws/knowles/hosts/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/ubuntu/faraday-dev/server/api/base.py", line 418, in index
    query = self._filter_query(self._get_eagerloaded_query(**kwargs))
  File "/home/ubuntu/faraday-dev/server/api/modules/hosts.py", line 164, in _filter_query
    query = super(HostsView, self)._filter_query(query)
  File "/home/ubuntu/faraday-dev/server/api/base.py", line 547, in _filter_query
    return self.filterset_class(query).filter()
  File "/usr/local/lib/python2.7/dist-packages/filteralchemy/filterset.py", line 158, in filter
    args = self.opts.parser.parse(argmap)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 344, in parse
    parsed = self._parse_request(schema=schema, req=req, locations=locations)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 259, in _parse_request
    parsed_value = self.parse_arg(argname, field_obj, req, locations)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 231, in parse_arg
    value = self._get_value(name, field, req=req, location=location)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 204, in _get_value
    value = function(req, name, argobj)
  File "/usr/local/lib/python2.7/dist-packages/webargs/flaskparser.py", line 66, in parse_json
    except json.JSONDecodeError as e:
AttributeError: 'module' object has no attribute 'JSONDecodeError'
`

![image](https://user-images.githubusercontent.com/30577973/50800817-8c0cd380-12a7-11e9-8a63-69360c7745a0.png)

**Faraday Community client installed on multiple OS versions result in the same issue.** 

[ WARNING ]- 2019-01-07 19:03:00,904 - faraday.Server-GTK IO - Couldn't get a valid response from the server when requesting to URL http://34.210.88.185:5985/_api/v2/ws/knowles/hosts and function <function get at 0x7f027bfbacf8>. Response was <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by kzzzzo2** [comment]
I also experienced the same error.

My environment was webargs == 5.0.0, but it was solved by downgrading to 4.4.1.

```
pip install webargs == 4.4.1
```

**Comment by njdonarski** [comment]
That resolved my issue, thanks!

**Comment by llazzaro** [comment]
This will be fixed in the next release. 
Webargs is breaking with python2
