### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by nil0x42** [infobyte/faraday#345]
## Issue Type
 - Bug Report

When starting faraday (with /usr/bin/python-faraday from kali package), i get this output on terminal:
`$ python-faraday`
```

  _____                           .___
_/ ____\_____  ____________     __| _/_____   ___.__.
\   __\ \__  \ \_  __ \__  \   / __ | \__  \ <   |  |
 |  |    / __ \_|  | \// __ \_/ /_/ |  / __ \_\___  |
 |__|   (____  /|__|  (____  /\____ | (____  // ____|
             \/            \/      \/      \/ \/
    
[*[       Open Source Penetration Test IDE       ]*]
            Where pwnage goes multiplayer

2019-02-22 21:31:38,133 - faraday.launcher - INFO [faraday.py:408 -          printBanner() ]  Starting Faraday IDE.
2019-02-22 21:31:38,133 - faraday.launcher - INFO [faraday.py:359 -   checkConfiguration() ]  Checking configuration.
2019-02-22 21:31:38,133 - faraday.launcher - INFO [faraday.py:360 -   checkConfiguration() ]  Setting up plugins.
2019-02-22 21:31:38,133 - faraday.launcher - INFO [faraday.py:294 -         setupPlugins() ]  Removing old plugins folder.
2019-02-22 21:31:38,159 - faraday.launcher - INFO [faraday.py:362 -   checkConfiguration() ]  Setting up ZSH integration.
2019-02-22 21:31:38,159 - faraday.launcher - INFO [faraday.py:364 -   checkConfiguration() ]  Setting up user configuration.
2019-02-22 21:31:38,159 - faraday.launcher - INFO [faraday.py:339 -       setupXMLConfig() ]  Using custom user configuration.
2019-02-22 21:31:38,159 - faraday.launcher - INFO [faraday.py:366 -   checkConfiguration() ]  Setting up icons for GTK interface.
2019-02-22 21:31:38,163 - faraday.launcher - INFO [faraday.py:218 -              setConf() ]  Setting configuration.
2019-02-22 21:31:38,271 - faraday.launcher - INFO [faraday.py:248 -         startFaraday() ]  All done. Opening environment.
2019-02-22 21:31:38,415 - faraday.launcher - INFO [faraday.py:254 -         startFaraday() ]  Main application ExceptHook enabled.
2019-02-22 21:31:38,415 - faraday.launcher - INFO [faraday.py:257 -         startFaraday() ]  Starting main application.

* Faraday UI is ready
Point your browser to: 
[http://localhost:5985/_ui]

2019-02-22 21:31:38,416 - faraday - INFO [api.py:118 -      _setUpAPIServer() ]  XMLRPC API server configured on ('localhost', 9876)
2019-02-22 21:31:38,423 - faraday - INFO [api.py:66 -            startAPIs() ]  REST API server configured on ('localhost', 9977)
2019-02-22 21:31:38,493 - faraday.Server-GTK IO - WARNING [decorators.py:23 -              wrapper() ]  You're not authorized to make this request. The answer from the server was <Response [401]>. Please check that your domain is the correct one and run Faraday GTK with option --login
```

and this stack trace in a window popup:
```py
    Exception: 
    Traceback: Traceback (most recent call last):
  File "/usr/share/python-faraday/gui/gtk/application.py", line 777, in do_activate
    if not is_authenticated(CONF.getServerURI(), CONF.getDBSessionCookies()):
  File "/usr/share/python-faraday/persistence/server/server.py", line 1542, in is_authenticated
    user_info = resp.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Also, the credentials that were valid in the past don't work anymore on webserver login.

I didn't use faraday for ~ 3 months, so it might be related to a package update from kali.

**Comment by llazzaro** [comment]
Hi!
Can you execute:

> python manage.py status

You could also use:

python manage.py support

To generate a zip file with debug information. Make sure you can send us the generated zip file.

Thanks!

**Comment by nil0x42** [comment]
Hi, i uninstalled python-faraday kali package, and cloned the latest version, i worked fine.

So i'm closing the issue
Thank you
