### ISSUE TITLE
WPScan vulnerabilities are not reported to Faraday Server

### ISSUE THREAD

**Issue by asdex22** [infobyte/faraday#375]

**Comment by llazzaro** [comment]
Hi,
We think that the stdout of the wpscan has changed and the plugin is not supporting the latest version.
Could you tell us the version of wpscan?
Can you retry using the --debug flag on the faraday-client?
Thanks!

**Comment by elenasarim** [comment]
Hello,

The WPScan version is 3.7.3.

The debug logs while running WPScan are depicted below:


```
2019-11-05 12:53:01,802 - faraday.client.start_client - INFO {MainThread} [start_client.py:408 - printBanner()]  Starting Faraday IDE.
2019-11-05 12:53:01,802 - faraday.client.start_client - INFO {MainThread} [start_client.py:359 - checkConfiguration()]  Checking configuration.
2019-11-05 12:53:01,802 - faraday.client.start_client - INFO {MainThread} [start_client.py:360 - checkConfiguration()]  Setting up plugins.
2019-11-05 12:53:01,802 - faraday.client.start_client - INFO {MainThread} [start_client.py:298 - setupPlugins()]  Removing old plugins folder.
2019-11-05 12:53:01,816 - faraday.client.start_client - INFO {MainThread} [start_client.py:362 - checkConfiguration()]  Setting up ZSH integration.
2019-11-05 12:53:01,817 - faraday.client.start_client - INFO {MainThread} [start_client.py:364 - checkConfiguration()]  Setting up user configuration.
2019-11-05 12:53:01,817 - faraday.client.start_client - INFO {MainThread} [start_client.py:339 - setupXMLConfig()]  Using custom user configuration.
2019-11-05 12:53:01,817 - faraday.client.start_client - INFO {MainThread} [start_client.py:366 - checkConfiguration()]  Setting up icons for GTK interface.
2019-11-05 12:53:01,820 - faraday.client.start_client - INFO {MainThread} [start_client.py:220 - setConf()]  Setting configuration.
2019-11-05 12:53:02,501 - faraday.client.start_client - INFO {MainThread} [start_client.py:530 - login()]  Login successful: faraday
2019-11-05 12:53:02,980 - faraday.client.start_client - INFO {MainThread} [start_client.py:429 - checkUpdates()]  You have available updates. Run ./faraday.py --update to catchup!
2019-11-05 12:53:03,095 - faraday.client.start_client - INFO {MainThread} [start_client.py:252 - startFaraday()]  All done. Opening environment.
2019-11-05 12:53:03,096 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin netcat
2019-11-05 12:53:03,097 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin webfuzzer
2019-11-05 12:53:03,098 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dnsenum
2019-11-05 12:53:03,099 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin hping3
2019-11-05 12:53:03,100 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin wpscan
2019-11-05 12:53:03,100 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin ndiff
2019-11-05 12:53:03,101 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin peepingtom
/opt/faraday-client/lib/python2.7/site-packages/psycopg2-2.7.7-py2.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
2019-11-05 12:53:03,106 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin metasploiton
2019-11-05 12:53:03,108 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin lynis
2019-11-05 12:53:03,115 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin sslyze
2019-11-05 12:53:03,161 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin netsparker
2019-11-05 12:53:03,161 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin traceroute
2019-11-05 12:53:03,163 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin wapiti
2019-11-05 12:53:03,163 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin theharvester
2019-11-05 12:53:03,164 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin propecia
2019-11-05 12:53:03,165 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin nexpose-full
2019-11-05 12:53:03,166 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin fierce
2019-11-05 12:53:03,167 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin masscan
2019-11-05 12:53:03,167 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin netdiscover
2019-11-05 12:53:03,168 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dig
2019-11-05 12:53:03,172 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin fortify
2019-11-05 12:53:03,176 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin sqlmap
2019-11-05 12:53:03,177 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin goohost
2019-11-05 12:53:03,179 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin medusa
2019-11-05 12:53:03,180 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin nikto
2019-11-05 12:53:03,181 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dnswalk
2019-11-05 12:53:03,182 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin sslcheck
2019-11-05 12:53:03,183 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin xsssniper
2019-11-05 12:53:03,183 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin metagoofil
2019-11-05 12:53:03,184 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin burp
2019-11-05 12:53:03,185 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin wcscan
2019-11-05 12:53:03,185 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin pasteanalyzer
2019-11-05 12:53:03,186 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin whois
2019-11-05 12:53:03,186 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin nmap
2019-11-05 12:53:03,187 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin ping
2019-11-05 12:53:03,188 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dirsearch
2019-11-05 12:53:03,189 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin w3af
2019-11-05 12:53:03,190 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin sublist3r
2019-11-05 12:53:03,190 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin reverseraider
2019-11-05 12:53:03,191 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin skipfish
2019-11-05 12:53:03,192 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin appscan
2019-11-05 12:53:03,193 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin beef
2019-11-05 12:53:03,194 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin impact
2019-11-05 12:53:03,195 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin acunetix
2019-11-05 12:53:03,196 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin hydra
2019-11-05 12:53:03,197 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dnsrecon
2019-11-05 12:53:03,197 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin ftp
2019-11-05 12:53:03,198 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin ip360
2019-11-05 12:53:03,199 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin wfuzz
2019-11-05 12:53:03,200 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin maltego
2019-11-05 12:53:03,201 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin listurl
2019-11-05 12:53:03,201 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dirb
2019-11-05 12:53:03,202 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin arp-scan
2019-11-05 12:53:03,202 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin telnet
2019-11-05 12:53:03,204 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin netsparkercloud
2019-11-05 12:53:03,206 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin arachni
2019-11-05 12:53:03,207 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin qualysguard
2019-11-05 12:53:03,209 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin openvas
2019-11-05 12:53:03,210 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin retina
2019-11-05 12:53:03,211 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin brutexss
2019-11-05 12:53:03,211 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dnsmap
2019-11-05 12:53:03,212 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin junit
2019-11-05 12:53:03,213 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin fruitywifi
2019-11-05 12:53:03,213 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin reconng
2019-11-05 12:53:03,215 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin zap
2019-11-05 12:53:03,216 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin amap
2019-11-05 12:53:03,221 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin nessus
2019-11-05 12:53:03,222 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin x1
2019-11-05 12:53:03,222 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin sshdefaultscan
2019-11-05 12:53:03,224 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin metasploit
2019-11-05 12:53:03,300 - faraday.client.start_client - INFO {MainThread} [start_client.py:258 - startFaraday()]  Main application ExceptHook enabled.
2019-11-05 12:53:03,300 - faraday.client.start_client - INFO {MainThread} [start_client.py:261 - startFaraday()]  Starting main application.

* Faraday UI is ready
Point your browser to: 
[http://localhost:5985/_ui]

2019-11-05 12:53:03,300 - faraday.client.model.api - DEBUG {MainThread} [api.py:495 - devlog()]  Starting application...
2019-11-05 12:53:03,300 - faraday.client.model.api - DEBUG {MainThread} [api.py:495 - devlog()]  Setting up remote API's...
2019-11-05 12:53:03,301 - faraday.client.model.api - DEBUG {MainThread} [api.py:495 - devlog()]  starting XMLRPCServer with api_conn_info = ('localhost', 9876)
2019-11-05 12:53:03,302 - faraday.client.model.api - INFO {MainThread} [api.py:117 - _setUpAPIServer()]  XMLRPC API server configured on ('localhost', 9876)
2019-11-05 12:53:03,302 - faraday.client.model.api - DEBUG {MainThread} [api.py:495 - devlog()]  Starting model controller daemon...
2019-11-05 12:53:03,302 - faraday.client.model.api - DEBUG {MainThread} [api.py:495 - devlog()]  starting xmlrpc api server...
2019-11-05 12:53:03,317 - faraday.client.apis.rest.api - INFO {MainThread} [api.py:65 - startAPIs()]  REST API server configured on ('localhost', 9977)
2019-11-05 12:53:03,323 - faraday.client.model.api - DEBUG {MainThread} [api.py:495 - devlog()]  Faraday ready...
2019-11-05 12:53:08,540 - faraday.server - INFO {Thread-3} [__init__.py:41 - run()]  License status OK
2019-11-05 12:53:49,836 - faraday.client.plugins.controller - DEBUG {Thread-5} [controller.py:174 - processOutput()]  Created plugin_process (140022983958288) for plugin instance (140022984357072)
2019-11-05 12:53:49,837 - faraday.client.model.api - DEBUG {Thread-12} [api.py:495 - devlog()]  ----------------------------------------
2019-11-05 12:53:49,839 - faraday.client.model.api - DEBUG {Thread-12} [api.py:495 - devlog()]  proc_name = Thread-12
2019-11-05 12:53:49,839 - faraday.client.model.api - DEBUG {Thread-12} [api.py:495 - devlog()]  Starting run method on PluginProcess
2019-11-05 12:53:49,839 - faraday.client.model.api - DEBUG {Thread-12} [api.py:495 - devlog()]  parent process: 7084
2019-11-05 12:53:49,840 - faraday.client.model.api - DEBUG {Thread-12} [api.py:495 - devlog()]  process id: 7088
2019-11-05 12:53:49,840 - faraday.client.model.api - DEBUG {Thread-12} [api.py:495 - devlog()]  ----------------------------------------
2019-11-05 12:53:49,840 - faraday.client.model.api - DEBUG {Thread-12} [api.py:495 - devlog()]  Thread-12: New Output
2019-11-05 12:53:49,843 - faraday.client.plugins.plugin - DEBUG {Thread-12} [plugin.py:173 - __addPendingAction()]  AddPendingAction (2000, <faraday.client.persistence.server.models.Host object at 0x7f59a4389e50>, 24)
2019-11-05 12:53:49,871 - faraday.client.model.api - DEBUG {Thread-1} [api.py:495 - devlog()]  _processAction - 3000 - parameters = ['wpscan', 24]
2019-11-05 12:53:49,872 - faraday.client.model.controller - INFO {Thread-1} [controller.py:427 - _pluginStart()]  Plugin Started: wpscan. 
2019-11-05 12:53:49,873 - faraday.client.model.api - DEBUG {Thread-1} [api.py:495 - devlog()]  _processAction - 2000 - parameters = [<faraday.client.persistence.server.models.Host object at 0x7f59a4389e50>, 24]
2019-11-05 12:53:49,961 - faraday.client.plugins.plugin - DEBUG {Thread-12} [plugin.py:173 - __addPendingAction()]  AddPendingAction (20008, <faraday.client.persistence.server.models.Service object at 0x7f59a4389e50>, 24)
2019-11-05 12:53:49,978 - faraday.client.model.api - DEBUG {Thread-1} [api.py:495 - devlog()]  _processAction - 20008 - parameters = [<faraday.client.persistence.server.models.Service object at 0x7f59a4389e50>, 24]
2019-11-05 12:53:50,077 - faraday.client.model.api - DEBUG {Thread-12} [api.py:495 - devlog()]  Plugin raised an exception:
2019-11-05 12:53:50,077 - faraday.client.model.api - DEBUG {Thread-12} [api.py:495 - devlog()]  Traceback (most recent call last):
  File "/opt/faraday-client/lib/python2.7/site-packages/faradaysec-3.9.2-py2.7.egg/faraday/client/plugins/plugin.py", line 416, in run
    self.plugin.processOutput(output)
  File "/opt/faraday-client/lib/python2.7/site-packages/faradaysec-3.9.2-py2.7.egg/faraday/client/plugins/plugin.py", line 134, in processOutput
    self.parseOutputString(output)
  File "/root/.faraday/plugins/wpscan/plugin.py", line 202, in parseOutputString
    base_url)
  File "/root/.faraday/plugins/wpscan/plugin.py", line 138, in addWPVulns
    with open(db_file_path, "r") as data:
TypeError: coercing to Unicode: need string or buffer, NoneType found

2019-11-05 12:53:50,077 - faraday.client.plugins.controller - DEBUG {Thread-13} [controller.py:55 - commit()]  Plugin end. Commiting to faraday server.
2019-11-05 12:53:50,094 - faraday.client.model.api - DEBUG {Thread-1} [api.py:495 - devlog()]  _processAction - 3001 - parameters = ['wpscan', 24]
2019-11-05 12:53:50,094 - faraday.client.model.controller - INFO {Thread-1} [controller.py:435 - _pluginEnd()]  Plugin Ended: wpscan
```

**Comment by geosphere** [comment]
Some issue with WPScan v. 3.7.5

**Comment by llazzaro** [comment]
Can you try to output a json with wpscan and then upload it from the webui?
