### ISSUE TITLE
Error in Netsparker Plugin

### ISSUE THREAD

**Issue by h0nus** [infobyte/faraday#380]
Please search the [Wiki](https://github.com/infobyte/faraday/wiki) for a solution before posting a ticket. Use the <strong>“New Support Request”</strong> button to the right of the screen to submit a ticket for technical support.

## Issue Type
 - Bug Report

## Faraday version
3.10.0 (downloaded .deb client version from releases)

## Component Name
Netsparker Plugin

## Steps to reproduce
From Netsparker:
 - Export Vuln list detailed|normal list.
 - Import from Faraday cli (`faraday-client --cli --workspace XXXX --report /home/xx/xxxx.xml`)
 - Wait, but no data appears/is imported (**with normal XML export, only HOST is imported**)

## Expected results
That Faraday imports vulnerabilities into his database and make me visualize them.

### Debugging tracebacks (current results)
```
2020-01-02 15:29:13,102 - faraday.client.start_client - INFO {MainThread} [start_client.py:416 - printBanner()]  Starting Faraday IDE.
2020-01-02 15:29:13,103 - faraday.client.start_client - INFO {MainThread} [start_client.py:368 - checkConfiguration()]  Checking configuration.
2020-01-02 15:29:13,104 - faraday.client.start_client - INFO {MainThread} [start_client.py:369 - checkConfiguration()]  Setting up plugins.
2020-01-02 15:29:13,105 - faraday.client.start_client - INFO {MainThread} [start_client.py:307 - setupPlugins()]  Removing old plugins folder.
2020-01-02 15:29:13,240 - faraday.client.start_client - INFO {MainThread} [start_client.py:371 - checkConfiguration()]  Setting up ZSH integration.
2020-01-02 15:29:13,243 - faraday.client.start_client - INFO {MainThread} [start_client.py:373 - checkConfiguration()]  Setting up user configuration.
2020-01-02 15:29:13,245 - faraday.client.start_client - INFO {MainThread} [start_client.py:348 - setupXMLConfig()]  Using custom user configuration.
2020-01-02 15:29:13,245 - faraday.client.start_client - INFO {MainThread} [start_client.py:375 - checkConfiguration()]  Setting up icons for GTK interface.
2020-01-02 15:29:13,266 - faraday.client.start_client - INFO {MainThread} [start_client.py:230 - setConf()]  Setting configuration.
2020-01-02 15:29:14,740 - faraday.client.start_client - INFO {MainThread} [start_client.py:537 - login()]  Login successful: faraday
2020-01-02 15:29:20,417 - faraday.client.start_client - INFO {MainThread} [start_client.py:436 - checkUpdates()]  You have available updates. Run ./faraday.py --update to catchup!
2020-01-02 15:29:21,687 - faraday.client.start_client - INFO {MainThread} [start_client.py:262 - startFaraday()]  All done. Opening environment.
2020-01-02 15:29:21,693 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin metasploit
2020-01-02 15:29:21,695 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin wapiti
2020-01-02 15:29:21,696 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin maltego
2020-01-02 15:29:21,699 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin hydra
2020-01-02 15:29:21,700 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin reverseraider
2020-01-02 15:29:21,701 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin listurl
2020-01-02 15:29:21,702 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin propecia
2020-01-02 15:29:21,703 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin netcat
2020-01-02 15:29:21,704 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin fruitywifi
2020-01-02 15:29:21,754 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin reconng
2020-01-02 15:29:22,179 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin netsparker
2020-01-02 15:29:22,181 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin impact
2020-01-02 15:29:22,201 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin metasploiton
2020-01-02 15:29:22,203 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin nexpose-full
2020-01-02 15:29:22,205 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin dnswalk
2020-01-02 15:29:22,206 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin dig
2020-01-02 15:29:22,208 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin sslcheck
2020-01-02 15:29:22,209 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin goohost
2020-01-02 15:29:22,223 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin dirsearch
2020-01-02 15:29:22,225 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin sshdefaultscan
2020-01-02 15:29:22,226 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin acunetix
2020-01-02 15:29:22,229 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin lynis
2020-01-02 15:29:22,231 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin retina
2020-01-02 15:29:22,233 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin dnsenum
2020-01-02 15:29:22,234 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin peepingtom
2020-01-02 15:29:22,237 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin masscan
2020-01-02 15:29:22,239 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin ping
2020-01-02 15:29:22,240 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin hping3
2020-01-02 15:29:22,242 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin junit
2020-01-02 15:29:22,259 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin appscan
2020-01-02 15:29:22,262 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin wpscan
2020-01-02 15:29:22,264 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin wcscan
2020-01-02 15:29:22,266 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin qualysguard
2020-01-02 15:29:22,267 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin netdiscover
2020-01-02 15:29:22,269 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin ndiff
2020-01-02 15:29:22,270 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin dnsmap
2020-01-02 15:29:22,272 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin skipfish
2020-01-02 15:29:22,293 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin nessus
2020-01-02 15:29:22,340 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin fortify
2020-01-02 15:29:22,341 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin w3af
2020-01-02 15:29:22,343 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin dnsrecon
2020-01-02 15:29:22,344 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin beef
2020-01-02 15:29:22,345 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin traceroute
2020-01-02 15:29:22,347 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin sublist3r
2020-01-02 15:29:22,349 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin zap
2020-01-02 15:29:22,350 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin sslyze
2020-01-02 15:29:22,351 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin xsssniper
2020-01-02 15:29:22,352 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin netsparkercloud
2020-01-02 15:29:22,358 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin sqlmap
2020-01-02 15:29:22,360 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin nmap
2020-01-02 15:29:22,361 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin metagoofil
2020-01-02 15:29:22,362 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin webfuzzer
2020-01-02 15:29:22,364 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin x1
2020-01-02 15:29:22,365 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin fierce
2020-01-02 15:29:22,367 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin arachni
2020-01-02 15:29:22,369 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin nikto
2020-01-02 15:29:22,370 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin brutexss
2020-01-02 15:29:22,372 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin ftp
2020-01-02 15:29:22,374 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin medusa
2020-01-02 15:29:22,375 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin openvas
2020-01-02 15:29:22,376 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin dirb
2020-01-02 15:29:22,392 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin burp
2020-01-02 15:29:22,393 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin theharvester
2020-01-02 15:29:22,397 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin amap
2020-01-02 15:29:22,399 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin whois
2020-01-02 15:29:22,400 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin wfuzz
2020-01-02 15:29:22,403 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin ip360
2020-01-02 15:29:22,404 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin pasteanalyzer
2020-01-02 15:29:22,405 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin telnet
2020-01-02 15:29:22,406 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:116 - _loadPlugins()]  Loading plugin arp-scan
2020-01-02 15:29:22,479 - faraday.client.start_client - INFO {MainThread} [start_client.py:268 - startFaraday()]  Main application ExceptHook enabled.
2020-01-02 15:29:22,480 - faraday.client.start_client - INFO {MainThread} [start_client.py:271 - startFaraday()]  Starting main application.

* Faraday UI is ready
Point your browser to:
[http://192.168.1.239:5985/_ui]

2020-01-02 15:29:22,480 - faraday.client.model.api - DEBUG {MainThread} [api.py:496 - devlog()]  Starting application...
2020-01-02 15:29:22,482 - faraday.client.model.api - DEBUG {MainThread} [api.py:496 - devlog()]  Setting up remote API's...
2020-01-02 15:29:22,482 - faraday.client.model.api - DEBUG {MainThread} [api.py:496 - devlog()]  starting XMLRPCServer with api_conn_info = ('127.0.0.1', 9876)
2020-01-02 15:29:22,486 - faraday.client.model.api - INFO {MainThread} [api.py:118 - _setUpAPIServer()]  XMLRPC API server configured on ('127.0.0.1', 9876)
2020-01-02 15:29:22,486 - faraday.client.model.api - DEBUG {MainThread} [api.py:496 - devlog()]  Starting model controller daemon...
2020-01-02 15:29:22,487 - faraday.client.model.api - DEBUG {MainThread} [api.py:496 - devlog()]  starting xmlrpc api server...
2020-01-02 15:29:22,528 - faraday.client.apis.rest.api - INFO {MainThread} [api.py:68 - startAPIs()]  REST API server configured on ('127.0.0.1', 9977)
2020-01-02 15:29:22,558 - faraday.client.model.api - DEBUG {MainThread} [api.py:496 - devlog()]  Faraday ready...
2020-01-02 15:29:22,698 - faraday.client.managers.reports_managers - DEBUG {MainThread} [reports_managers.py:89 - processReport()]  Report file is /home/vagrant/netsparker-report-detailed-wwwyves.xml
2020-01-02 15:29:22,702 - faraday.client.managers.reports_managers - DEBUG {MainThread} [reports_managers.py:235 - _get_plugin_by_name()]  Could not extract plugin_id from filename: netsparker-report-detailed-wwwyves.xml
2020-01-02 15:29:22,703 - faraday.client.managers.reports_managers - DEBUG {MainThread} [reports_managers.py:188 - get_plugin_id()]  Plugin by name not found
2020-01-02 15:29:22,704 - faraday.client.managers.reports_managers - DEBUG {MainThread} [reports_managers.py:200 - _get_plugin_by_file_type()]  Analyze report File
2020-01-02 15:29:22,707 - faraday.client.managers.reports_managers - DEBUG {MainThread} [reports_managers.py:211 - _get_plugin_by_file_type()]  Found XML content on file: /home/vagrant/netsparker-report-detailed-wwwyves.xml - Main tag: netsparker
2020-01-02 15:29:22,708 - faraday.client.plugins.plugin.MetasploitPlugin - DEBUG {MainThread} [plugin.py:401 - report_belongs_to()]  Extension Match: [.xml =/in .xml] -> True
2020-01-02 15:29:22,708 - faraday.client.plugins.plugin.MetasploitPlugin - DEBUG {MainThread} [plugin.py:419 - report_belongs_to()]  Tag Match: [netsparker =/in ['MetasploitV4', 'MetasploitV5']] -> False      2020-01-02 15:29:22,709 - faraday.client.plugins.plugin.WapitiPlugin - DEBUG {MainThread} [plugin.py:401 - report_belongs_to()]  Extension Match: [.xml =/in .xml] -> True
2020-01-02 15:29:22,709 - faraday.client.plugins.plugin.WapitiPlugin - DEBUG {MainThread} [plugin.py:419 - report_belongs_to()]  Tag Match: [netsparker =/in report] -> False
2020-01-02 15:29:22,710 - faraday.client.plugins.plugin.MaltegoPlugin - DEBUG {MainThread} [plugin.py:401 - report_belongs_to()]  Extension Match: [.xml =/in .xml] -> True
2020-01-02 15:29:22,711 - faraday.client.plugins.plugin.MaltegoPlugin - DEBUG {MainThread} [plugin.py:419 - report_belongs_to()]  Tag Match: [netsparker =/in maltego] -> False
2020-01-02 15:29:22,711 - faraday.client.plugins.plugin.ReconngPlugin - DEBUG {MainThread} [plugin.py:401 - report_belongs_to()]  Extension Match: [.xml =/in .xml] -> True
2020-01-02 15:29:22,712 - faraday.client.plugins.plugin.ReconngPlugin - DEBUG {MainThread} [plugin.py:419 - report_belongs_to()]  Tag Match: [netsparker =/in reconng] -> False
2020-01-02 15:29:22,714 - faraday.client.plugins.plugin.NetsparkerPlugin - DEBUG {MainThread} [plugin.py:401 - report_belongs_to()]  Extension Match: [.xml =/in .xml] -> True
2020-01-02 15:29:22,714 - faraday.client.plugins.plugin.NetsparkerPlugin - DEBUG {MainThread} [plugin.py:419 - report_belongs_to()]  Tag Match: [netsparker =/in netsparker] -> True
2020-01-02 15:29:22,715 - faraday.client.managers.reports_managers - INFO {MainThread} [reports_managers.py:99 - sendReport()]  The file is /home/vagrant/netsparker-report-detailed-wwwyves.xml, netsparker     2020-01-02 15:29:22,828 - faraday.client.plugins.controller - INFO {MainThread} [controller.py:294 - processReport()]  Processing report with plugin netsparker
2020-01-02 15:29:22,863 - faraday.client.plugins.controller - INFO {MainThread} [controller.py:173 - processOutput()]  Created plugin_process (140429245420496) for plugin instance (140429247379600)
2020-01-02 15:29:22,865 - faraday.client.model.api - DEBUG {ModelControllerThread} [api.py:496 - devlog()]  _processAction - 3000 - parameters = ['Netsparker', 5]
2020-01-02 15:29:22,865 - faraday.client.model.controller - INFO {ModelControllerThread} [controller.py:429 - _pluginStart()]  Plugin Started: Netsparker.
2020-01-02 15:29:22,868 - faraday.client.model.api - DEBUG {PluginProcessThread} [api.py:496 - devlog()]  ----------------------------------------
2020-01-02 15:29:22,869 - faraday.client.model.api - INFO {MainThread} [api.py:490 - log()]  Closing Faraday...
2020-01-02 15:29:22,871 - faraday.client.model.api - DEBUG {PluginProcessThread} [api.py:496 - devlog()]  proc_name = PluginProcessThread
2020-01-02 15:29:22,871 - faraday.client.model.api - DEBUG {MainThread} [api.py:496 - devlog()]  stopping model controller thread...
2020-01-02 15:29:22,874 - faraday.client.model.api - DEBUG {PluginProcessThread} [api.py:496 - devlog()]  Starting run method on PluginProcess
2020-01-02 15:29:22,874 - faraday.client.model.api - DEBUG {MainThread} [api.py:496 - devlog()]  server stopping...
2020-01-02 15:29:22,875 - faraday.client.model.api - DEBUG {PluginProcessThread} [api.py:496 - devlog()]  parent process: 2520
2020-01-02 15:29:22,875 - faraday.client.model.api - DEBUG {MainThread} [api.py:496 - devlog()]  called stop on xmlrpc server
2020-01-02 15:29:22,876 - faraday.client.model.api - DEBUG {PluginProcessThread} [api.py:496 - devlog()]  process id: 2573
2020-01-02 15:29:22,876 - faraday.client.model.api - DEBUG {PluginProcessThread} [api.py:496 - devlog()]  ----------------------------------------
2020-01-02 15:29:22,877 - faraday.client.model.api - DEBUG {PluginProcessThread} [api.py:496 - devlog()]  PluginProcessThread: New Output
2020-01-02 15:29:22,896 - faraday.client.model.api - DEBUG {PluginProcessThread} [api.py:496 - devlog()]  Plugin raised an exception:
2020-01-02 15:29:22,898 - faraday.client.model.api - DEBUG {PluginProcessThread} [api.py:496 - devlog()]  Traceback (most recent call last):
  File "/opt/faraday/lib/python3.7/site-packages/faradaysec-3.10.0-py3.7.egg/faraday/client/plugins/plugin.py", line 470, in run
    self.plugin.processOutput(output)
  File "/opt/faraday/lib/python3.7/site-packages/faradaysec-3.10.0-py3.7.egg/faraday/client/plugins/plugin.py", line 130, in processOutput
    self.parseOutputString(output)
  File "/home/vagrant/.faraday/plugins/netsparker/plugin.py", line 219, in parseOutputString
    parser = NetsparkerXmlParser(output)
  File "/home/vagrant/.faraday/plugins/netsparker/plugin.py", line 54, in __init__
    self.items = list(self.get_items(tree))
  File "/home/vagrant/.faraday/plugins/netsparker/plugin.py", line 80, in get_items
    yield Item(node)
  File "/home/vagrant/.faraday/plugins/netsparker/plugin.py", line 139, in __init__
    self.extra.append(v.get('name') + ":" + v.text)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

2020-01-02 15:29:22,900 - faraday.client.plugins.controller - INFO {PluginCommiterThread} [controller.py:58 - commit()]  Plugin end. Commiting to faraday server.
2020-01-02 15:29:22,907 - faraday.client.model.api - DEBUG {ModelControllerThread} [api.py:496 - devlog()]  _processAction - 3001 - parameters = ['Netsparker', 5]
2020-01-02 15:29:22,907 - faraday.client.model.controller - INFO {ModelControllerThread} [controller.py:437 - _pluginEnd()]  Plugin Ended: Netsparker
2020-01-02 15:29:24,489 - faraday.client.model.api - DEBUG {Thread-1} [api.py:496 - devlog()]  server forever stopped by flag
2020-01-02 15:29:24,489 - faraday.client.model.api - DEBUG {Thread-1} [api.py:496 - devlog()]  serve_forever ended
2020-01-02 15:29:24,490 - faraday.client.model.api - DEBUG {MainThread} [api.py:496 - devlog()]  xmlrpc thread joined
2020-01-02 15:29:24,909 - faraday.client.model.api - DEBUG {MainThread} [api.py:496 - devlog()]  Waiting for controller threads to end...
2020-01-02 15:29:27,848 - faraday.server - INFO {TimerClassThread} [__init__.py:28 - run()]  License status OK
```
## Environment information

Just a ubuntu vagrant machine with only faraday-client installed from dpkg (releases version)

### Configuration files

Nothing. I was only doing this from pc to remote (in same LAN) server with Faraday server running (.deb version from releases, v. 3.10.0)

### Reports/Extra data

Nothing to add

### OS

Provide information on your operating system. Example:

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.04
DISTRIB_CODENAME=disco
DISTRIB_DESCRIPTION="Ubuntu 19.04"

**Comment by llazzaro** [comment]
Hi,

We are going to release a hotfix in the next days to fix this issue.

Thanks for reporting this issue.

**Comment by h0nus** [comment]
Awesome!

**Comment by montive** [comment]
Hi there.

We've made some changes to the Netsparker Plugin. 
Please, update Faraday and try to import your report.

Let us know how it goes.

**Comment by h0nus** [comment]
Yes, i'll let you know!
thanks!

**Comment by h0nus** [comment]
Hi, actually I can't test due to issue #388 
If you'd like, i can send you a little report of Netsparker of testphp.vulnweb.com
Let me know!

**Comment by h0nus** [comment]
Hi, now that issue #388 has been fixed, i've tried to import a Netsparker scan and it works!
Thanks again!

**Comment by llazzaro** [comment]
Hi,
Great to hear that everything is working!
