### ISSUE TITLE
error in install  'pyasn1' 

### ISSUE THREAD

**Issue by meetgyn** [infobyte/faraday#384]
**I can't install faraday. This error returns to me. I already installed package pyasn1, pyasn1-modules and even so it still has an error. Can someone help me?**

(.venv) root@ubuntu:/opt/faraday-dev# faraday-manage initdb
Traceback (most recent call last):
  File "/opt/faraday-dev/.venv/bin/faraday-manage", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/faraday-dev/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in 

<module>
    @_call_aside
  File "/opt/faraday-dev/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/opt/faraday-dev/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/faraday-dev/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/opt/faraday-dev/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/faraday-dev/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
**pkg_resources.DistributionNotFound: The 'pyasn1' distribution was not found and is required by service-identity**

**Comment by cript0nauta** [comment]
Hi @meetgyn! Which version of Ubuntu are you using? Could you paste the output of running `/opt/faraday-dev/.venv/bin/pip freeze`?

Also, if you're trying to use Faraday as a user (not in development mode), we suggest you to try the Faraday Server `.deb` files we uploaded in the releases page: https://github.com/infobyte/faraday/releases. This has the advantage of installing the application with the proper user and with its own systemd service (`faraday-server`) so it is easier to run the server.

**Comment by montive** [comment]
Hi.

Any news here?

**Comment by Yashvendra** [comment]
Hi All,

Any updates here.
I'm also getting the same error on the latest Kali 2020 release.

**Comment by llazzaro** [comment]
Hi @Yashvendra @meetgyn,
We have a temporary solution to this problem in #399. We are going to publish updates about this error with Kali Linux.
If you have any problem feel free to comment in #399 .

Thanks!
