### ISSUE TITLE
AlienVault Openvas Plugin Request

### ISSUE THREAD

**Issue by ow111** [infobyte/faraday#385]
Currently trying to import vulnerability reports from Alienvault that uses Openvas, however running into a few issues. I have tried adding _faraday_openvas to the file name, converting the file to xml , importing as an excel worksheet however faraday isn't able to import (runs for 0.5 seconds then stops). Sometimes it registers the plugin to use for import as maltego when importing in different formats.

I believe the issue lies in the plugin for openvas - maybe the openvas version that alienvault use is different to what the plugin supports.
Current versions of OV used by AlienVault:
openvas manager 7.0.3
openvas scanner 5.1.3

I have attached an example file below
[Alienvault-Openvas Example.xlsx](https://github.com/infobyte/faraday/files/4244156/Alienvault-Openvas.Example.xlsx)

**Comment by montive** [comment]
Hi there.

Thanks for the report. Can you send us your server's logs? This way it would be easier for us to debug this issue.

Regards.

**Comment by ow111** [comment]
Hi, Sorry for the delay - here are the server logs.. It covers me trying to import in various ways - One error seen is missing package lxml (thought this would install through dependencies) . Let me know if that would be the root cause!
2020-02-20 15:12:45,817 - faraday.server.web - INFO {MainThread} [web.py:128 - __build_websockets_resource()]  Starting websocket server at port 9000 with bind address 0.0.0.0. SSL False
2020-02-20 15:12:45,820 - faraday.server.web - INFO {MainThread} [web.py:190 - run()]  Faraday Server is ready
2020-02-20 15:12:51,097 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-20 15:13:06,699 - faraday - INFO {MainThread} [start_server.py:47 - setup_environment()]  Checking dependencies...
2020-02-20 15:13:06,699 - faraday - INFO {MainThread} [start_server.py:50 - setup_environment()]  Some dependencies are old. Update them with "pip install -r requirements_server.txt -U"
2020-02-20 15:13:06,700 - faraday - INFO {MainThread} [start_server.py:52 - setup_environment()]  Dependencies met
2020-02-20 15:13:06,700 - faraday.server.web - INFO {MainThread} [web.py:80 - __init__()]  Starting web server at http://0.0.0.0:5985/
2020-02-20 15:13:06,703 - faraday.client.start_client - INFO {MainThread} [start_client.py:298 - setupPlugins()]  Removing old plugins folder.
2020-02-20 15:13:06,770 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin nmap
2020-02-20 15:13:06,771 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin pasteanalyzer
2020-02-20 15:13:06,771 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin traceroute
2020-02-20 15:13:06,787 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin appscan
2020-02-20 15:13:06,788 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin lynis
2020-02-20 15:13:06,790 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin sqlmap
2020-02-20 15:13:06,790 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin sshdefaultscan
2020-02-20 15:13:06,791 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin ftp
2020-02-20 15:13:06,791 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin sublist3r
2020-02-20 15:13:06,792 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin wcscan
2020-02-20 15:13:06,792 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin junit
2020-02-20 15:13:06,792 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin zap
2020-02-20 15:13:06,793 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin wfuzz
2020-02-20 15:13:06,793 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin netsparkercloud
2020-02-20 15:13:06,793 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin peepingtom
2020-02-20 15:13:06,794 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin metagoofil
2020-02-20 15:13:06,794 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin beef
2020-02-20 15:13:06,795 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin x1
2020-02-20 15:13:06,795 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin skipfish
2020-02-20 15:13:06,796 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin propecia
2020-02-20 15:13:06,796 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dig
2020-02-20 15:13:06,797 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin metasploit
2020-02-20 15:13:06,797 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin wapiti
2020-02-20 15:13:06,798 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin webfuzzer
2020-02-20 15:13:06,798 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin arachni
2020-02-20 15:13:06,798 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin openvas
2020-02-20 15:13:06,799 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin amap
2020-02-20 15:13:06,800 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin impact
2020-02-20 15:13:06,800 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin retina
2020-02-20 15:13:06,800 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin reconng
2020-02-20 15:13:06,801 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dirsearch
2020-02-20 15:13:06,801 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin medusa
2020-02-20 15:13:06,801 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin hping3
2020-02-20 15:13:06,802 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin netdiscover
2020-02-20 15:13:06,802 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin telnet
2020-02-20 15:13:06,802 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin metasploiton
2020-02-20 15:13:06,803 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin goohost
2020-02-20 15:13:06,803 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin fruitywifi
2020-02-20 15:13:06,803 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dirb
2020-02-20 15:13:06,804 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin qualysguard
2020-02-20 15:13:06,885 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin netsparker
2020-02-20 15:13:06,885 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin sslyze
2020-02-20 15:13:06,885 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin theharvester
2020-02-20 15:13:06,886 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin wpscan
2020-02-20 15:13:06,886 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin listurl
2020-02-20 15:13:06,887 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin masscan
2020-02-20 15:13:06,888 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin nexpose-full
2020-02-20 15:13:06,889 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin burp
2020-02-20 15:13:06,890 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin acunetix
2020-02-20 15:13:06,891 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dnswalk
2020-02-20 15:13:06,894 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin fortify
2020-02-20 15:13:06,894 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin maltego
2020-02-20 15:13:06,895 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin sslcheck
2020-02-20 15:13:06,896 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin w3af
2020-02-20 15:13:06,896 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin hydra
2020-02-20 15:13:06,897 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin xsssniper
2020-02-20 15:13:06,897 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin whois
2020-02-20 15:13:06,897 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dnsenum
2020-02-20 15:13:06,898 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin arp-scan
2020-02-20 15:13:06,898 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dnsrecon
2020-02-20 15:13:06,899 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin nikto
2020-02-20 15:13:06,899 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin netcat
2020-02-20 15:13:06,900 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin ping
2020-02-20 15:13:06,905 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin nessus
2020-02-20 15:13:06,906 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin ip360
2020-02-20 15:13:06,906 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin brutexss
2020-02-20 15:13:06,906 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin fierce
2020-02-20 15:13:06,907 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin ndiff
2020-02-20 15:13:06,907 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin reverseraider
2020-02-20 15:13:06,907 - faraday.client.plugins.manager - DEBUG {MainThread} [manager.py:120 - _loadPlugins()]  Loading plugin dnsmap
2020-02-20 15:13:06,935 - faraday.server.api.modules.upload_reports - INFO {Thread-1} [upload_reports.py:89 - run()]  Tool report processor started
2020-02-20 15:13:06,938 - faraday.server.web - INFO {MainThread} [web.py:128 - __build_websockets_resource()]  Starting websocket server at port 9000 with bind address 0.0.0.0. SSL False
2020-02-20 15:13:06,941 - faraday.server.web - INFO {MainThread} [web.py:190 - run()]  Faraday Server is ready
2020-02-20 15:13:12,174 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-20 15:13:43,609 - faraday.server.api.modules.upload_reports - DEBUG {PoolThread-twisted.internet.reactor-2} [upload_reports.py:130 - file_upload()]  Importing new plugin report in server...
2020-02-20 15:13:43,733 - faraday.server.api.modules.upload_reports - INFO {Thread-1} [upload_reports.py:94 - run()]  Processing raw report /root/.faraday/uploaded_reports/S2C0NFYUAMJSmyData1_faraday_openvas.xml
2020-02-20 15:13:43,733 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:90 - processReport()]  Report file is /root/.faraday/uploaded_reports/S2C0NFYUAMJSmyData1_faraday_openvas.xml
2020-02-20 15:13:43,733 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:302 - open_file()]  Report type detected: xml
2020-02-20 15:13:43,734 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:235 - __init__()]  Automatical detection FAILED... Trying manual...
2020-02-20 15:13:43,734 - faraday.client.managers.reports_managers - INFO {Thread-1} [reports_managers.py:106 - sendReport()]  The file is /root/.faraday/uploaded_reports/S2C0NFYUAMJSmyData1_faraday_openvas.xml, openvas
2020-02-20 15:13:44,713 - faraday.client.managers.reports_managers - ERROR {Thread-1} [reports_managers.py:114 - sendReport()]  Faraday doesn't have a plugin for this tool... Processing: ABORT
2020-02-20 15:14:12,476 - faraday.server.api.modules.upload_reports - DEBUG {PoolThread-twisted.internet.reactor-4} [upload_reports.py:130 - file_upload()]  Importing new plugin report in server...
2020-02-20 15:14:12,522 - faraday.server.api.modules.upload_reports - INFO {Thread-1} [upload_reports.py:94 - run()]  Processing raw report /root/.faraday/uploaded_reports/OJ88VADBVMT4ScanResult.csv
2020-02-20 15:14:12,522 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:90 - processReport()]  Report file is /root/.faraday/uploaded_reports/OJ88VADBVMT4ScanResult.csv
2020-02-20 15:14:12,523 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:302 - open_file()]  Report type detected: None
2020-02-20 15:14:12,523 - faraday.client.managers.reports_managers - ERROR {Thread-1} [reports_managers.py:339 - getRootTag()]  Not an xml file.
 syntax error: line 1, column 0
2020-02-20 15:14:12,523 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:235 - __init__()]  Automatical detection FAILED... Trying manual...
2020-02-20 15:14:12,523 - faraday.client.managers.reports_managers - ERROR {Thread-1} [reports_managers.py:97 - processReport()]  Plugin not found: automatic and manual try!
2020-02-20 15:14:33,421 - faraday.server.api.modules.upload_reports - DEBUG {PoolThread-twisted.internet.reactor-4} [upload_reports.py:130 - file_upload()]  Importing new plugin report in server...
2020-02-20 15:14:33,516 - faraday.server.api.modules.upload_reports - INFO {Thread-1} [upload_reports.py:94 - run()]  Processing raw report /root/.faraday/uploaded_reports/6O3UZ7UNS4KKData2_faraday_openvas.xml
2020-02-20 15:14:33,516 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:90 - processReport()]  Report file is /root/.faraday/uploaded_reports/6O3UZ7UNS4KKData2_faraday_openvas.xml
2020-02-20 15:14:33,516 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:302 - open_file()]  Report type detected: xml
2020-02-20 15:14:33,517 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:235 - __init__()]  Automatical detection FAILED... Trying manual...
2020-02-20 15:14:33,517 - faraday.client.managers.reports_managers - INFO {Thread-1} [reports_managers.py:106 - sendReport()]  The file is /root/.faraday/uploaded_reports/6O3UZ7UNS4KKData2_faraday_openvas.xml, openvas
2020-02-20 15:14:33,987 - faraday.client.managers.reports_managers - ERROR {Thread-1} [reports_managers.py:114 - sendReport()]  Faraday doesn't have a plugin for this tool... Processing: ABORT
2020-02-20 15:14:58,708 - faraday.server.api.modules.upload_reports - DEBUG {PoolThread-twisted.internet.reactor-4} [upload_reports.py:130 - file_upload()]  Importing new plugin report in server...
2020-02-20 15:14:58,805 - faraday.server.api.modules.upload_reports - INFO {Thread-1} [upload_reports.py:94 - run()]  Processing raw report /root/.faraday/uploaded_reports/2PO6RUUR87MLcwe_en.csv
2020-02-20 15:14:58,805 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:90 - processReport()]  Report file is /root/.faraday/uploaded_reports/2PO6RUUR87MLcwe_en.csv
2020-02-20 15:14:58,806 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:302 - open_file()]  Report type detected: None
2020-02-20 15:14:58,806 - faraday.client.managers.reports_managers - ERROR {Thread-1} [reports_managers.py:339 - getRootTag()]  Not an xml file.
 syntax error: line 1, column 0
2020-02-20 15:14:58,807 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:235 - __init__()]  Automatical detection FAILED... Trying manual...
2020-02-20 15:14:58,807 - faraday.client.managers.reports_managers - ERROR {Thread-1} [reports_managers.py:97 - processReport()]  Plugin not found: automatic and manual try!
2020-02-20 15:16:16,112 - faraday.server.api.modules.upload_reports - DEBUG {PoolThread-twisted.internet.reactor-1} [upload_reports.py:130 - file_upload()]  Importing new plugin report in server...
2020-02-20 15:16:16,204 - faraday.server.api.modules.upload_reports - INFO {Thread-1} [upload_reports.py:94 - run()]  Processing raw report /root/.faraday/uploaded_reports/OIZLTWTXZ207ScanResult.xlsx
2020-02-20 15:16:16,205 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:90 - processReport()]  Report file is /root/.faraday/uploaded_reports/OIZLTWTXZ207ScanResult.xlsx
2020-02-20 15:16:16,205 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:302 - open_file()]  Report type detected: zip
2020-02-20 15:16:16,205 - faraday.client.managers.reports_managers - INFO {Thread-1} [reports_managers.py:106 - sendReport()]  The file is /root/.faraday/uploaded_reports/OIZLTWTXZ207ScanResult.xlsx, Maltego
2020-02-20 15:16:16,371 - faraday.client.plugins.controller - INFO {Thread-1} [controller.py:296 - processReport()]  Processing report with plugin Maltego
2020-02-20 15:16:16,379 - faraday.client.plugins.controller - DEBUG {Thread-1} [controller.py:174 - processOutput()]  Created plugin_process (139921942840592) for plugin instance (139922378800976)
2020-02-20 15:16:16,391 - faraday.client.model.api - DEBUG {Thread-5} [api.py:495 - devlog()]  ----------------------------------------
2020-02-20 15:16:16,393 - faraday.client.model.api - DEBUG {Thread-5} [api.py:495 - devlog()]  proc_name = Thread-5
2020-02-20 15:16:16,396 - faraday.client.model.api - DEBUG {Thread-5} [api.py:495 - devlog()]  Starting run method on PluginProcess
2020-02-20 15:16:16,400 - faraday.client.model.api - DEBUG {Thread-5} [api.py:495 - devlog()]  parent process: 7169
2020-02-20 15:16:16,401 - faraday.client.model.api - DEBUG {Thread-2} [api.py:495 - devlog()]  _processAction - 3000 - parameters = ['Maltego', 14]
2020-02-20 15:16:16,405 - faraday.client.model.api - DEBUG {Thread-5} [api.py:495 - devlog()]  process id: 7170
2020-02-20 15:16:16,407 - faraday.client.model.controller - INFO {Thread-2} [controller.py:427 - _pluginStart()]  Plugin Started: Maltego.
2020-02-20 15:16:16,412 - faraday.client.model.api - DEBUG {Thread-5} [api.py:495 - devlog()]  ----------------------------------------
2020-02-20 15:16:16,416 - faraday.client.model.api - DEBUG {Thread-5} [api.py:495 - devlog()]  Thread-5: New Output
2020-02-20 15:16:16,421 - faraday.client.model.api - DEBUG {Thread-5} [api.py:495 - devlog()]  Plugin raised an exception:
2020-02-20 15:16:16,443 - faraday.client.model.api - DEBUG {Thread-5} [api.py:495 - devlog()]  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/faraday/client/plugins/plugin.py", line 416, in run
    self.plugin.processOutput(output)
  File "/usr/local/lib/python2.7/dist-packages/faraday/client/plugins/plugin.py", line 134, in processOutput
    self.parseOutputString(output)
  File "/root/.faraday/plugins/maltego/plugin.py", line 328, in parseOutputString
    maltego_parser = MaltegoMtgxParser(filename)
  File "/root/.faraday/plugins/maltego/plugin.py", line 72, in __init__
    self.nodes = self.xml.findall(
AttributeError: 'NoneType' object has no attribute 'findall'

2020-02-20 15:16:16,464 - faraday.client.plugins.controller - DEBUG {Thread-6} [controller.py:55 - commit()]  Plugin end. Commiting to faraday server.
2020-02-20 15:16:16,489 - faraday.client.model.api - DEBUG {Thread-2} [api.py:495 - devlog()]  _processAction - 3001 - parameters = ['Maltego', 14]
2020-02-20 15:16:16,492 - faraday.client.model.controller - INFO {Thread-2} [controller.py:435 - _pluginEnd()]  Plugin Ended: Maltego
2020-02-20 15:16:16,951 - faraday.server.api.modules.upload_reports - INFO {Thread-1} [upload_reports.py:109 - run()]  Report processing of report /root/.faraday/uploaded_reports/OIZLTWTXZ207ScanResult.xlsx finished
2020-02-20 15:16:36,041 - faraday.server.api.modules.upload_reports - DEBUG {PoolThread-twisted.internet.reactor-6} [upload_reports.py:130 - file_upload()]  Importing new plugin report in server...
2020-02-20 15:16:36,081 - faraday.server.api.modules.upload_reports - INFO {Thread-1} [upload_reports.py:94 - run()]  Processing raw report /root/.faraday/uploaded_reports/CMS9FHSZ5T4Sresults.nbe
2020-02-20 15:16:36,081 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:90 - processReport()]  Report file is /root/.faraday/uploaded_reports/CMS9FHSZ5T4Sresults.nbe
2020-02-20 15:16:36,081 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:302 - open_file()]  Report type detected: None
2020-02-20 15:16:36,082 - faraday.client.managers.reports_managers - ERROR {Thread-1} [reports_managers.py:339 - getRootTag()]  Not an xml file.
 syntax error: line 1, column 0
2020-02-20 15:16:36,082 - faraday.client.managers.reports_managers - DEBUG {Thread-1} [reports_managers.py:235 - __init__()]  Automatical detection FAILED... Trying manual...
2020-02-20 15:16:36,082 - faraday.client.managers.reports_managers - ERROR {Thread-1} [reports_managers.py:97 - processReport()]  Plugin not found: automatic and manual try!
2020-02-21 03:13:17,458 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-21 15:13:22,773 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-22 03:13:28,214 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-22 15:13:33,503 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-23 03:13:38,819 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-23 15:13:44,103 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-24 03:13:49,387 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-24 15:13:58,076 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-25 03:14:03,348 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-25 15:14:08,650 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-26 03:14:13,956 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-26 15:14:19,278 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-27 03:14:24,574 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-27 15:14:29,862 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status OK
2020-02-28 03:14:35,132 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-02-28 15:14:40,396 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-02-29 03:14:45,662 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-02-29 15:14:50,939 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-01 03:14:56,208 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-01 15:15:01,492 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-02 03:15:06,798 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-02 15:15:12,101 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-03 03:15:17,392 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-03 15:15:22,711 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-04 03:15:28,003 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-04 15:15:33,325 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-05 03:16:10,373 - faraday.server - ERROR {Thread-4} [__init__.py:43 - run()]  HTTPSConnectionPool(host='portal.faradaysec.com', port=443): Max retries exceeded with url: /api/v1/license_check?version=3.9.3&key=white (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f423409d5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/faraday/server/__init__.py", line 38, in run
    verify=True)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='portal.faradaysec.com', port=443): Max retries exceeded with url: /api/v1/license_check?version=3.9.3&key=white (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f423409d5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2020-03-05 03:16:11,516 - faraday.server - WARNING {Thread-4} [__init__.py:45 - run()]  NEWS: Can't connect to faradaysec.com...
2020-03-05 15:16:16,833 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-06 03:16:22,107 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-06 15:16:27,379 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-07 03:16:32,648 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-07 15:16:37,911 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-08 03:16:43,188 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-08 15:16:48,461 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-09 03:16:53,729 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-09 15:16:59,174 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-10 03:17:04,556 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-10 15:17:09,921 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID
2020-03-11 03:17:15,206 - faraday.server - INFO {Thread-4} [__init__.py:41 - run()]  License status INVALID

**Comment by ignaciosoto93** [comment]
Hey @ow111 — thanks for filing this and for taking the time to share logs back in 2020.

We're doing a pass on older issues and this one has been open for over 6 years without further activity. First, apologies — you provided the logs we asked for and we never followed up. That's on us.

A few things have changed since then:

- **Faraday 3.9.3 and Python 2.7** are both long past end-of-life — the current version runs on Python 3.11+ with a completely rewritten plugin engine.
- The **OpenVAS plugin** has received several updates since 2020, including CVSS3 handling improvements as recently as May 2025.
- Plugin issues are now tracked in the **[faraday_plugins](https://github.com/infobyte/faraday_plugins)** repository.

Given the age and the significant changes since this was filed, I'm going to close this one out.

If you (or anyone) still needs AlienVault OpenVAS support on a current Faraday version, please open a new issue on [faraday_plugins](https://github.com/infobyte/faraday_plugins/issues) with a sample report file — we currently support **118+ security tools** and are happy to look into it. You can also check the [plugin development guide](https://docs.faradaysec.com/Basic-plugin-development/) if you'd like to contribute one yourself.

---
*Closing as stale — no activity since March 2020, filed against EOL software.*
