### ISSUE TITLE
kali 2020.2 error

### ISSUE THREAD

**Issue by 5l1v3r1** [infobyte/faraday#386]
Traceback (most recent call last):
  File "/usr/bin/faraday-manage", line 11, in <module>
    load_entry_point('faradaysec==3.10.2', 'console_scripts', 'faraday-manage')()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2853, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2444, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2450, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/faraday/manage.py", line 44, in <module>
    from faraday.server.commands.app_urls import show_all_urls
  File "/usr/lib/python3/dist-packages/faraday/server/commands/app_urls.py", line 7, in <module>
    from faraday.server.web import app
  File "/usr/lib/python3/dist-packages/faraday/server/web.py", line 14, in <module>
    from twisted.web.static import File
  File "/usr/local/lib/python3.7/dist-packages/twisted/web/static.py", line 20, in <module>
    from twisted.web import server
  File "/usr/local/lib/python3.7/dist-packages/twisted/web/server.py", line 36, in <module>
    from twisted.spread.pb import Copyable, ViewPoint
  File "/usr/local/lib/python3.7/dist-packages/twisted/spread/pb.py", line 49, in <module>
    from twisted.spread.jelly import jelly, unjelly, globalSecurity, _newInstance
  File "/usr/local/lib/python3.7/dist-packages/twisted/spread/jelly.py", line 94, in <module>
    _SetTypes.append(_sets.Set)
AttributeError: module 'sets' has no attribute 'Set'

**Comment by montive** [comment]
Hi there.

Please, give us more information about this issue. How did you reproduce it?

**Comment by 5l1v3r1** [comment]
well it is due to installing faraday from kali repo which conflicts with python3-twisted module. well it can be temporarily fixed by uncommenting some lines after "/usr/local/lib/python3.7/dist-packages/twisted/spread/jelly.py", line 94 module of twisted. I think the problem is according to sets problem which is deprecated for python3.

**Comment by llazzaro** [comment]
Hi @5l1v3r1,

We have a temporary solution to this problem in #399. We are going to publish updates about this error with Kali Linux.
If you have any problem feel free to comment in #399 .

Thanks!
