### ISSUE TITLE
Unable to run on Kali 2.0

### ISSUE THREAD

**Issue by Consequences** [infobyte/faraday#39]
Hey, I'm probably just a noob but following the quick install instructions on Kali Sena doesn't seem to be working.

Steps to reproduce:
1) Download Kali Sena
2)Install and upgrade all packages
3) Pull faraday latest from github
4) ./install.sh

It tells me blahblahblahblah....
```
Successfully installed argparse
Cleaning up...
You can now run Faraday, enjoy!
```
Run faraday.py and you get...
```
2015-08-13 11:04:21,082 - faraday.launcher - INFO - You have available updates. Run ./faraday.py --update to catchup!
2015-08-13 11:04:21,225 - faraday.launcher - INFO - All done. Opening environment.
Traceback (most recent call last):
  File "./faraday.py", line 582, in <module>
    main()
  File "./faraday.py", line 576, in main
    startFaraday()
  File "./faraday.py", line 282, in startFaraday
    main_app = MainApplication(args)
  File "/root/faraday-dev/model/application.py", line 73, in __init__
    args.gui)
  File "/root/faraday-dev/gui/gui_app.py", line 16, in create
    from gui.qt3.application import GuiApp
  File "/root/faraday-dev/gui/qt3/application.py", line 13, in <module>
    import qt
RuntimeError: the sip module implements API v11.0 to v11.1 but the qt module requires API v8.1
```

Run faraday.py --update and you get...
```
2015-08-13 11:05:28,699 - faraday.launcher - INFO - You have available updates. Run ./faraday.py --update to catchup!
2015-08-13 11:05:28,760 - faraday.launcher - INFO - All done. Opening environment.
Traceback (most recent call last):
  File "./faraday.py", line 582, in <module>
    main()
  File "./faraday.py", line 576, in main
    startFaraday()
  File "./faraday.py", line 282, in startFaraday
    main_app = MainApplication(args)
  File "/root/faraday-dev/model/application.py", line 73, in __init__
    args.gui)
  File "/root/faraday-dev/gui/gui_app.py", line 16, in create
    from gui.qt3.application import GuiApp
  File "/root/faraday-dev/gui/qt3/application.py", line 19, in <module>
    from gui.qt3.mainwindow import MainWindow
  File "/root/faraday-dev/gui/qt3/mainwindow.py", line 10, in <module>
    from gui.qt3.pyqonsole.widget import ShellWidget
  File "/root/faraday-dev/gui/qt3/pyqonsole/widget.py", line 99, in <module>
    ColorEntry(qt.QColor(0x00,0x00,0x00), 0, 0 ), ColorEntry( qt.QColor(0xB2,0xB2,0xB2), 1, 0 ), # Dfore, Dback
AttributeError: 'module' object has no attribute 'QColor'
```

**Comment by Consequences** [comment]
Pastebin of the full console log http://pastebin.com/E7rC0gi0

**Comment by f-amato** [comment]
Hi @Consequences thanks for your feedback
We are working in this issue that already know about it, we are testing the patch and by the end of this week we are going to release a new version with this fix and others new features.

To get Faraday works use this workaround:

# apt-get install python-faraday
# cp -r /usr/share/python-faraday/external_libs/* /root/faraday-dev/external/external_libs/

and run again ./faraday.py 

Let me know if this fix the issue.

**Comment by Consequences** [comment]
```
root@kali:~# apt-get update
Hit http://security.kali.org sana/updates InRelease
Hit http://security.kali.org sana/updates/main Sources
Hit http://security.kali.org sana/updates/contrib Sources
Hit http://security.kali.org sana/updates/non-free Sources
Hit http://security.kali.org sana/updates/main amd64 Packages
Hit http://security.kali.org sana/updates/contrib amd64 Packages
Hit http://security.kali.org sana/updates/non-free amd64 Packages
Ign http://security.kali.org sana/updates/contrib Translation-en_US
Ign http://security.kali.org sana/updates/contrib Translation-en
Ign http://security.kali.org sana/updates/main Translation-en_US
Ign http://security.kali.org sana/updates/main Translation-en
Ign http://security.kali.org sana/updates/non-free Translation-en_US
Ign http://security.kali.org sana/updates/non-free Translation-en
Reading package lists... Done
root@kali:~# apt-get install python-faraday
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-faraday
```

It appears to be missing from the repositories. Is there a non-default repo you would suggest I add?

**Comment by Consequences** [comment]
```
root@kali:~# apt-get update
Hit http://security.kali.org sana/updates InRelease
Hit http://security.kali.org sana/updates/main Sources
Hit http://security.kali.org sana/updates/contrib Sources
Hit http://security.kali.org sana/updates/non-free Sources
Hit http://security.kali.org sana/updates/main amd64 Packages
Hit http://security.kali.org sana/updates/contrib amd64 Packages
Hit http://security.kali.org sana/updates/non-free amd64 Packages
Ign http://security.kali.org sana/updates/contrib Translation-en_US
Ign http://security.kali.org sana/updates/contrib Translation-en
Ign http://security.kali.org sana/updates/main Translation-en_US
Ign http://security.kali.org sana/updates/main Translation-en
Ign http://security.kali.org sana/updates/non-free Translation-en_US
Ign http://security.kali.org sana/updates/non-free Translation-en
Reading package lists... Done
root@kali:~# apt-get install python-faraday
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-faraday
```

Can't seem to find that package. Is there an additional repo I should be adding?

**Comment by f-amato** [comment]
I just tested in Kali Sana live cd

```
root@kali:~# cat /etc/apt/sources.list
deb http://http.kali.org/kali sana main contrib non-free
deb-src http://http.kali.org/kali sana main contrib non-free
deb http://security.kali.org/kali-security sana/updates main contrib non-free
deb-src http://security.kali.org/kali-security sana/updates main contrib non-free
root@kali:~# apt-cache search python-faraday
python-faraday - Collaborative Penetration Test IDE
```

**Comment by Consequences** [comment]
Ah, it seems I was only configured to receive security updates and the main kali software branches were missing. Likely my install got a little messed up because I wasn't able to connect to any mirrors during install.

Followed your instructions and everything is working now. One minor change, the correct cp command should be

```
cp -r /usr/share/python-faraday/external_libs/* /root/faraday-dev/external_libs/
```
 Thanks a lot for all the assistance!

**Comment by f-amato** [comment]
Thanks you @Consequences for try Faraday I hope help you in the next pentest !
