### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Strannik74** [infobyte/faraday#407]
Kali Linux 2020
faraday-server
Traceback (most recent call last):
  File "/usr/local/bin/faraday-server", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'faraday-plugins<2.0.0,>=1.0.1' distribution was not found and is required by faradaysec

**Comment by llazzaro** [comment]
Hi,

Are you using Kali 2020.3?

Thanks

**Comment by Strannik74** [comment]
Good evening!
Yes

**Comment by fedek** [comment]
Thanks for the bug report. Closed issue during clean-up.
