### ISSUE TITLE
User model must contain fs_uniquifier as of flask-security 4.0.0

### ISSUE THREAD

**Issue by lmcthbe** [infobyte/faraday#426]
## Issue Type
 - Bug Report

After upgrading Kali to latest package release, new flask-security 4.0.0 prevents faraday to start

## Faraday version

3.14

## Component Name

/usr/lib/python3/dist-packages/flask_security/core.py

## Steps to reproduce

Update flask-security to 4.0.0 and start faraday

### Debugging tracebacks (current results)
faraday-server -h
Traceback (most recent call last):
  File "/usr/bin/faraday-server", line 33, in <module>
    sys.exit(load_entry_point('faradaysec==3.14.0', 'console_scripts', 'faraday-server')())
  File "/usr/bin/faraday-server", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/faraday/start_server.py", line 16, in <module>
    import faraday.server.web
  File "/usr/lib/python3/dist-packages/faraday/server/web.py", line 36, in <module>
    app = create_app()  # creates a Flask(__name__) app
  File "/usr/lib/python3/dist-packages/faraday/server/app.py", line 368, in create_app
    Security(app, app.user_datastore, login_form=CustomLoginForm)
  File "/usr/lib/python3/dist-packages/flask_security/core.py", line 1024, in __init__
    self._state = self.init_app(
  File "/usr/lib/python3/dist-packages/flask_security/core.py", line 1080, in init_app
    raise ValueError("User model must contain fs_uniquifier as of 4.0.0")
ValueError: User model must contain fs_uniquifier as of 4.0.0

### OS

$ cat /etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by EricHorvat** [comment]
Hi there! 

Are you using kali version of faraday or an own virtual-env?

We are currently migrating to flask-security 4.0.0, but it will not be ready for the next version. We estimate that for the following one it'll be done

Regards,
Eric

**Comment by lmcthbe** [comment]
Hi,

Yes, I am using the faraday version of Kali. 

And when the next version is planned to be delivered ?

Regards
Thierry

**Comment by EricHorvat** [comment]
Hi @lmcthbe 

We currently do not mantain kali version of faraday, but will pass this error to kali mantainers. They will handle this and problably fix it meanwhile we add it to our code.

I can't ensure the exact date of that version but I can say as it's the following to the next one (next week), it will be on late March / first days of April

**Comment by EricHorvat** [comment]
Hi @lmcthbe . We talk with the kali mantainers and they launched a fix for this problem. We already updated to flask-security-too in 3.14.1, released today and passed that info to the mantainers. I'll close this, as its written in the requirements, that we need flask-security-too <4. We'll update to flask security 4.0.0 in the next releases.

Regards
Eric
