### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/faraday/.faraday/logs/alembic.log'

### ISSUE THREAD

**Issue by cavazquez** [infobyte/faraday#444]
When run docker-compose and try create database apper error.

Trying to connect to database ...
today at 11:47:50 AMCreating tables
today at 11:47:51 AMTraceback (most recent call last):
today at 11:47:51 AM  File "/nix/store/gkykirs9m7af1lgsk2mlh7irrg7ipcwn-faraday-server-3.18.1/bin/.faraday-manage-wrapped", line 9, in <module>
today at 11:47:51 AM    sys.exit(cli())
today at 11:47:51 AM  File "/nix/store/r5pycb209p9gc6siqd8cfcn2mb1gygvy-python3.8-click-8.0.3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
today at 11:47:51 AM    return self.main(*args, **kwargs)
today at 11:47:51 AM  File "/nix/store/r5pycb209p9gc6siqd8cfcn2mb1gygvy-python3.8-click-8.0.3/lib/python3.8/site-packages/click/core.py", line 1053, in main
today at 11:47:51 AM    rv = self.invoke(ctx)
today at 11:47:51 AM  File "/nix/store/r5pycb209p9gc6siqd8cfcn2mb1gygvy-python3.8-click-8.0.3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
today at 11:47:51 AM    return _process_result(sub_ctx.command.invoke(sub_ctx))
today at 11:47:51 AM  File "/nix/store/r5pycb209p9gc6siqd8cfcn2mb1gygvy-python3.8-click-8.0.3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
today at 11:47:51 AM    return ctx.invoke(self.callback, **ctx.params)
today at 11:47:51 AM  File "/nix/store/r5pycb209p9gc6siqd8cfcn2mb1gygvy-python3.8-click-8.0.3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
today at 11:47:51 AM    return __callback(*args, **kwargs)
today at 11:47:51 AM  File "/nix/store/gkykirs9m7af1lgsk2mlh7irrg7ipcwn-faraday-server-3.18.1/lib/python3.8/site-packages/faraday/manage.py", line 208, in create_tables
today at 11:47:51 AM    InitDB()._create_tables(conn_string)
today at 11:47:51 AM  File "/nix/store/gkykirs9m7af1lgsk2mlh7irrg7ipcwn-faraday-server-3.18.1/lib/python3.8/site-packages/faraday/server/commands/initdb.py", line 466, in _create_tables
today at 11:47:51 AM    command.stamp(alembic_cfg, "head")
today at 11:47:51 AM  File "/nix/store/kzc6ak216flxgss5x32qav69lnz3ayfx-python3.8-alembic-1.4.2/lib/python3.8/site-packages/alembic/command.py", line 579, in stamp
today at 11:47:51 AM    script.run_env()
today at 11:47:51 AM  File "/nix/store/kzc6ak216flxgss5x32qav69lnz3ayfx-python3.8-alembic-1.4.2/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
today at 11:47:51 AM    util.load_python_file(self.dir, "env.py")
today at 11:47:51 AM  File "/nix/store/kzc6ak216flxgss5x32qav69lnz3ayfx-python3.8-alembic-1.4.2/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
today at 11:47:51 AM    module = load_module_py(module_id, path)
today at 11:47:51 AM  File "/nix/store/kzc6ak216flxgss5x32qav69lnz3ayfx-python3.8-alembic-1.4.2/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
today at 11:47:51 AM    spec.loader.exec_module(module)
today at 11:47:51 AM  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
today at 11:47:51 AM  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
today at 11:47:51 AM  File "migrations/env.py", line 25, in <module>
today at 11:47:51 AM    fh = logging.FileHandler(LOG_FILE)
today at 11:47:51 AM  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/logging/__init__.py", line 1143, in __init__
today at 11:47:51 AM    StreamHandler.__init__(self, self._open())
today at 11:47:51 AM  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/logging/__init__.py", line 1172, in _open
today at 11:47:51 AM    return open(self.baseFilename, self.mode, encoding=self.encoding)
today at 11:47:51 AMFileNotFoundError: [Errno 2] No such file or directory: '/home/faraday/.faraday/logs/alembic.log'
today at 11:47:59 AMContainer stopped

**Comment by cavazquez** [comment]
Run mkdir /home/faraday/.faraday/logs solve de problem

**Comment by f-amato** [comment]
Thanks @cavazquez for reporting this! We are going to check it out.
Best
