### ISSUE TITLE
ImportError: cannot import name 'JSONEncoder' from 'flask.json'

### ISSUE THREAD

**Issue by D3vil0p3r** [infobyte/faraday#501]
When I run `faraday-server` I get:
```
Traceback (most recent call last):
  File "/usr/bin/faraday-server", line 33, in <module>
    sys.exit(load_entry_point('faradaysec==5.7.0', 'console_scripts', 'faraday-server')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/faraday-server", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/faraday/start_server.py", line 25, in <module>
    from faraday.server.app import get_app
  File "/usr/lib/python3.12/site-packages/faraday/server/app.py", line 32, in <module>
    from flask.json import JSONEncoder
ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/usr/lib/python3.12/site-packages/flask/json/__init__.py)
```
despite I installed all the mentioned dependencies in `requirements.txt`.

**Comment by ezk06eer** [comment]
Hello @D3vil0p3r can you please show us /usr/lib/python3.12/site-packages/ contents? 


It seems you're using python 3.12

Thanks!

**Comment by D3vil0p3r** [comment]
```
 __pycache__                                           h11                                         pytest-8.3.3.dist-info
 _brotli.cpython-312-x86_64-linux-gnu.so               h11-0.14.0.dist-info                        python_dateutil-2.9.0.dist-info
 _cffi_backend.cpython-312-x86_64-linux-gnu.so         Hamlib.py                                   python_engineio-4.9.1.dist-info
 _dbus_bindings.cpython-312-x86_64-linux-gnu.so        hgdemandimport                              python_libnmap-0.7.3-py3.12.egg-info
 _dbus_glib_bindings.cpython-312-x86_64-linux-gnu.so   hgext                                       python_magic-0.4.27.dist-info
 _distutils_hack                                       hgext3rd                                    python_mimeparse-1.6.0-py3.12.egg-info
 _Hamlib.so                                            html2text                                   python_slugify-8.0.4-py3.12.egg-info
 _hypothesis_ftz_detector.py                           html2text-2024.2.26-py3.12.egg-info         python_socketio-5.8.0.dist-info
 _hypothesis_globals.py                                httpcore                                    python_xmp_toolkit-2.0.1.dist-info
 _hypothesis_pytestplugin.py                           httpcore-1.0.5.dist-info                    pytsk3-20231007-py3.12.egg-info
 _ldb_text.py                                          httptools                                   pytsk3.cpython-312-x86_64-linux-gnu.so
 _libfdt.cpython-312-x86_64-linux-gnu.so               httptools-0.6.1-py3.12.egg-info             pytz
 _nvx_utf8validator.abi3.so                            httpx                                       pytz-2024.2-py3.12.egg-info
 _pytest                                               httpx-0.27.2.dist-info                      pywhat
 _snack.so                                             humanize                                    pywhat-5.1.0.dist-info
 _SoapySDR.so                                          humanize-4.9.0.dist-info                    pyxcute-0.6.0-py3.12.egg-info
 _tdb_text.py                                          humblewx                                    pyxdg-0.28-py3.12.egg-info
 _tevent.cpython-312-x86_64-linux-gnu.so               humblewx-0.2.2.dist-info                    PyYAML-6.0.2.dist-info
 _time_machine.cpython-312-x86_64-linux-gnu.so         hyperlink                                   qrcode
 _yaml                                                 hyperlink-21.0.0.dist-info                  qrcode-7.4.2.dist-info
 ADExplorerSnapshot-1.0.0.dist-info                    hypothesis                                  QTermWidget-2.0.1.dist-info
 adexpsnapshot                                         hypothesis-6.112.4.dist-info                QTermWidget.abi3.so
 aiodns                                                idna                                        README.txt
 aiodns-3.2.0.dist-info                                idna-3.8.dist-info                          readme_renderer
 aiohappyeyeballs                                      imagesize                                   readme_renderer-43.0.dist-info
 aiohappyeyeballs-2.4.3.dist-info                      imagesize-1.4.1.dist-info                   redis
 aiohttp                                               imath.so                                    redis-5.1.0.dist-info
 aiohttp-3.10.5.dist-info                              imgcat                                      Reflector-2023.6.28.0.36.1.dist-info
 aiosignal                                             imgcat-0.5.0-py3.12.egg-info                Reflector.py
 aiosignal-1.3.1.dist-info                             imobiledevice.so                            requests
 aiosqlite                                             impacket                                    requests-2.32.3.dist-info
 aiosqlite-0.20.0.dist-info                            impacket-0.11.0.dist-info                   requests_file-1.5.1-py3.12.egg-info
 alabaster                                             importlib_metadata                          requests_file.py
 alabaster-1.0.0.dist-info                             importlib_metadata-7.2.1.dist-info          requests_ntlm
 alembic                                               importlib_resources                         requests_ntlm-1.2.0.dist-info
 alembic-1.13.1.dev0.dist-info                         importlib_resources-6.4.5.dist-info         requests_toolbelt
 amqp                                                  incremental                                 requests_toolbelt-1.0.0-py3.12.egg-info
 amqp-5.2.0-py3.12.egg-info                            incremental-22.10.0.dist-info               responses
 anyascii                                              inflect                                     responses-0.25.3-py3.12.egg-info
 anyascii-0.3.2.dist-info                              inflect-7.2.1.dist-info                     rfc3986
 anyio                                                 iniconfig                                   rfc3986-2.0.0-py3.12.egg-info
 anyio-4.4.0.dist-info                                 iniconfig-2.0.0.dist-info                   rich
 apispec                                               installer                                   rich-13.8.1.dist-info
 apispec-6.0.2.dist-info                               installer-0.7.0.dist-info                   ropgadget
 apispec_webframeworks                                 intervaltree                                ROPGadget-7.4.dist-info
 apispec_webframeworks-0.5.2-py3.12.egg-info           intervaltree-3.1.0-py3.12.egg-info          rpyc
 apng                                                  iptcdata.so                                 rpyc-6.0.1.dist-info
 apng-0.3.4-py3.12.egg-info                            IPy-1.1-py3.12.egg-info                     scandir-1.10.0-py3.12.egg-info
 appdirs-1.4.4.dist-info                               IPy.py                                      scandir.py
 appdirs.py                                            isort                                       scapy
 asciinema                                             isort-5.13.2.dist-info                      scapy-2.5.0.dist-info
 asciinema-2.4.0.dist-info                             itsdangerous                                secretstorage
 asgiref                                               itsdangerous-2.1.2.dist-info                SecretStorage-3.3.3.dist-info
 asgiref-3.7.2-py3.12.egg-info                         jaraco                                      selenium
 asn1crypto                                            jaraco.classes-3.4.0.dist-info              selenium-3.141.0-py3.12.egg-info
 asn1crypto-1.5.1-py3.12.egg-info                      jaraco.context-5.3.0.dist-info              serial
 astroid                                               jaraco.functools-4.0.2.dist-info            service_identity
 astroid-3.3.4.dist-info                               jaraco.text-4.0.0.dist-info                 service_identity-23.1.0.dist-info
 async_timeout                                         jeepney                                     setproctitle
 async_timeout-4.0.3.dist-info                         jeepney-0.8.0.dist-info                     setproctitle-1.3.3.dist-info
 attr                                                  jinja2                                      setuptools
 attrs                                                 jinja2-3.1.4.dist-info                      setuptools-69.5.1-py3.12.egg-info
 attrs-23.2.1.dev0.dist-info                           jwt                                         setuptools_scm
 autobahn                                              keyring                                     setuptools_scm-8.1.0.dist-info
 autobahn-24.4.2.dist-info                             keyring-25.2.1.dist-info                    sh-2.0.7.dist-info
 autocommand                                           kombu                                       sh.py
 autocommand-2.2.2.dist-info                           kombu-5.4.2.dist-info                       shiboken6
 automat                                               ldap3                                       shiboken6.egg-info
 Automat-22.10.0-py3.12.egg-info                       ldap3-2.9-py3.12.egg-info                   shiboken6_generator
 avahi                                                 ldb.cpython-312-x86_64-linux-gnu.so         shiboken6_generator.egg-info
 babel                                                 libear                                      shodan
 Babel-2.15.0-py3.12.egg-info                          libfdt-1.7.1-py3.12.egg-info                shodan-1.31.0.dist-info
 backports                                             libfdt.py                                   simplejson
 backports.csv-1.0.7-py3.12-nspkg.pth                  libfuturize                                 simplejson-3.19.2.dist-info
 backports.csv-1.0.7-py3.12.egg-info                   libmount                                    simplekv
 bcrypt                                                libnmap                                     simplekv-0.14.1-py3.12.egg-info
 bcrypt-4.1.3.dist-info                                libnvme                                     six-1.16.0-py3.12.egg-info
 beautifulsoup4-4.12.3.dist-info                       libpasteurize                               six.py
 bidict                                                libscanbuild                                slugify
 bidict-0.23.1.dist-info                               libsvn                                      snack.py
 billiard                                              libtmux                                     sniffio
 billiard-4.2.0.dist-info                              libtmux-0.37.0.dist-info                    sniffio-1.3.1.dist-info
 binwalk                                               libxml2.py                                  snowballstemmer
 binwalk-2.4.2.dist-info                               libxml2mod.so                               snowballstemmer-2.2.0-py3.12.egg-info
 bleach                                                libxmp                                      SoapySDR.py
 bleach-6.1.0-py3.12.egg-info                          libxslt.py                                  socketio
 blinker                                               libxsltmod.so                               socketpool
 blinker-1.7.0.dist-info                               limits                                      socketpool-0.5.3-py3.12.egg-info
 bloodhound                                            limits-3.13.0.dist-info                     socks.py
 bloodhound-1.7.2-py3.12.egg-info                      lit                                         sockshandler.py
 boost                                                 lit-18.1.8.dev0-py3.12.egg-info             sortedcontainers
 breezy                                                livereload                                  sortedcontainers-2.4.0.dist-info
 breezy-3.3.8.dist-info                                livereload-2.6.3-py3.12.egg-info            soupsieve
 Brlapi-0.8.5-py3.12.egg-info                          louis                                       soupsieve-2.6.dist-info
 brlapi.cpython-312-x86_64-linux-gnu.so                louis-3.31.0.dist-info                      speaklater-1.3-py3.12.egg-info
 Brotli-1.1.0.dist-info                                lxml                                        speaklater.py
 brotli.py                                             lxml-5.3.0-py3.12.egg-info                  speechd
 bs4                                                   magic                                       speechd_config
 btrfsutil-6.10-py3.12.egg-info                        mako                                        sphinx
 btrfsutil.cpython-312-x86_64-linux-gnu.so             Mako-1.3.5.dev0.dist-info                   sphinx-8.0.2.dist-info
 build                                                 markdown                                    sphinx_autobuild
 build-1.2.2.dist-info                                 Markdown-3.7.dist-info                      sphinx_autobuild-2024.4.13.dist-info
 bytesize                                              markdown_it                                 sphinxcontrib
 caca                                                  markdown_it_py-3.0.0.dist-info              sphinxcontrib_applehelp-2.0.0.dist-info
 cachetools                                            markupsafe                                  sphinxcontrib_devhelp-2.0.0.dist-info
 cachetools-5.5.0.dist-info                            MarkupSafe-2.1.5.dist-info                  sphinxcontrib_htmlhelp-2.1.0.dist-info
 cairo                                                 marshmallow                                 sphinxcontrib_jsmath-1.0.1-py3.12-nspkg.pth
 capstone                                              marshmallow-3.20.2.dist-info                sphinxcontrib_jsmath-1.0.1.dist-info
 capstone-5.0.3.dist-info                              marshmallow_sqlalchemy                      sphinxcontrib_qthelp-2.0.0.dist-info
 celery                                                marshmallow_sqlalchemy-1.1.0.dist-info      sphinxcontrib_serializinghtml-2.0.0.dist-info
 celery-5.4.0.dist-info                                mccabe-0.7.0.dist-info                      spnego
 certifi                                               mccabe.py                                   sqlalchemy
 certifi-2024.2.2-py3.12.egg-info                      mdurl                                       SQLAlchemy-2.0.35.dev0.dist-info
 certipy                                               mdurl-0.1.2.dist-info                       sqlparse
 certipy_ad-4.8.2-py3.12.egg-info                      mercurial                                   sqlparse-0.5.1.dist-info
 cffi                                                  mercurial-6.8.1.dist-info                   starlette
 cffi-1.16.0.dist-info                                 merge3                                      starlette-0.39.2.dist-info
 chardet                                               merge3-0.0.15.dist-info                     stegoveritas
 chardet-5.2.0.dist-info                               meson-1.5.2.dist-info                       stegoveritas-1.10-py3.12.egg-info
 charset_normalizer                                    mesonbuild                                  stegoveritas_install_deps
 charset_normalizer-3.3.2.dist-info                    mimeparse.py                                stegoveritas_pfp-0.2.3-py3.12.egg-info
 clang                                                 mimerender-0.6.0.dist-info                  stegoveritas_py010parser-0.1.10-py3.12.egg-info
 cli_helpers                                           mimerender.py                               stem
 cli_helpers-2.3.1-py3.12.egg-info                     mockito                                     stem-1.8.3.dist-info
 click                                                 mockito-1.5.0.dist-info                     svn
 click-8.1.7.dist-info                                 more_itertools                              syslog_rfc5424_formatter
 click_didyoumean                                      more_itertools-10.3.0.dist-info             syslog_rfc5424_formatter-1.2.3-py3.12.egg-info
 click_didyoumean-0.3.1.dist-info                      msgpack                                     tabulate
 click_plugins                                         msgpack-1.0.5.dist-info                     tabulate-0.9.0.dist-info
 click_plugins-1.1.1-py3.12.egg-info                   multidict                                   talloc.cpython-312-x86_64-linux-gnu.so
 click_repl                                            multidict-6.0.5.dist-info                   tbb
 click_repl-0.3.0.dist-info                            mypy                                        TBB-0.2-py3.12.egg-info
 colorama                                              mypy-1.11.2.dist-info                       TBB.py
 colorama-0.4.6.dist-info                              mypy_extensions-1.0.0-py3.12.egg-info       tdb.cpython-312-x86_64-linux-gnu.so
 colored_traceback                                     mypy_extensions.py                          termcolor
 colored_traceback-0.3.0-py3.12.egg-info               mypyc                                       termcolor-2.4.0.dist-info
 colorlog                                              nacl                                        terminaltables
 colorlog-6.8.2.dist-info                              nh3                                         terminaltables-3.1.10-py3.12.egg-info
 configobj                                             nh3-0.2.17.dist-info                       󰙨 tests
 configobj-5.0.8-py3.12.egg-info                       ninja_syntax.py                             tevent.py
 constantly                                            nplusone                                    text_unidecode
 constantly-23.10.0.dist-info                          nplusone-1.0.0-py3.12.egg-info              text_unidecode-1.3.dist-info
 couchdb                                               numpy                                       time_machine
 CouchDB-1.2-py3.12.egg-info                           numpy-2.1.1.dist-info                       time_machine-2.15.0.dist-info
 croniter                                              onionshare                                  tldextract
 croniter-3.0.3.dist-info                              onionshare-2.6.2.dist-info                  tldextract-5.1.2.dist-info
 Crypto                                                onionshare_cli                              toml
 Cryptodome                                            onionshare_cli-2.6.2.dist-info              toml-0.10.2.dist-info
 cryptography                                          OpenSSL                                     tomli
 cryptography-42.0.7.dist-info                         orca                                        tomli-2.0.1.dist-info
 cvss                                                  ordered_set                                 tomlkit
 cvss-3.2-py3.12.egg-info                              ordered_set-4.1.0.dist-info                 tomlkit-0.13.2.dist-info
 cx_Oracle-7.3.0-py3.12.egg-info                       orjson                                      torbrowser_launcher
 cx_Oracle.cpython-312-x86_64-linux-gnu.so             orjson-3.10.7.dist-info                     torbrowser_launcher-0.3.7.dist-info
 dateutil                                              packaging                                   tornado
 dbus                                                  packaging-24.1.dist-info                    tornado-6.4.1.dist-info
 dbus_python.egg-info                                  pandas                                      tox
 depot                                                 pandas-2.2.2.dist-info                      tox-4.12.1.dist-info
 deprecated                                            paramiko                                    tqdm
 Deprecated-1.2.14.dist-info                           paramiko-3.4.0-py3.12.egg-info              tqdm-4.66.5.dist-info
 deprecation-2.1.0-py3.12.egg-info                     passlib                                     trove_classifiers
 deprecation.py                                        passlib-1.7.4-py3.12.egg-info               trove_classifiers-2024.9.17.dist-info
 dill                                                  past                                        twine
 dill-0.3.8.dist-info                                  pathlib2                                    twine-5.0.1.dev0+g94f810c.d20240510.dist-info
 dissect                                               pathlib2-2.3.7.post1-py3.12.egg-info        twisted
 dissect-3.16.1.dist-info                              patiencediff                                twisted-24.3.0.dist-info
 dissect.cstruct-4.2.dev1+g09830d2.dist-info           patiencediff-0.2.15.dist-info               txaio
 distlib                                               pcapy.cpython-312-x86_64-linux-gnu.so       txaio-23.1.1.dist-info
 distlib-0.3.8.dist-info                               pcapy_ng-1.0.9-py3.12.egg-info              typeguard
 distro                                                pendulum                                    typeguard-4.3.0.dist-info
 distro-1.9.0.dist-info                                pendulum-3.0.0.dist-info                    typing_extensions-4.12.2.dist-info
 distutils-precedence.pth                              pfp                                         typing_extensions.py
 dns                                                   pgcli                                       tzdata
 dnspython-2.6.1.dist-info                             pgcli-4.1.0-py3.12.egg-info                 tzdata-2024.2.dist-info
 docutils                                              pgspecial                                   tzlocal
 docutils-0.21.2.dist-info                             pgspecial-2.1.2.dist-info                   tzlocal-5.2.dist-info
 drv_libxml2.py                                        PIL                                         uc_micro
 dsinternals                                           pillow-10.4.0.dist-info                     uc_micro_py-1.0.3.dist-info
 dsinternals-1.2.4-py3.12.egg-info                     pip                                         ufw
 dulwich                                               pip-24.2.dist-info                          ufw-0.36.2-py3.12.egg-info
 dulwich-0.22.1.dist-info                              pkg_resources                               uhd
 elastic_transport                                     pkginfo                                     ujson-5.10.0.dist-info
 elastic_transport-8.15.0.dist-info                    pkginfo-1.10.0.dist-info                    ujson.cpython-312-x86_64-linux-gnu.so
 elasticsearch                                         platformdirs                                unicorn
 elasticsearch-8.15.1.dist-info                        platformdirs-4.3.6.dist-info                unicorn-2.0.1.post1-py3.12.egg-info
 elftools                                              plist.so                                    unidecode
 email_validator                                       pluggy                                      Unidecode-1.3.8-py3.12.egg-info
 email_validator-2.1.1.dist-info                       pluggy-1.5.0.dist-info                      urllib3
 engineio                                              plumbum                                     urllib3-1.26.20.dist-info
 eventlet                                              plumbum-1.8.3.dist-info                     usrp_mpm
 eventlet-0.35.2.dist-info                             png.py                                      utils
 exifread                                              prettytable                                 uvicorn
 ExifRead-3.0.0-py3.12.egg-info                        prettytable-3.11.0.dist-info                uvicorn-0.31.0.dist-info
 exiftool.py                                           prompt_toolkit                              uvloop
 faraday                                               prompt_toolkit-3.0.48.dist-info             uvloop-0.20.0.dist-info
 faraday_agent_parameters_types                        psutil                                      validate
 faraday_agent_parameters_types-1.7.1.dist-info        psutil-6.0.0.dist-info                      validate-5.0.8-py3.12.egg-info
 faraday_plugins                                       psycogreen                                  validate_pyproject
 faraday_plugins-1.19.1-py3.12.egg-info                psycogreen-1.0.2-py3.12.egg-info            validate_pyproject-0.19.dist-info
 faradaysec-5.7.0-py3.12.egg-info                      psycopg                                     validators
 fastbencode                                           psycopg-3.2.1.dist-info                     validators-0.20.0.dist-info
 fastbencode-0.3.1.dist-info                           psycopg2                                    vapoursynth.so
 fastjsonschema                                        psycopg2-2.9.9.dist-info                    vine
 fastjsonschema-2.20.0.dist-info                       pwn                                         vine-5.1.0.dist-info
 filedepot-0.11.0-py3.12.egg-info                      pwnlib                                      vipermonkey
 filelock                                              pwntools-4.13.1.dist-info                   vipermonkey-2.0.0-py3.12.egg-info
 filelock-3.13.3.dist-info                             pwquality-1.4.5-py3.12.egg-info             virtualenv
 filteralchemy                                         pwquality.cpython-312-x86_64-linux-gnu.so   virtualenv-20.26.2.dist-info
 filteralchemy_fork-0.1.0-py3.12.egg-info              py.py                                       volk_modtool
 flask                                                 py010parser                                 w3af_api_client-3.0.1-py3.12.egg-info
 flask-2.3.3.dist-info                                 pyaml                                       waitress
 flask_babel                                           pyaml-24.7.0.dist-info                      waitress-3.0.0.dist-info
 flask_babel-4.0.0.dist-info                           pyasn1                                      watchfiles
 flask_celery.py                                       pyasn1-0.6.0.dist-info                      watchfiles-0.24.0.dist-info
 Flask_Celery_Helper-1.1.0-py3.12.egg-info             pyasn1_modules                              wcwidth
 flask_classful-0.16.0.dist-info                       pyasn1_modules-0.4.0.dist-info              wcwidth-0.2.13.dist-info
 flask_classful.py                                     pycairo-1.27.0.dist-info                    webargs
 flask_compress                                        pycares                                     webargs-8.4.0-py3.12.egg-info
 Flask_Compress-1.14.dist-info                         pycares-4.4.0.dist-info                     webencodings
 flask_kvsession                                       pycparser                                   webencodings-0.5.1-py3.12.egg-info
 Flask_KVSession_fork-0.6.4-py3.12.egg-info            pycparser-2.22-py3.12.egg-info              websocket
 flask_limiter                                         pycryptodome-3.20.0.dist-info               websocket_client-1.8.0-py3.12.egg-info
 Flask_Limiter-3.8.0.dist-info                         pycryptodomex-3.20.0-py3.12.egg-info        websockets
 flask_login                                           pyee                                        websockets-12.0.dist-info
 Flask_Login-0.6.3.dist-info                           pyee-11.1.0.dist-info                       werkzeug
 Flask_Mail-0.9.1-py3.12.egg-info                      pyelftools-0.31.dist-info                   werkzeug-3.0.1.dist-info
 flask_mail.py                                         PyExifTool-0.1.1-py3.12.egg-info            wheel
 flask_mailman                                         pygments                                    wheel-0.44.0.dist-info
 flask_mailman-1.0.0.dist-info                         pygments-2.18.0.dist-info                   whoosh
 Flask_Principal-0.4.0-py3.12.egg-info                 PyGObject-3.50.0.dist-info                  Whoosh-2.7.4.dist-info
 flask_principal.py                                    pygtkcompat                                 wrapt
 flask_restless                                        PyJWT-2.9.0.dist-info                       wrapt-1.16.0.dist-info
 Flask_Restless-0.17.0-py3.12.egg-info                 pylint                                      wsaccel
 flask_security                                        pylint-3.3.1.dist-info                      wsaccel-0.6.6.dist-info
 Flask_Security_Too-5.4.3.dist-info                    PyNaCl-1.5.0.dist-info                      wtforms
 flask_socketio                                        pyOpenSSL-24.2.1.dist-info                  wtforms-3.1.2.dist-info
 Flask_SocketIO-5.3.6.dist-info                        pyotp                                       wx
 flask_sqlalchemy                                      pyotp-2.9.0-py3.12.egg-info                 wxPython-4.2.1-py3.12.egg-info
 flask_sqlalchemy-3.1.1.dist-info                      pyparsing                                   xcbgen
 flask_wtf                                             pyparsing-3.1.2.dist-info                   xcute
 flask_wtf-1.2.1.dist-info                             pypng-0.20231004.0.dist-info                xdg
 frozendict                                            pyppeteer                                   xlsxwriter
 frozendict-2.4.0.dist-info                            pyppeteer-2.0.0.dist-info                   XlsxWriter-3.1.9.dist-info
 frozenlist                                            pyproject_api                               xmltodict-0.13.0-py3.12.egg-info
 frozenlist-1.4.1.dist-info                            pyproject_api-1.8.0.dist-info               xmltodict.py
 future                                                pyproject_hooks                             yaml
 future-1.0.0.dist-info                                pyproject_hooks-1.1.0.dist-info             yara.cpython-312-x86_64-linux-gnu.so
 gevent                                                PyQt5                                       yara_python-4.5.0-py3.12.egg-info
 gevent-24.2.1.dist-info                               PyQt5-5.15.11.dist-info                     yarl
 gevent_websocket-0.10.1-py3.12.egg-info               PyQt5_sip-12.15.0.dist-info                 yarl-1.9.4.dist-info
 geventwebsocket                                       PyQt6                                       zipp
 gi                                                    pyserial-3.5-py3.12.egg-info                zipp-3.19.3.dev0+gc6a3339.d20240728.dist-info
 gpg                                                   PySide6                                     zope
 gpg-1.23.2.dist-info                                  PySide6.egg-info                            zope.event-5.0-py3.12-nspkg.pth
 greenlet                                              PySocks-1.7.1-py3.12.egg-info               zope.event-5.0-py3.12.egg-info
 greenlet-3.1.0.dist-info                              pyspnego-0.10.2.dist-info                   zope.interface-7.0.3-py3.12-nspkg.pth
 gtweak                                                pysqlite3                                   zope.interface-7.0.3.dist-info
 gunicorn                                              pysqlite3-0.5.3.dist-info                   zstandard
 gunicorn-23.0.0.dist-info                             pytest                                      zstandard-0.22.0-py3.12.egg-info
```

**Comment by D3vil0p3r** [comment]
> Hello [@D3vil0p3r](https://github.com/D3vil0p3r) can you please show us /usr/lib/python3.12/site-packages/ contents?
> 
> It seems you're using python 3.12
> 
> Thanks!

Now I am using Python 3.13 and still getting:
```
faraday-server
Traceback (most recent call last):
  File "/usr/bin/faraday-server", line 33, in <module>
    sys.exit(load_entry_point('faradaysec==5.16.0', 'console_scripts', 'faraday-server')())
             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/faraday-server", line 25, in importlib_load_entry_point
    return next(matches).load()
           ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 179, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.13/site-packages/faraday/start_server.py", line 25, in <module>
    from faraday.server.app import get_app, create_app
  File "/usr/lib/python3.13/site-packages/faraday/server/app.py", line 34, in <module>
    from flask.json import JSONEncoder
ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/usr/lib/python3.13/site-packages/flask/json/__init__.py)
```

**Comment by D3vil0p3r** [comment]
> Hello [@D3vil0p3r](https://github.com/D3vil0p3r) can you please show us /usr/lib/python3.12/site-packages/ contents?
> 
> It seems you're using python 3.12
> 
> Thanks!

@ezk06eer Now I am using Python 3.13 and still getting:
```
faraday-server
Traceback (most recent call last):
  File "/usr/bin/faraday-server", line 33, in <module>
    sys.exit(load_entry_point('faradaysec==5.16.0', 'console_scripts', 'faraday-server')())
             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/faraday-server", line 25, in importlib_load_entry_point
    return next(matches).load()
           ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 179, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.13/site-packages/faraday/start_server.py", line 25, in <module>
    from faraday.server.app import get_app, create_app
  File "/usr/lib/python3.13/site-packages/faraday/server/app.py", line 34, in <module>
    from flask.json import JSONEncoder
ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/usr/lib/python3.13/site-packages/flask/json/__init__.py)
```

**Comment by D3vil0p3r** [comment]
I guess JSONEncoder from flask is deprecated https://github.com/MongoEngine/flask-mongoengine/issues/522 could you please use a maintained library for JSON encoding?

**Comment by D3vil0p3r** [comment]
@dnadares @FaradayDev

**Comment by ignaciosoto93** [comment]
Thanks for the detailed report and follow-up, @D3vil0p3r .

  Based on your traceback, Faraday is installed system-wide (`/usr/lib/python3.12/site-packages/`), which is causing Flask version conflicts.

  **Fix:** Use an isolated virtual environment:

  ```bash
  python3 -m venv faraday_venv
  source faraday_venv/bin/activate
  pip3 install faradaysec
  faraday-manage initdb

  Why this happens: Your system has Flask 3.x, which removed JSONEncoder from flask.json. Faraday requires Flask <=2.1.3. A virtualenv ensures the correct versions are isolated from system packages.
  ```

**Comment by D3vil0p3r** [comment]
Thank you for the answer. I am installing system-wide because I am packaging Faraday for BlackArch.

**Comment by ignaciosoto93** [comment]
Thanks for clarifying, @D3vil0p3r .

  As a BlackArch package maintainer, system-wide installation with Arch's Flask 3.x is a valid requirement. This is not a user configuration issue — Faraday needs to update its dependencies.


 Keeping this open to track Flask 3.x compatibility.

**Comment by ignaciosoto93** [comment]
Thanks for the report and the packaging context.

The specific `JSONEncoder` import problem reported here was addressed in Faraday `v5.23.0`. Since that release, Faraday no longer imports `JSONEncoder` from `flask.json` and uses Flask JSON provider instead.

Could you please retry with `v5.23.0` or a newer release and confirm whether you still get this exact traceback?

If the server now fails with a different error, please share the updated traceback together with the Python and Flask versions you are packaging against, and we can review it from there.

**Comment by ignaciosoto93** [comment]
Closing since is fixed on v5.23.0

**Comment by D3vil0p3r** [comment]
Hi @ignaciosoto93 sorry for my late response. I was checking now and I cloned the master branch, but when I run:
```
 git describe --long --tags --abbrev=7
```
I get `v3.19.0-3098-g17217f4` instead of 5.24.xxx.

Can you give a look to your repo?
