### ISSUE TITLE
failing to launch ./faraday.py

### ISSUE THREAD

**Issue by ichintu** [infobyte/faraday#97]
2016-07-08 16:09:14,523 - faraday.launcher - INFO - Starting Faraday IDE.
2016-07-08 16:09:14,524 - faraday.launcher - INFO - Dependencies met.
2016-07-08 16:09:14,524 - faraday.launcher - INFO - Checking configuration.
2016-07-08 16:09:14,525 - faraday.launcher - INFO - Setting up plugins.
2016-07-08 16:09:14,525 - faraday.launcher - INFO - Removing old plugins folder
2016-07-08 16:09:14,572 - faraday.launcher - INFO - Setting up ZSH integration.
2016-07-08 16:09:14,574 - faraday.launcher - INFO - Setting up  user configuration.
2016-07-08 16:09:14,574 - faraday.launcher - INFO - Copying default configuration from project.
2016-07-08 16:09:14,575 - faraday.launcher - INFO - Setting up libraries.
2016-07-08 16:09:14,580 - faraday.launcher - INFO - x86_64 linux detected.
2016-07-08 16:09:14,585 - faraday.launcher - INFO - Setting configuration.
2016-07-08 16:09:15,064 - faraday.launcher - INFO - No updates available, enjoy Faraday
2016-07-08 16:09:15,238 - faraday.launcher - INFO - All done. Opening environment.
Traceback (most recent call last):
  File "./faraday.py", line 641, in <module>
    main()
  File "./faraday.py", line 635, in main
    startFaraday()
  File "./faraday.py", line 304, in startFaraday
    main_app = MainApplication(args)
  File "/home/chintu/faraday-dev/model/application.py", line 99, in __init__
    self.args.gui)
  File "/home/chintu/faraday-dev/gui/gui_app.py", line 25, in create
    return GuiApp(model_controller, plugin_manager, workspace_manager, plugin_controller)
  File "/home/chintu/faraday-dev/gui/gtk/application.py", line 100, in __init__
    16, False)
GLib.Error: g-file-error-quark: Failed to open file '/home/chintu/.faraday/images/icons/faraday_icon.png': No such file or directory (4)

**Comment by ichintu** [comment]
I should have provided more information:
ubuntu gnome 16.04
I am trying to run in GUI mode.
this is my first attempt to run it. i did git clone and install.sh

**Comment by Ezequieltbh** [comment]
Hi!
Your faraday installation is clean?
This file, home/chintu/.faraday/images/icons/faraday_icon.png, should exist.
Can you check this?
If this file does not exist, you can run this command to copy it.
cp $FARADAY_DIR/data/images/icons/faraday_icon.png /home/chintu/.faraday/images/icons/

Replace $FARADAY_DIR with the path to Faraday.
Cheers.

**Comment by Ezequieltbh** [comment]
Thanks for report this bug, we introduced this in the last release.
Use this command for fix this.

**Comment by Ezequieltbh** [comment]
Thanks for report this bug, this have been introduced in the last version.
Use this command (Forget the previous) for fix this issue.

cp -r $FARADAY_DIR/data/images/icons/ /home/chintu/.faraday/images/icons/

Replace $FARADAY_DIR with the path to Faraday.
Cheers

**Comment by ichintu** [comment]
thanks this fixed it.

**Comment by Ezequieltbh** [comment]
Excelent, this will be fixed in the next release.
Thanks for report this.
